"""Chunk 5 — Big push (100 claims):
   trigonometry, sequences, exp/log, probability, combinatorics, advanced geometry.
   Imported by seed_curriculum.py.
"""
from __future__ import annotations

from core.models import Claim, Course, Proof


CANON = "canonical"


def C(cid, kind, course, topic, stmt):
    return Claim(id=cid, kind=kind, status=CANON, course=course,
                 topic=topic, statement=stmt)


def P(pid, cid, deps, body, method="informal", status="reviewed", canonical=True):
    return Proof(id=pid, claim_id=cid, dependencies=list(deps), body=body,
                 method=method, status=status, is_canonical=canonical)


HS3 = "math_hs_3"
HS4 = "math_hs_4"


COURSES = [
    Course(id=HS4, name="מתמטיקה תיכון 4 יחל",
           prerequisites=["math_hs_3"]),
]


CLAIMS = [
    # ═══ math_hs_3 extensions ═══

    # ── Trigonometry: definitions & basic identities ──
    C("def_radian", "definition", HS3, "טריגונומטריה",
      r"**רדיאן:** מידת זווית המוגדרת על-ידי היחס בין אורך הקשת לאורך הרדיוס במעגל. זווית של $1$ רדיאן היא הזווית המרכזית הקובעת קשת באורך הרדיוס."),
    C("def_degree", "definition", HS3, "טריגונומטריה",
      r"**מעלה:** מידת זווית כאשר מעגל מלא מחולק ל-$360$ חלקים שווים. הקשר לרדיאנים: $180° = \pi$ רדיאן."),
    C("def_unit_circle", "definition", HS3, "טריגונומטריה",
      r"**מעגל היחידה:** המעגל שמרכזו בראשית הצירים $(0,0)$ ורדיוסו $1$. משוואתו: $x^2 + y^2 = 1$."),
    C("def_sin", "definition", HS3, "טריגונומטריה",
      r"**סינוס:** עבור זווית $\theta$, $\sin\theta$ הוא הקואורדינטה $y$ של הנקודה במעגל היחידה שמתאימה לזווית $\theta$ (נמדדת נגד כיוון השעון מהציר החיובי של $x$)."),
    C("def_cos", "definition", HS3, "טריגונומטריה",
      r"**קוסינוס:** עבור זווית $\theta$, $\cos\theta$ הוא הקואורדינטה $x$ של הנקודה במעגל היחידה שמתאימה לזווית $\theta$."),
    C("def_tan", "definition", HS3, "טריגונומטריה",
      r"**טנגנס:** $\tan\theta := \frac{\sin\theta}{\cos\theta}$ (מוגדר כאשר $\cos\theta \neq 0$)."),
    C("thm_sin_cos_pythagorean", "theorem", HS3, "טריגונומטריה",
      r"**זהות פיתגוראית טריגונומטרית:** לכל $\theta$ מתקיים $\sin^2\theta + \cos^2\theta = 1$."),
    C("thm_tan_in_sin_cos", "theorem", HS3, "טריגונומטריה",
      r"**טנגנס כיחס:** $\tan\theta = \frac{\sin\theta}{\cos\theta}$ — מההגדרה ישירות."),
    C("thm_sin_periodicity", "theorem", HS3, "טריגונומטריה",
      r"**מחזוריות סינוס:** $\sin(\theta + 2\pi) = \sin\theta$ לכל $\theta$."),
    C("thm_cos_periodicity", "theorem", HS3, "טריגונומטריה",
      r"**מחזוריות קוסינוס:** $\cos(\theta + 2\pi) = \cos\theta$ לכל $\theta$."),
    C("thm_sin_special_values", "theorem", HS3, "טריגונומטריה",
      r"**ערכים מיוחדים של סינוס:** $\sin 0 = 0$, $\sin\frac{\pi}{6} = \frac{1}{2}$, $\sin\frac{\pi}{4} = \frac{\sqrt{2}}{2}$, $\sin\frac{\pi}{3} = \frac{\sqrt{3}}{2}$, $\sin\frac{\pi}{2} = 1$."),
    C("thm_cos_special_values", "theorem", HS3, "טריגונומטריה",
      r"**ערכים מיוחדים של קוסינוס:** $\cos 0 = 1$, $\cos\frac{\pi}{6} = \frac{\sqrt{3}}{2}$, $\cos\frac{\pi}{4} = \frac{\sqrt{2}}{2}$, $\cos\frac{\pi}{3} = \frac{1}{2}$, $\cos\frac{\pi}{2} = 0$."),

    # ── Sequences ──
    C("def_sequence", "definition", HS3, "סדרות",
      r"**סדרה:** פונקציה $a: \mathbb{N} \to \mathbb{R}$. נסמן את הערך ב-$n$ כ-$a_n$, וכותבים $(a_n)_{n=1}^{\infty}$ או $a_1, a_2, a_3, \ldots$"),
    C("def_arithmetic_sequence", "definition", HS3, "סדרות",
      r"**סדרה חשבונית:** סדרה $(a_n)$ שבה ההפרש בין כל איבר לקודמו קבוע: $a_{n+1} - a_n = d$ לכל $n$ (כאשר $d$ נקרא ה**הפרש**)."),
    C("def_geometric_sequence", "definition", HS3, "סדרות",
      r"**סדרה הנדסית:** סדרה $(a_n)$ שבה היחס בין כל איבר לקודמו קבוע: $\frac{a_{n+1}}{a_n} = q$ לכל $n$ (כאשר $q$ נקרא ה**מנה**, $a_n \neq 0$)."),
    C("thm_arithmetic_nth_term", "theorem", HS3, "סדרות",
      r"**איבר כללי בסדרה חשבונית:** בסדרה חשבונית עם איבר ראשון $a_1$ והפרש $d$ מתקיים $a_n = a_1 + (n - 1) \cdot d$."),
    C("thm_geometric_nth_term", "theorem", HS3, "סדרות",
      r"**איבר כללי בסדרה הנדסית:** בסדרה הנדסית עם איבר ראשון $a_1$ ומנה $q$ מתקיים $a_n = a_1 \cdot q^{n-1}$."),
    C("thm_arithmetic_sum", "theorem", HS3, "סדרות",
      r"**סכום סדרה חשבונית:** $S_n = a_1 + a_2 + \cdots + a_n = \frac{n \cdot (a_1 + a_n)}{2} = \frac{n \cdot (2 a_1 + (n-1) d)}{2}$."),
    C("thm_geometric_sum_finite", "theorem", HS3, "סדרות",
      r"**סכום סופי של סדרה הנדסית:** עבור $q \neq 1$: $S_n = a_1 \cdot \frac{q^n - 1}{q - 1}$. עבור $q = 1$: $S_n = n \cdot a_1$."),
    C("def_recursive_sequence", "definition", HS3, "סדרות",
      r"**סדרה נסיגתית:** סדרה המוגדרת על-ידי איברים ראשונים נתונים וכלל שמחשב כל איבר נוסף מהקודמים. לדוגמה, פיבונאצ׳י: $F_1 = F_2 = 1$, $F_{n+2} = F_{n+1} + F_n$."),

    # ── Function properties ──
    C("def_composition_of_functions", "definition", HS3, "תכונות פונקציות",
      r"**הרכבת פונקציות:** עבור $f: A \to B$ ו-$g: B \to C$, הרכבתן היא $(g \circ f)(x) := g(f(x))$."),
    C("def_inverse_function", "definition", HS3, "תכונות פונקציות",
      r"**פונקציה הפוכה:** $f^{-1}$ היא הפונקציה המקיימת $f^{-1}(f(x)) = x$ ו-$f(f^{-1}(y)) = y$ (קיימת אם ורק אם $f$ חד-חד-ערכית)."),
    C("def_even_function", "definition", HS3, "תכונות פונקציות",
      r"**פונקציה זוגית:** פונקציה $f$ נקראת **זוגית** אם $f(-x) = f(x)$ לכל $x$ בתחום ההגדרה. הגרף סימטרי ביחס לציר $y$."),
    C("def_odd_function", "definition", HS3, "תכונות פונקציות",
      r"**פונקציה אי-זוגית:** פונקציה $f$ נקראת **אי-זוגית** אם $f(-x) = -f(x)$ לכל $x$ בתחום. הגרף סימטרי ביחס לראשית הצירים."),
    C("def_periodic_function", "definition", HS3, "תכונות פונקציות",
      r"**פונקציה מחזורית:** פונקציה $f$ נקראת **מחזורית** אם קיים $T > 0$ כך ש-$f(x + T) = f(x)$ לכל $x$. ה-$T$ המינימלי נקרא ה**מחזור**."),
    C("def_increasing_function", "definition", HS3, "תכונות פונקציות",
      r"**פונקציה עולה:** פונקציה $f$ נקראת **עולה** בתחום $I$ אם לכל $x_1, x_2 \in I$, $x_1 < x_2 \Rightarrow f(x_1) < f(x_2)$."),
    C("def_decreasing_function", "definition", HS3, "תכונות פונקציות",
      r"**פונקציה יורדת:** פונקציה $f$ נקראת **יורדת** בתחום $I$ אם לכל $x_1, x_2 \in I$, $x_1 < x_2 \Rightarrow f(x_1) > f(x_2)$."),
    C("def_monotonic_function", "definition", HS3, "תכונות פונקציות",
      r"**פונקציה מונוטונית:** פונקציה שהיא עולה בכל תחום ההגדרה, או יורדת בכל תחום ההגדרה."),

    # ═══ math_hs_4 — advanced trig ═══
    C("thm_sin_addition_formula", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**נוסחת חיבור לסינוס:** $\sin(\alpha + \beta) = \sin\alpha \cos\beta + \cos\alpha \sin\beta$."),
    C("thm_cos_addition_formula", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**נוסחת חיבור לקוסינוס:** $\cos(\alpha + \beta) = \cos\alpha \cos\beta - \sin\alpha \sin\beta$."),
    C("thm_sin_subtraction_formula", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**נוסחת חיסור לסינוס:** $\sin(\alpha - \beta) = \sin\alpha \cos\beta - \cos\alpha \sin\beta$."),
    C("thm_cos_subtraction_formula", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**נוסחת חיסור לקוסינוס:** $\cos(\alpha - \beta) = \cos\alpha \cos\beta + \sin\alpha \sin\beta$."),
    C("thm_sin_double_angle", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**סינוס של זווית כפולה:** $\sin(2\alpha) = 2 \sin\alpha \cos\alpha$."),
    C("thm_cos_double_angle", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**קוסינוס של זווית כפולה:** $\cos(2\alpha) = \cos^2\alpha - \sin^2\alpha = 2\cos^2\alpha - 1 = 1 - 2\sin^2\alpha$."),
    C("thm_tan_double_angle", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**טנגנס של זווית כפולה:** $\tan(2\alpha) = \frac{2 \tan\alpha}{1 - \tan^2\alpha}$ (כאשר המכנה אינו אפס)."),
    C("thm_sin_odd", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**סינוס פונקציה אי-זוגית:** $\sin(-\theta) = -\sin\theta$."),
    C("thm_cos_even", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**קוסינוס פונקציה זוגית:** $\cos(-\theta) = \cos\theta$."),
    C("thm_sin_complementary", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**זוויות משלימות:** $\sin\!\left(\frac{\pi}{2} - \theta\right) = \cos\theta$ ו-$\cos\!\left(\frac{\pi}{2} - \theta\right) = \sin\theta$."),
    C("thm_law_of_sines", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**משפט הסינוסים:** בכל משולש עם צלעות $a, b, c$ וזוויות מתאימות $A, B, C$ מתקיים $\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C} = 2R$, כאשר $R$ הוא רדיוס המעגל החוסם."),
    C("thm_law_of_cosines", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**משפט הקוסינוסים:** בכל משולש $c^2 = a^2 + b^2 - 2ab \cos C$."),

    # ═══ math_hs_4 — exponentials & logs ═══
    C("def_exponential_function", "definition", HS4, "מעריכיים",
      r"**פונקציה מעריכית:** $f(x) = a^x$ עבור $a > 0$, $a \neq 1$. תחום ההגדרה $\mathbb{R}$, הטווח $(0, \infty)$."),
    C("thm_exp_addition", "theorem", HS4, "מעריכיים",
      r"**חיבור מעריכים (כללי):** $a^{x+y} = a^x \cdot a^y$ לכל $x, y \in \mathbb{R}$."),
    C("thm_exp_multiplication", "theorem", HS4, "מעריכיים",
      r"**חזקה של חזקה (כללי):** $(a^x)^y = a^{x \cdot y}$ לכל $x, y \in \mathbb{R}$ ו-$a > 0$."),
    C("thm_exp_zero", "theorem", HS4, "מעריכיים",
      r"**חזקה אפסית:** $a^0 = 1$ לכל $a \neq 0$."),
    C("thm_exp_negative", "theorem", HS4, "מעריכיים",
      r"**חזקה שלילית:** $a^{-x} = \frac{1}{a^x}$ לכל $a > 0$."),
    C("thm_exp_increasing", "theorem", HS4, "מעריכיים",
      r"**מעריכית עולה:** $f(x) = a^x$ עולה ממש כאשר $a > 1$."),
    C("thm_exp_decreasing", "theorem", HS4, "מעריכיים",
      r"**מעריכית יורדת:** $f(x) = a^x$ יורדת ממש כאשר $0 < a < 1$."),
    C("def_logarithm", "definition", HS4, "לוגריתמים",
      r"**לוגריתם:** עבור $b > 0$, $b \neq 1$ ו-$x > 0$: $\log_b x := y$ אם ורק אם $b^y = x$. הלוגריתם הוא הפונקציה ההפוכה של הפונקציה המעריכית $b^y$."),
    C("thm_log_of_product", "theorem", HS4, "לוגריתמים",
      r"**לוגריתם של מכפלה:** $\log_b(x \cdot y) = \log_b x + \log_b y$ לכל $x, y > 0$."),
    C("thm_log_of_quotient", "theorem", HS4, "לוגריתמים",
      r"**לוגריתם של מנה:** $\log_b\!\left(\frac{x}{y}\right) = \log_b x - \log_b y$ לכל $x, y > 0$."),
    C("thm_log_of_power", "theorem", HS4, "לוגריתמים",
      r"**לוגריתם של חזקה:** $\log_b(x^n) = n \cdot \log_b x$ לכל $x > 0$ ו-$n \in \mathbb{R}$."),
    C("thm_log_change_of_base", "theorem", HS4, "לוגריתמים",
      r"**שינוי בסיס לוגריתם:** $\log_b x = \frac{\log_c x}{\log_c b}$ לכל בסיסים $b, c$ חיוביים שונים מ-$1$."),
    C("thm_log_one", "theorem", HS4, "לוגריתמים",
      r"**לוגריתם של $1$:** $\log_b 1 = 0$ לכל בסיס $b$ חוקי."),
    C("thm_log_inverse_of_exp", "theorem", HS4, "לוגריתמים",
      r"**לוגריתם כהפוכה למעריכית:** $\log_b(b^x) = x$ ו-$b^{\log_b x} = x$ (לכל $x > 0$ בנוסחה השנייה)."),
    C("def_natural_log", "definition", HS4, "לוגריתמים",
      r"**לוגריתם טבעי:** $\ln x := \log_e x$, כאשר $e \approx 2.71828\ldots$ הוא קבוע אוילר."),

    # ═══ math_hs_4 — sequences advanced ═══
    C("def_limit_of_sequence", "definition", HS4, "סדרות מתקדם",
      r"**גבול סדרה:** $\lim_{n \to \infty} a_n = L$ אם לכל $\epsilon > 0$ קיים $N \in \mathbb{N}$ כך שלכל $n > N$ מתקיים $|a_n - L| < \epsilon$."),
    C("def_convergent_sequence", "definition", HS4, "סדרות מתקדם",
      r"**סדרה מתכנסת:** סדרה $(a_n)$ נקראת **מתכנסת** אם קיים $L \in \mathbb{R}$ כך ש-$\lim_{n \to \infty} a_n = L$. אחרת היא **מתבדרת**."),
    C("def_infinite_geometric_series", "definition", HS4, "סדרות מתקדם",
      r"**טור הנדסי אינסופי:** עבור סדרה הנדסית $a_1, a_1 q, a_1 q^2, \ldots$, הטור האינסופי הוא $S = \sum_{n=1}^{\infty} a_1 q^{n-1}$, המוגדר כגבול של הסכומים החלקיים."),
    C("thm_geometric_series_convergence", "theorem", HS4, "סדרות מתקדם",
      r"**התכנסות טור הנדסי:** טור הנדסי אינסופי $\sum_{n=1}^{\infty} a_1 q^{n-1}$ מתכנס אם ורק אם $|q| < 1$, ואז $S = \frac{a_1}{1 - q}$."),
    C("thm_squeeze_theorem", "theorem", HS4, "סדרות מתקדם",
      r"**משפט הסנדוויץ׳:** אם $a_n \leq b_n \leq c_n$ לכל $n$ גדול מספיק, ו-$\lim a_n = \lim c_n = L$, אז $\lim b_n = L$."),

    # ═══ math_hs_4 — probability ═══
    C("def_sample_space", "definition", HS4, "הסתברות",
      r"**מרחב מדגם:** הקבוצה $\Omega$ של כל התוצאות האפשריות של ניסוי אקראי."),
    C("def_event", "definition", HS4, "הסתברות",
      r"**מאורע:** תת-קבוצה $A \subseteq \Omega$ של המרחב המדגם."),
    C("def_probability_function", "definition", HS4, "הסתברות",
      r"**פונקציית הסתברות:** פונקציה $P$ מקבוצת המאורעות לקטע $[0, 1]$ המקיימת את אקסיומות קולמוגורוב."),
    C("ax_probability_nonneg", "axiom", HS4, "הסתברות",
      r"**אקסיומת קולמוגורוב — אי-שליליות:** $P(A) \geq 0$ לכל מאורע $A$."),
    C("ax_probability_total", "axiom", HS4, "הסתברות",
      r"**אקסיומת קולמוגורוב — נורמליזציה:** $P(\Omega) = 1$ (הסתברות של המרחב כולו היא $1$)."),
    C("ax_probability_additivity", "axiom", HS4, "הסתברות",
      r"**אקסיומת קולמוגורוב — אדיטיביות:** אם $A_1, A_2, \ldots$ מאורעות זרים בזוגות, אז $P\!\left(\bigcup_i A_i\right) = \sum_i P(A_i)$."),
    C("thm_complement_probability", "theorem", HS4, "הסתברות",
      r"**הסתברות המשלים:** $P(A^c) = 1 - P(A)$."),
    C("thm_empty_probability", "theorem", HS4, "הסתברות",
      r"**הסתברות הקבוצה הריקה:** $P(\emptyset) = 0$."),
    C("thm_union_probability", "theorem", HS4, "הסתברות",
      r"**הסתברות איחוד (הכלה-הפרדה לשניים):** $P(A \cup B) = P(A) + P(B) - P(A \cap B)$."),
    C("def_conditional_probability", "definition", HS4, "הסתברות",
      r"**הסתברות מותנית:** $P(A \mid B) := \frac{P(A \cap B)}{P(B)}$ (עבור $P(B) > 0$)."),
    C("def_independent_events", "definition", HS4, "הסתברות",
      r"**מאורעות בלתי תלויים:** $A$ ו-$B$ נקראים **בלתי תלויים** אם $P(A \cap B) = P(A) \cdot P(B)$."),
    C("thm_bayes", "theorem", HS4, "הסתברות",
      r"**משפט בייס:** $P(A \mid B) = \frac{P(B \mid A) \cdot P(A)}{P(B)}$ (כאשר $P(B) > 0$)."),

    # ═══ math_hs_4 — combinatorics ═══
    C("def_factorial", "definition", HS4, "קומבינטוריקה",
      r"**עצרת:** $n! := n \cdot (n-1) \cdot (n-2) \cdots 2 \cdot 1$ עבור $n \in \mathbb{N}$, ובמיוחד $0! := 1$."),
    C("def_permutation", "definition", HS4, "קומבינטוריקה",
      r"**תמורה (פרמוטציה):** סידור של $n$ אלמנטים שונים בשורה. מספר התמורות הוא $n!$."),
    C("def_combination", "definition", HS4, "קומבינטוריקה",
      r"**צירוף (קומבינציה):** בחירת קבוצה לא מסודרת של $k$ איברים מתוך $n$. מסומן $\binom{n}{k}$ או $C(n, k)$."),
    C("def_binomial_coefficient", "definition", HS4, "קומבינטוריקה",
      r"**מקדם בינומי:** $\binom{n}{k}$ — מספר הדרכים לבחור $k$ איברים מתוך $n$ ללא חשיבות לסדר."),
    C("thm_combinations_formula", "theorem", HS4, "קומבינטוריקה",
      r"**נוסחת הצירופים:** $\binom{n}{k} = \frac{n!}{k! \cdot (n - k)!}$."),
    C("thm_pascal_identity", "theorem", HS4, "קומבינטוריקה",
      r"**זהות פסקל:** $\binom{n}{k} = \binom{n-1}{k-1} + \binom{n-1}{k}$ עבור $1 \leq k \leq n-1$."),
    C("thm_binomial_theorem", "theorem", HS4, "קומבינטוריקה",
      r"**הבינום של ניוטון:** $(a + b)^n = \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^k$."),
    C("thm_sum_of_binomial_coefficients", "theorem", HS4, "קומבינטוריקה",
      r"**סכום מקדמים בינומיים:** $\sum_{k=0}^{n} \binom{n}{k} = 2^n$."),

    # ═══ math_hs_4 — more geometry ═══
    C("def_tangent_to_circle", "definition", HS4, "גאומטריית מעגל",
      r"**משיק למעגל:** ישר הנפגש עם המעגל בנקודה אחת בלבד."),
    C("def_central_angle", "definition", HS4, "גאומטריית מעגל",
      r"**זווית מרכזית:** זווית שקודקודה במרכז המעגל. גודלה שווה לקשת שעליה היא נשענת (כאשר מודדים את הקשת ברדיאנים)."),
    C("thm_tangent_perpendicular_to_radius", "theorem", HS4, "גאומטריית מעגל",
      r"**משיק מאונך לרדיוס:** משיק למעגל בנקודת ההשקה מאונך לרדיוס באותה נקודה."),
    C("thm_thales", "theorem", HS4, "גאומטריית מעגל",
      r"**משפט תאלס (מעגל):** אם $AB$ קוטר במעגל ו-$C$ נקודה כלשהי במעגל, אז זווית $\angle ACB = 90°$."),
    C("thm_perpendicular_diameter_bisects_chord", "theorem", HS4, "גאומטריית מעגל",
      r"**אנך לקוטר חוצה מיתר:** אנך ממרכז המעגל למיתר חוצה את המיתר ואת הקשת שמולו."),
    C("thm_inscribed_angles_same_arc", "theorem", HS4, "גאומטריית מעגל",
      r"**זוויות היקפיות על אותה קשת:** כל הזוויות ההיקפיות הנשענות על אותה קשת שוות בגודלן."),
    C("thm_opposite_angles_cyclic_quad", "theorem", HS4, "גאומטריית מעגל",
      r"**זוויות נגדיות במרובע חסום:** במרובע החסום במעגל, סכום זוויות נגדיות = $180°$."),
    C("def_inscribed_polygon", "definition", HS4, "גאומטריית מעגל",
      r"**מצולע חסום:** מצולע שכל קודקודיו על מעגל אחד (המעגל החוסם)."),
    C("def_circumscribed_polygon", "definition", HS4, "גאומטריית מעגל",
      r"**מצולע חוסם:** מצולע שכל צלעותיו משיקות למעגל פנימי (המעגל החסום במצולע)."),
    C("thm_chord_secant_power", "theorem", HS4, "גאומטריית מעגל",
      r"**משפט הכוח של נקודה:** עבור נקודה $P$ ושני מיתרים/חותכים דרכה במעגל החותכים אותו בנקודות $A, B$ ו-$C, D$ בהתאמה, מתקיים $PA \cdot PB = PC \cdot PD$."),

    # ═══ math_hs_4 — calculus prep ═══
    C("def_function_continuity_intuitive", "definition", HS4, "הקדמה לחדו״א",
      r"**רציפות (אינטואיטיבית):** פונקציה $f$ נקראת **רציפה** ב-$x_0$ אם ערכה ב-$x_0$ ושאר הערכים בקרבת $x_0$ קרובים זה לזה — אין 'קפיצות'. פורמלית: $\lim_{x \to x_0} f(x) = f(x_0)$."),
    C("def_function_limit_intuitive", "definition", HS4, "הקדמה לחדו״א",
      r"**גבול פונקציה (אינטואיטיבי):** $\lim_{x \to x_0} f(x) = L$ אם ככל ש-$x$ מתקרב ל-$x_0$ (משני הצדדים), ערכי $f(x)$ מתקרבים ל-$L$."),
    C("def_extremum", "definition", HS4, "הקדמה לחדו״א",
      r"**ערך קיצון:** $f(x_0)$ הוא **מקסימום גלובלי** אם $f(x_0) \geq f(x)$ לכל $x$ בתחום. **מינימום גלובלי** באופן סימטרי."),
    C("def_local_extremum", "definition", HS4, "הקדמה לחדו״א",
      r"**ערך קיצון מקומי:** $f(x_0)$ הוא **מקסימום מקומי** אם קיימת סביבה של $x_0$ שבה $f(x_0) \geq f(x)$ לכל $x$ בסביבה. **מינימום מקומי** סימטרית."),
    C("def_function_zeros", "definition", HS4, "הקדמה לחדו״א",
      r"**אפסי פונקציה:** הערכים $x$ בתחום שעבורם $f(x) = 0$. אלה נקודות החיתוך של הגרף עם ציר $x$."),
    C("thm_intermediate_value", "theorem", HS4, "הקדמה לחדו״א",
      r"**משפט ערך הביניים:** אם $f$ רציפה ב-$[a, b]$ ו-$y$ נמצא בין $f(a)$ ל-$f(b)$, אז קיים $c \in [a, b]$ עם $f(c) = y$."),
    C("def_secant_line", "definition", HS4, "הקדמה לחדו״א",
      r"**ישר חותך (סקנט):** הישר העובר דרך שתי נקודות על גרף הפונקציה: $(x_1, f(x_1))$ ו-$(x_2, f(x_2))$."),
    C("def_average_rate_of_change", "definition", HS4, "הקדמה לחדו״א",
      r"**שיעור שינוי ממוצע:** השיפוע של הישר החותך — $\frac{f(x_2) - f(x_1)}{x_2 - x_1}$."),
    C("def_difference_quotient", "definition", HS4, "הקדמה לחדו״א",
      r"**מנת ההפרשים:** $\frac{f(x + h) - f(x)}{h}$ — הביטוי שגבולו ($h \to 0$) הוא הנגזרת."),
    C("def_secant_to_circle", "definition", HS4, "גאומטריית מעגל",
      r"**חותך למעגל:** ישר החותך את המעגל בשתי נקודות שונות."),
]


PROOFS = [
    # ── Trig (sin/cos basic) ──
    P("prf_sin_cos_pythagorean", "thm_sin_cos_pythagorean",
      ["def_sin", "def_cos", "def_unit_circle"],
      "מהגדרת סינוס וקוסינוס במעגל היחידה, הנקודה $(\\cos\\theta, \\sin\\theta)$ נמצאת על מעגל היחידה שמשוואתו $x^2 + y^2 = 1$.\n\nמכאן $\\cos^2\\theta + \\sin^2\\theta = 1$. $\\blacksquare$"),
    P("prf_tan_in_sin_cos", "thm_tan_in_sin_cos",
      ["def_tan"],
      "ישירות מהגדרת הטנגנס $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$. $\\blacksquare$"),
    P("prf_sin_periodicity", "thm_sin_periodicity",
      ["def_sin", "def_unit_circle"],
      "תוספת של $2\\pi$ לזווית מתאימה לסיבוב מלא במעגל היחידה, שמחזיר את הנקודה לעצמה. לכן הקואורדינטה $y$ (סינוס) לא משתנה. $\\blacksquare$"),
    P("prf_cos_periodicity", "thm_cos_periodicity",
      ["def_cos", "def_unit_circle"],
      "באותו טיעון כמו ב-$\\sin$: סיבוב $2\\pi$ הוא סיבוב מלא במעגל היחידה ולכן הקואורדינטה $x$ נשמרת. $\\blacksquare$"),
    P("prf_sin_odd", "thm_sin_odd",
      ["def_sin", "def_unit_circle"],
      "הזווית $-\\theta$ מתאימה לנקודה $(\\cos\\theta, -\\sin\\theta)$ במעגל היחידה (שיקוף אופקי).\n\nלכן $\\sin(-\\theta) = -\\sin\\theta$. $\\blacksquare$"),
    P("prf_cos_even", "thm_cos_even",
      ["def_cos", "def_unit_circle"],
      "כמו ב-$\\sin$: הזווית $-\\theta$ נותנת נקודה $(\\cos\\theta, -\\sin\\theta)$. הקואורדינטה $x$ נשמרת, לכן $\\cos(-\\theta) = \\cos\\theta$. $\\blacksquare$"),
    P("prf_cos_addition_formula", "thm_cos_addition_formula",
      ["def_cos", "def_sin", "def_unit_circle", "thm_law_of_cosines"],
      "**גישה גאומטרית:** ניקח שתי נקודות במעגל היחידה — $A = (\\cos\\alpha, \\sin\\alpha)$ ו-$B = (\\cos\\beta, \\sin\\beta)$.\n\nהמרחק בריבוע $|AB|^2 = (\\cos\\alpha - \\cos\\beta)^2 + (\\sin\\alpha - \\sin\\beta)^2 = 2 - 2(\\cos\\alpha\\cos\\beta + \\sin\\alpha\\sin\\beta)$.\n\nמצד שני, לפי משפט הקוסינוסים במשולש המכיל את הזווית $\\alpha - \\beta$: $|AB|^2 = 1 + 1 - 2\\cos(\\alpha - \\beta)$.\n\nהשוואה: $\\cos(\\alpha - \\beta) = \\cos\\alpha\\cos\\beta + \\sin\\alpha\\sin\\beta$, ולכן $\\cos(\\alpha + \\beta) = \\cos(\\alpha - (-\\beta)) = \\cos\\alpha\\cos(-\\beta) + \\sin\\alpha\\sin(-\\beta) = \\cos\\alpha\\cos\\beta - \\sin\\alpha\\sin\\beta$. $\\blacksquare$"),
    P("prf_sin_addition_formula", "thm_sin_addition_formula",
      ["thm_cos_addition_formula", "thm_sin_complementary", "thm_cos_even"],
      "$\\sin(\\alpha + \\beta) = \\cos\\!\\left(\\tfrac{\\pi}{2} - (\\alpha + \\beta)\\right) = \\cos\\!\\left((\\tfrac{\\pi}{2} - \\alpha) - \\beta\\right)$\n\n$= \\cos\\!\\left(\\tfrac{\\pi}{2} - \\alpha\\right)\\cos\\beta + \\sin\\!\\left(\\tfrac{\\pi}{2} - \\alpha\\right)\\sin\\beta = \\sin\\alpha\\cos\\beta + \\cos\\alpha\\sin\\beta$. $\\blacksquare$"),
    P("prf_sin_subtraction_formula", "thm_sin_subtraction_formula",
      ["thm_sin_addition_formula", "thm_sin_odd", "thm_cos_even"],
      "$\\sin(\\alpha - \\beta) = \\sin(\\alpha + (-\\beta)) = \\sin\\alpha\\cos(-\\beta) + \\cos\\alpha\\sin(-\\beta) = \\sin\\alpha\\cos\\beta - \\cos\\alpha\\sin\\beta$. $\\blacksquare$"),
    P("prf_cos_subtraction_formula", "thm_cos_subtraction_formula",
      ["thm_cos_addition_formula", "thm_sin_odd", "thm_cos_even"],
      "$\\cos(\\alpha - \\beta) = \\cos(\\alpha + (-\\beta)) = \\cos\\alpha\\cos(-\\beta) - \\sin\\alpha\\sin(-\\beta) = \\cos\\alpha\\cos\\beta + \\sin\\alpha\\sin\\beta$. $\\blacksquare$"),
    P("prf_sin_double_angle", "thm_sin_double_angle",
      ["thm_sin_addition_formula"],
      "$\\sin(2\\alpha) = \\sin(\\alpha + \\alpha) = \\sin\\alpha\\cos\\alpha + \\cos\\alpha\\sin\\alpha = 2\\sin\\alpha\\cos\\alpha$. $\\blacksquare$"),
    P("prf_cos_double_angle", "thm_cos_double_angle",
      ["thm_cos_addition_formula", "thm_sin_cos_pythagorean"],
      "$\\cos(2\\alpha) = \\cos(\\alpha + \\alpha) = \\cos^2\\alpha - \\sin^2\\alpha$.\n\nהצורות החלופיות מתקבלות מהזהות $\\sin^2 + \\cos^2 = 1$: $\\cos^2 - \\sin^2 = \\cos^2 - (1 - \\cos^2) = 2\\cos^2\\alpha - 1$, ובאופן דומה $= 1 - 2\\sin^2\\alpha$. $\\blacksquare$"),
    P("prf_tan_double_angle", "thm_tan_double_angle",
      ["def_tan", "thm_sin_double_angle", "thm_cos_double_angle"],
      "$\\tan(2\\alpha) = \\frac{\\sin(2\\alpha)}{\\cos(2\\alpha)} = \\frac{2\\sin\\alpha\\cos\\alpha}{\\cos^2\\alpha - \\sin^2\\alpha}$.\n\nנחלק מונה ומכנה ב-$\\cos^2\\alpha$: $= \\frac{2\\tan\\alpha}{1 - \\tan^2\\alpha}$. $\\blacksquare$"),
    P("prf_law_of_cosines", "thm_law_of_cosines",
      ["thm_pythagoras", "def_cos", "ax_distributive_law"],
      "במשולש עם זווית $C$, נוריד גובה מהקודקוד אל הצלע המקבילה. נסמן את הרגלים שנוצרות ב-$h$ ו-$d$, כאשר $d = a\\cos C$ ו-$h = a\\sin C$.\n\nלפי פיתגורס: $c^2 = h^2 + (b - d)^2 = a^2\\sin^2 C + (b - a\\cos C)^2 = a^2(\\sin^2 C + \\cos^2 C) + b^2 - 2ab\\cos C = a^2 + b^2 - 2ab\\cos C$. $\\blacksquare$"),

    # ── Sequences ──
    P("prf_arithmetic_nth_term", "thm_arithmetic_nth_term",
      ["def_arithmetic_sequence"],
      "אינדוקציה על $n$. בסיס $n = 1$: $a_1 = a_1 + 0 \\cdot d$. ✓\n\nצעד: אם $a_n = a_1 + (n-1)d$, אז $a_{n+1} = a_n + d = a_1 + (n-1)d + d = a_1 + n \\cdot d$. $\\blacksquare$"),
    P("prf_geometric_nth_term", "thm_geometric_nth_term",
      ["def_geometric_sequence", "thm_power_addition_rule"],
      "אינדוקציה על $n$. בסיס $n = 1$: $a_1 = a_1 \\cdot q^0$. ✓\n\nצעד: אם $a_n = a_1 q^{n-1}$, אז $a_{n+1} = a_n \\cdot q = a_1 q^{n-1} \\cdot q = a_1 q^n$. $\\blacksquare$"),
    P("prf_arithmetic_sum", "thm_arithmetic_sum",
      ["def_arithmetic_sequence", "thm_arithmetic_nth_term"],
      "הטריק של גאוס: נכתוב $S_n = a_1 + a_2 + \\cdots + a_n$ ושוב $S_n = a_n + a_{n-1} + \\cdots + a_1$. בסכימה איבר-איבר, כל זוג נותן $a_1 + a_n$, ויש $n$ זוגות:\n\n$2 S_n = n(a_1 + a_n)$, ולכן $S_n = \\frac{n(a_1 + a_n)}{2}$.\n\nהצבה $a_n = a_1 + (n-1)d$ נותנת את הצורה השנייה. $\\blacksquare$"),
    P("prf_geometric_sum_finite", "thm_geometric_sum_finite",
      ["def_geometric_sequence", "thm_geometric_nth_term", "ax_distributive_law"],
      "נסמן $S = a_1 + a_1 q + a_1 q^2 + \\cdots + a_1 q^{n-1}$. נכפול ב-$q$: $qS = a_1 q + a_1 q^2 + \\cdots + a_1 q^n$.\n\nחיסור: $qS - S = a_1 q^n - a_1$, כלומר $S(q - 1) = a_1(q^n - 1)$.\n\nעבור $q \\neq 1$: $S = a_1 \\cdot \\frac{q^n - 1}{q - 1}$. עבור $q = 1$: כל איבר שווה ל-$a_1$, סכום $n \\cdot a_1$. $\\blacksquare$"),
    P("prf_geometric_series_convergence", "thm_geometric_series_convergence",
      ["def_infinite_geometric_series", "thm_geometric_sum_finite",
       "def_limit_of_sequence", "def_convergent_sequence"],
      "מסכום סופי: $S_n = a_1 \\cdot \\frac{q^n - 1}{q - 1} = \\frac{a_1}{1 - q} - \\frac{a_1 q^n}{1 - q}$.\n\nאם $|q| < 1$ אז $q^n \\to 0$ כאשר $n \\to \\infty$, ולכן $S_n \\to \\frac{a_1}{1 - q}$.\n\nאם $|q| \\geq 1$, $q^n$ אינה שואפת ל-$0$, והטור מתבדר. $\\blacksquare$"),

    # ── Exponential & log ──
    P("prf_exp_zero", "thm_exp_zero",
      ["def_exponential_function", "ax_multiplicative_identity"],
      "מהגדרה / חוקי חזקות: $a^0 = a^{x - x} = a^x / a^x = 1$ (עבור $a \\neq 0$). או באופן ישיר $a^0 := 1$. $\\blacksquare$"),
    P("prf_exp_negative", "thm_exp_negative",
      ["def_exponential_function", "thm_exp_addition", "thm_exp_zero"],
      "$a^x \\cdot a^{-x} = a^{x + (-x)} = a^0 = 1$, ולכן $a^{-x} = \\frac{1}{a^x}$. $\\blacksquare$"),
    P("prf_log_one", "thm_log_one",
      ["def_logarithm", "thm_exp_zero"],
      "מהגדרת לוגריתם: $\\log_b 1 = y$ אם ורק אם $b^y = 1$. ידוע $b^0 = 1$, ומכך $\\log_b 1 = 0$. $\\blacksquare$"),
    P("prf_log_inverse_of_exp", "thm_log_inverse_of_exp",
      ["def_logarithm"],
      "מהגדרה: $\\log_b(b^x) = y$ אם ורק אם $b^y = b^x$, כלומר $y = x$.\n\nובכיוון השני: $b^{\\log_b x} = b^y$ כאשר $y = \\log_b x$, ולפי הגדרה $b^y = x$. $\\blacksquare$"),
    P("prf_log_of_product", "thm_log_of_product",
      ["def_logarithm", "thm_exp_addition"],
      "יהיו $u = \\log_b x$, $v = \\log_b y$. אז $b^u = x$, $b^v = y$.\n\n$xy = b^u \\cdot b^v = b^{u+v}$, ולכן $\\log_b(xy) = u + v = \\log_b x + \\log_b y$. $\\blacksquare$"),
    P("prf_log_of_quotient", "thm_log_of_quotient",
      ["def_logarithm", "thm_exp_addition", "thm_exp_negative"],
      "$\\frac{x}{y} = x \\cdot y^{-1} = b^u \\cdot b^{-v} = b^{u-v}$, ולכן $\\log_b(x/y) = u - v = \\log_b x - \\log_b y$. $\\blacksquare$"),
    P("prf_log_of_power", "thm_log_of_power",
      ["def_logarithm", "thm_exp_multiplication"],
      "יהי $u = \\log_b x$, כך ש-$b^u = x$. אז $x^n = (b^u)^n = b^{un}$, ולכן $\\log_b(x^n) = un = n \\log_b x$. $\\blacksquare$"),
    P("prf_log_change_of_base", "thm_log_change_of_base",
      ["def_logarithm", "thm_log_of_power"],
      "יהי $y = \\log_b x$, כך ש-$b^y = x$. נפעיל $\\log_c$ על שני האגפים: $y \\log_c b = \\log_c x$, ולכן $y = \\frac{\\log_c x}{\\log_c b}$. $\\blacksquare$"),

    # ── Probability ──
    P("prf_complement_probability", "thm_complement_probability",
      ["ax_probability_total", "ax_probability_additivity"],
      "$A$ ו-$A^c$ זרים, $A \\cup A^c = \\Omega$. לפי אדיטיביות: $P(A) + P(A^c) = P(\\Omega) = 1$, ולכן $P(A^c) = 1 - P(A)$. $\\blacksquare$"),
    P("prf_empty_probability", "thm_empty_probability",
      ["thm_complement_probability", "ax_probability_total"],
      "$\\emptyset = \\Omega^c$, ולכן $P(\\emptyset) = 1 - P(\\Omega) = 1 - 1 = 0$. $\\blacksquare$"),
    P("prf_union_probability", "thm_union_probability",
      ["ax_probability_additivity"],
      "נכתוב $A \\cup B = A \\cup (B \\setminus A)$, איחוד זרים. וגם $B = (A \\cap B) \\cup (B \\setminus A)$, זרים.\n\nלפי אדיטיביות: $P(A \\cup B) = P(A) + P(B \\setminus A)$ ו-$P(B) = P(A \\cap B) + P(B \\setminus A)$.\n\nחיסור: $P(B \\setminus A) = P(B) - P(A \\cap B)$. הצבה: $P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$. $\\blacksquare$"),
    P("prf_bayes", "thm_bayes",
      ["def_conditional_probability"],
      "מההגדרה $P(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}$ ו-$P(B \\mid A) = \\frac{P(A \\cap B)}{P(A)}$.\n\nהצירוף נותן $P(A \\cap B) = P(B \\mid A) \\cdot P(A)$, ולכן $P(A \\mid B) = \\frac{P(B \\mid A) \\cdot P(A)}{P(B)}$. $\\blacksquare$"),

    # ── Combinatorics ──
    P("prf_combinations_formula", "thm_combinations_formula",
      ["def_combination", "def_permutation", "def_factorial"],
      "מספר התמורות של $n$ אלמנטים הוא $n!$.\n\nאם בוחרים $k$ מתוך $n$ ומסדרים, מקבלים $\\frac{n!}{(n-k)!}$ תמורות. כל בחירה לא-מסודרת מופיעה $k!$ פעמים (כי יש $k!$ סידורים של אותם $k$ איברים).\n\nלכן מספר הבחירות הוא $\\binom{n}{k} = \\frac{n!}{k!(n-k)!}$. $\\blacksquare$"),
    P("prf_pascal_identity", "thm_pascal_identity",
      ["thm_combinations_formula"],
      "**הוכחה אלגברית:** $\\binom{n-1}{k-1} + \\binom{n-1}{k} = \\frac{(n-1)!}{(k-1)!(n-k)!} + \\frac{(n-1)!}{k!(n-1-k)!} = \\frac{(n-1)! \\cdot k + (n-1)! \\cdot (n-k)}{k!(n-k)!} = \\frac{(n-1)! \\cdot n}{k!(n-k)!} = \\binom{n}{k}$.\n\n**הוכחה קומבינטורית:** מתוך $n$ איברים, נקבע איבר אחד. בחירה של $k$ איברים מפצלת לפי האם אותו איבר נכלל ($\\binom{n-1}{k-1}$) או לא ($\\binom{n-1}{k}$). $\\blacksquare$"),
    P("prf_binomial_theorem", "thm_binomial_theorem",
      ["thm_combinations_formula", "def_natural_power"],
      "אינדוקציה על $n$, או הוכחה קומבינטורית:\n\nכשמכפילים $(a+b)(a+b)\\cdots(a+b)$ $n$ פעמים ופותחים, כל איבר במכפלה הוא בחירה של $a$ או $b$ מכל גורם. איבר $a^{n-k} b^k$ נוצר ע\"י בחירת $b$ ב-$k$ מתוך $n$ גורמים, ויש $\\binom{n}{k}$ דרכים לבחור. $\\blacksquare$"),
    P("prf_sum_of_binomial_coefficients", "thm_sum_of_binomial_coefficients",
      ["thm_binomial_theorem"],
      "נציב $a = b = 1$ במשפט הבינום: $(1 + 1)^n = \\sum_{k=0}^{n} \\binom{n}{k} 1^{n-k} 1^k = \\sum_k \\binom{n}{k}$.\n\nכלומר $2^n = \\sum_{k=0}^n \\binom{n}{k}$. $\\blacksquare$"),

    # ── Function properties ──
    # (we have only definitions, no theorems to prove here)

    # ── More geometry ──
    P("prf_tangent_perpendicular_to_radius", "thm_tangent_perpendicular_to_radius",
      ["def_tangent_to_circle", "def_circle", "thm_triangle_inequality_geometry"],
      "יהי $\\ell$ משיק במעגל בנקודה $P$, ו-$O$ מרכז המעגל. נניח בשלילה ש-$OP$ אינו מאונך ל-$\\ell$.\n\nאז קיימת נקודה $Q$ על $\\ell$ עם $Q \\neq P$ כך ש-$OQ < OP$ (מורידים אנך מ-$O$ ל-$\\ell$ ומסמנים את הרגל). אבל אז $Q$ נמצאת בתוך המעגל, ולכן $\\ell$ חוצה את המעגל בעוד נקודה, סתירה לכך ש-$\\ell$ משיק.\n\nלכן $OP \\perp \\ell$. $\\blacksquare$"),
    P("prf_thales", "thm_thales",
      ["def_circle", "thm_isosceles_triangle_base_angles",
       "thm_triangle_angle_sum"],
      "יהי $AB$ קוטר במעגל עם מרכז $O$, $C$ נקודה על המעגל. $OA = OB = OC$ (רדיוסים).\n\n$\\triangle OAC$ שווה שוקיים, לכן $\\angle OAC = \\angle OCA$. ובדומה $\\angle OBC = \\angle OCB$.\n\nסכום זוויות $\\triangle ABC$: $\\angle A + \\angle B + \\angle C = (\\angle OCA) + (\\angle OCB) + (\\angle OCA + \\angle OCB) = 2(\\angle OCA + \\angle OCB) = 180°$.\n\nלכן $\\angle OCA + \\angle OCB = 90°$, כלומר $\\angle ACB = 90°$. $\\blacksquare$"),
    P("prf_perpendicular_diameter_bisects_chord", "thm_perpendicular_diameter_bisects_chord",
      ["def_circle", "ax_sss_congruence", "thm_isosceles_triangle_base_angles"],
      "יהי $AB$ מיתר, $O$ מרכז המעגל, ו-$OC \\perp AB$ עם $C$ על $AB$.\n\n$\\triangle OAC$ ו-$\\triangle OBC$: $OA = OB$ (רדיוסים), $OC$ משותף, וזוויות ישרות ב-$C$. לפי חפיפה (היפוטנוזה-ניצב), המשולשים חופפים, ולכן $AC = BC$. $\\blacksquare$"),
    P("prf_inscribed_angles_same_arc", "thm_inscribed_angles_same_arc",
      ["thm_inscribed_angle_theorem"],
      "כל זווית היקפית הנשענת על קשת מסוימת שווה למחצית הזווית המרכזית הנשענת על אותה קשת.\n\nאבל הזווית המרכזית קבועה לפי הקשת. לכן כל הזוויות ההיקפיות שוות (כל אחת = חצי מהזווית המרכזית). $\\blacksquare$"),
    P("prf_opposite_angles_cyclic_quad", "thm_opposite_angles_cyclic_quad",
      ["thm_inscribed_angle_theorem", "def_inscribed_polygon"],
      "במרובע $ABCD$ חסום במעגל, זווית $\\angle A$ נשענת על קשת $BCD$, וזווית $\\angle C$ נשענת על קשת $DAB$. \n\nהזוויות המרכזיות המתאימות מתחלקות בין שתי הקשתות לסכום $360°$, ולכן הזוויות ההיקפיות סוכמות ל-$\\tfrac{360°}{2} = 180°$.\n\nאותה דרך מראה $\\angle B + \\angle D = 180°$. $\\blacksquare$"),
]
