"""Chunk 8 — 100 claims: set theory, matrices, triangle centers, function transforms,
   statistics & probability extended, Taylor series, advanced number theory,
   extended combinatorics, applied math (finance + kinematics + decay).
"""
from __future__ import annotations

from core.models import Claim, Course, Proof


CANON = "canonical"


def C(cid, kind, course, topic, stmt):
    return Claim(id=cid, kind=kind, status=CANON, course=course,
                 topic=topic, statement=stmt)


def P(pid, cid, deps, body, method="informal", status="reviewed", canonical=True):
    return Proof(id=pid, claim_id=cid, dependencies=list(deps), body=body,
                 method=method, status=status, is_canonical=canonical)


FOUND = "math_foundations"
HS3 = "math_hs_3"
HS4 = "math_hs_4"
HS5 = "math_hs_5"


COURSES: list[Course] = []


CLAIMS = [
    # ═══ Set theory (math_foundations) ═══
    C("def_set", "definition", FOUND, "תורת הקבוצות",
      r"**קבוצה:** אוסף בלתי-מסודר של איברים שונים. מסמנים $A = \{a, b, c\}$. שייכות: $a \in A$, אי-שייכות: $d \notin A$."),
    C("def_subset", "definition", FOUND, "תורת הקבוצות",
      r"**תת-קבוצה:** $A \subseteq B$ אם כל איבר של $A$ הוא איבר של $B$. שוויון קבוצות: $A = B$ אם ורק אם $A \subseteq B$ ו-$B \subseteq A$."),
    C("def_empty_set", "definition", FOUND, "תורת הקבוצות",
      r"**הקבוצה הריקה:** $\emptyset$ — הקבוצה ללא איברים. $\emptyset$ תת-קבוצה של כל קבוצה."),
    C("def_set_union", "definition", FOUND, "תורת הקבוצות",
      r"**איחוד:** $A \cup B := \{x : x \in A \text{ או } x \in B\}$."),
    C("def_set_intersection", "definition", FOUND, "תורת הקבוצות",
      r"**חיתוך:** $A \cap B := \{x : x \in A \text{ ו-} x \in B\}$."),
    C("def_set_difference", "definition", FOUND, "תורת הקבוצות",
      r"**הפרש קבוצות:** $A \setminus B := \{x : x \in A \text{ ו-} x \notin B\}$."),
    C("def_set_complement", "definition", FOUND, "תורת הקבוצות",
      r"**משלים:** עבור קבוצה אוניברסלית $U$, $A^c := U \setminus A$."),
    C("def_power_set", "definition", FOUND, "תורת הקבוצות",
      r"**קבוצת חזקה:** $\mathcal{P}(A) := \{S : S \subseteq A\}$ — קבוצת כל תתי-הקבוצות של $A$. אם $|A| = n$ אז $|\mathcal{P}(A)| = 2^n$."),
    C("def_cartesian_product", "definition", FOUND, "תורת הקבוצות",
      r"**מכפלה קרטזית:** $A \times B := \{(a, b) : a \in A, b \in B\}$ — קבוצת זוגות סדורים."),
    C("def_set_cardinality", "definition", FOUND, "תורת הקבוצות",
      r"**עוצמה (קרדינליות):** $|A|$ — מספר האיברים בקבוצה (עבור קבוצות סופיות). $|\emptyset| = 0$."),
    C("thm_demorgan_sets_union", "theorem", FOUND, "תורת הקבוצות",
      r"**דה-מורגן (איחוד):** $(A \cup B)^c = A^c \cap B^c$."),
    C("thm_demorgan_sets_intersection", "theorem", FOUND, "תורת הקבוצות",
      r"**דה-מורגן (חיתוך):** $(A \cap B)^c = A^c \cup B^c$."),

    # ═══ Matrices & linear algebra basics (math_hs_5) ═══
    C("def_matrix", "definition", HS5, "אלגברה לינארית",
      r"**מטריצה:** מערך מלבני של מספרים בגודל $m \times n$ ($m$ שורות, $n$ עמודות). איבר במקום $(i, j)$ מסומן $a_{ij}$."),
    C("def_matrix_addition", "definition", HS5, "אלגברה לינארית",
      r"**חיבור מטריצות:** עבור $A, B$ בגודל $m \times n$: $(A + B)_{ij} := a_{ij} + b_{ij}$ — איבר-איבר."),
    C("def_matrix_scalar_multiplication", "definition", HS5, "אלגברה לינארית",
      r"**כפל בסקלר:** $(c A)_{ij} := c \cdot a_{ij}$."),
    C("def_matrix_multiplication", "definition", HS5, "אלגברה לינארית",
      r"**כפל מטריצות:** עבור $A$ בגודל $m \times k$ ו-$B$ בגודל $k \times n$: $(AB)_{ij} := \sum_{r=1}^{k} a_{ir} b_{rj}$ — מכפלה סקלרית של שורה $i$ של $A$ עם עמודה $j$ של $B$."),
    C("def_identity_matrix", "definition", HS5, "אלגברה לינארית",
      r"**מטריצת היחידה:** $I_n$ — מטריצה ריבועית $n \times n$ עם $1$ באלכסון ו-$0$ בשאר. מקיימת $A \cdot I = I \cdot A = A$."),
    C("thm_matrix_multiplication_associative", "theorem", HS5, "אלגברה לינארית",
      r"**אסוציאטיביות כפל מטריצות:** $(AB)C = A(BC)$."),
    C("def_matrix_transpose", "definition", HS5, "אלגברה לינארית",
      r"**מטריצה משוחלפת:** $A^T$ — $(A^T)_{ij} := a_{ji}$. שורות הופכות לעמודות."),
    C("def_determinant_2x2", "definition", HS5, "אלגברה לינארית",
      r"**דטרמיננטה $2 \times 2$:** $\det\begin{pmatrix} a & b \\ c & d \end{pmatrix} := ad - bc$."),
    C("def_determinant_3x3", "definition", HS5, "אלגברה לינארית",
      r"**דטרמיננטה $3 \times 3$:** פיתוח שורה ראשונה (כלל סרוס): $\det = a(ei - fh) - b(di - fg) + c(dh - eg)$ עבור מטריצה $\begin{pmatrix} a & b & c \\ d & e & f \\ g & h & i \end{pmatrix}$."),
    C("thm_determinant_product", "theorem", HS5, "אלגברה לינארית",
      r"**דטרמיננטה של מכפלה:** $\det(AB) = \det(A) \cdot \det(B)$."),
    C("def_invertible_matrix", "definition", HS5, "אלגברה לינארית",
      r"**מטריצה הפיכה:** מטריצה ריבועית $A$ הפיכה אם קיימת $A^{-1}$ עם $A A^{-1} = A^{-1} A = I$. קיימת אם ורק אם $\det(A) \neq 0$."),
    C("thm_inverse_via_determinant_2x2", "theorem", HS5, "אלגברה לינארית",
      r"**הפכי מטריצה $2 \times 2$:** $A^{-1} = \frac{1}{\det A} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix}$ עבור $A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$."),
    C("def_linear_system", "definition", HS5, "אלגברה לינארית",
      r"**מערכת משוואות לינאריות:** $A \vec{x} = \vec{b}$ עבור מטריצת מקדמים $A$, וקטור נעלמים $\vec{x}$, וקטור קבועים $\vec{b}$."),
    C("thm_cramer_rule", "theorem", HS5, "אלגברה לינארית",
      r"**כלל קרמר:** עבור מערכת $A \vec{x} = \vec{b}$ ריבועית עם $\det(A) \neq 0$: $x_i = \frac{\det(A_i)}{\det(A)}$, כאשר $A_i$ היא $A$ בה העמודה ה-$i$ הוחלפה ב-$\vec{b}$."),
    C("def_eigenvalue_eigenvector", "definition", HS5, "אלגברה לינארית",
      r"**ערך עצמי ווקטור עצמי:** $\lambda$ ערך עצמי של $A$ אם קיים וקטור $\vec{v} \neq 0$ עם $A \vec{v} = \lambda \vec{v}$. $\vec{v}$ נקרא וקטור עצמי המתאים ל-$\lambda$."),

    # ═══ Triangle centers (math_hs_5) ═══
    C("def_centroid", "definition", HS5, "מרכזי משולש",
      r"**מרכז הכובד (קודקודי):** נקודת המפגש של שלושת התיכונים של משולש (קטעים מקודקוד לאמצע הצלע הנגדית)."),
    C("def_circumcenter", "definition", HS5, "מרכזי משולש",
      r"**מרכז המעגל החוסם:** נקודת המפגש של אנכי האמצע (מאונכים) של שלוש צלעות המשולש. מרכז המעגל העובר דרך שלושת הקודקודים."),
    C("def_incenter", "definition", HS5, "מרכזי משולש",
      r"**מרכז המעגל החסום:** נקודת המפגש של שלושת חוצי הזוויות של המשולש. מרכז המעגל המשיק לשלוש הצלעות מבפנים."),
    C("def_orthocenter", "definition", HS5, "מרכזי משולש",
      r"**אורתוצנטר:** נקודת המפגש של שלושת הגבהים של המשולש (מאונכים מקודקוד לצלע הנגדית)."),
    C("thm_medians_meet_at_centroid", "theorem", HS5, "מרכזי משולש",
      r"**מפגש תיכונים:** שלושת התיכונים במשולש נחתכים בנקודה אחת — מרכז הכובד — שמחלקת כל תיכון ביחס $2:1$ מהקודקוד."),
    C("thm_perpendicular_bisectors_concur", "theorem", HS5, "מרכזי משולש",
      r"**מפגש אנכי אמצע:** שלושת אנכי האמצע במשולש נחתכים בנקודה אחת המרוחקת באותה מידה משלושת הקודקודים — מרכז המעגל החוסם."),
    C("thm_angle_bisectors_concur", "theorem", HS5, "מרכזי משולש",
      r"**מפגש חוצי זוויות:** שלושת חוצי הזוויות הפנימיות במשולש נחתכים בנקודה אחת — מרכז המעגל החסום."),
    C("thm_euler_line", "theorem", HS5, "מרכזי משולש",
      r"**ישר אוילר:** בכל משולש שאינו שווה-צלעות, האורתוצנטר $H$, מרכז הכובד $G$, ומרכז המעגל החוסם $O$ מצויים על ישר אחד (ישר אוילר), עם $HG = 2 \cdot GO$."),

    # ═══ Function transformations (math_hs_3) ═══
    C("def_horizontal_shift", "definition", HS3, "טרנספורמציות פונקציה",
      r"**הזזה אופקית:** הגרף של $g(x) = f(x - h)$ הוא הגרף של $f$ מוזז $h$ יחידות ימינה (אם $h > 0$) או שמאלה (אם $h < 0$)."),
    C("def_vertical_shift", "definition", HS3, "טרנספורמציות פונקציה",
      r"**הזזה אנכית:** הגרף של $g(x) = f(x) + k$ הוא הגרף של $f$ מוזז $k$ יחידות מעלה (אם $k > 0$) או מטה (אם $k < 0$)."),
    C("def_horizontal_scaling", "definition", HS3, "טרנספורמציות פונקציה",
      r"**מתיחה/כיווץ אופקי:** $g(x) = f(c x)$ — אם $c > 1$ כיווץ אופקי בפקטור $c$; אם $0 < c < 1$ מתיחה."),
    C("def_vertical_scaling", "definition", HS3, "טרנספורמציות פונקציה",
      r"**מתיחה/כיווץ אנכי:** $g(x) = c \cdot f(x)$ — אם $|c| > 1$ מתיחה אנכית, אם $|c| < 1$ כיווץ."),
    C("def_reflection_x_axis", "definition", HS3, "טרנספורמציות פונקציה",
      r"**שיקוף בציר $x$:** $g(x) = -f(x)$."),
    C("def_reflection_y_axis", "definition", HS3, "טרנספורמציות פונקציה",
      r"**שיקוף בציר $y$:** $g(x) = f(-x)$."),

    # ═══ Statistics extended (math_hs_5) ═══
    C("def_population", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**אוכלוסייה:** הקבוצה השלמה של כל הפריטים שעליהם רוצים להסיק. מסומנת בפרמטרים יווניים ($\mu, \sigma$)."),
    C("def_sample", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**מדגם:** תת-קבוצה של פריטים שנבחרו מהאוכלוסייה לצורך הסקה. מסומן בסטטיסטיקה לטינית ($\bar{x}, s$)."),
    C("def_random_variable", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**משתנה מקרי:** פונקציה $X: \Omega \to \mathbb{R}$ שמקצה ערך מספרי לכל תוצאה במרחב מדגם."),
    C("def_discrete_random_variable", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**משתנה מקרי בדיד:** משתנה מקרי שטווחו סופי או בן-מנייה. מאופיין ע״י פונקציית הסתברות $P(X = x_i) = p_i$."),
    C("def_continuous_random_variable", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**משתנה מקרי רציף:** משתנה מקרי שטווחו אינסופי לא-בן-מנייה. מאופיין ע״י פונקציית צפיפות $f(x)$ עם $P(a \leq X \leq b) = \int_a^b f$."),
    C("def_expected_value", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**תוחלת:** עבור משתנה מקרי בדיד $X$: $E[X] := \sum_i x_i \cdot P(X = x_i)$. עבור רציף: $E[X] := \int_{-\infty}^{\infty} x \cdot f(x) \, dx$."),
    C("thm_expected_value_linearity", "theorem", HS5, "סטטיסטיקה מתקדמת",
      r"**לינאריות התוחלת:** $E[a X + b Y] = a E[X] + b E[Y]$ לכל קבועים $a, b$ ומשתנים $X, Y$ (גם בלי תלות)."),
    C("def_normal_distribution", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**התפלגות נורמלית:** $X \sim N(\mu, \sigma^2)$ עם צפיפות $f(x) = \frac{1}{\sigma \sqrt{2\pi}} e^{-(x - \mu)^2 / (2\sigma^2)}$."),
    C("def_standard_score_z", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**ציון תקני $Z$:** $Z := \frac{X - \mu}{\sigma}$ — תיקון לערך לפי הממוצע וסטיית התקן. $Z \sim N(0, 1)$ אם $X \sim N(\mu, \sigma^2)$."),
    C("def_binomial_distribution", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**התפלגות בינומית:** $X \sim \text{Bin}(n, p)$ — מספר ההצלחות ב-$n$ ניסויים בלתי-תלויים, הסתברות הצלחה $p$ בכל אחד. $P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}$."),

    # ═══ Probability extended (math_hs_5) ═══
    C("def_variance_rv", "definition", HS5, "הסתברות מתקדמת",
      r"**שונות משתנה מקרי:** $\text{Var}(X) := E[(X - E[X])^2] = E[X^2] - (E[X])^2$."),
    C("thm_variance_sum_independent", "theorem", HS5, "הסתברות מתקדמת",
      r"**שונות סכום בלתי-תלויים:** אם $X, Y$ בלתי-תלויים, $\text{Var}(X + Y) = \text{Var}(X) + \text{Var}(Y)$."),
    C("def_geometric_distribution", "definition", HS5, "הסתברות מתקדמת",
      r"**התפלגות גאומטרית:** $X \sim \text{Geo}(p)$ — מספר הניסויים עד ההצלחה הראשונה. $P(X = k) = (1-p)^{k-1} p$ עבור $k = 1, 2, \ldots$"),
    C("def_uniform_distribution_continuous", "definition", HS5, "הסתברות מתקדמת",
      r"**התפלגות אחידה רציפה:** $X \sim U(a, b)$ עם צפיפות $f(x) = \frac{1}{b - a}$ ב-$[a, b]$, אפס מחוץ."),
    C("thm_law_of_total_probability", "theorem", HS5, "הסתברות מתקדמת",
      r"**משפט ההסתברות השלמה:** אם $\{B_1, \ldots, B_n\}$ חלוקה של $\Omega$: $P(A) = \sum_i P(A \mid B_i) \cdot P(B_i)$."),
    C("def_independent_random_variables", "definition", HS5, "הסתברות מתקדמת",
      r"**משתנים מקריים בלתי-תלויים:** $X, Y$ בלתי-תלויים אם לכל $a, b$: $P(X \leq a \text{ ו-} Y \leq b) = P(X \leq a) \cdot P(Y \leq b)$."),
    C("thm_expected_value_of_function", "theorem", HS5, "הסתברות מתקדמת",
      r"**תוחלת פונקציה של משתנה:** $E[g(X)] = \sum_i g(x_i) P(X = x_i)$ (בדיד), $E[g(X)] = \int g(x) f(x) dx$ (רציף)."),
    C("def_covariance", "definition", HS5, "הסתברות מתקדמת",
      r"**שונות משותפת (קווריאנס):** $\text{Cov}(X, Y) := E[(X - E[X])(Y - E[Y])] = E[XY] - E[X] E[Y]$."),
    C("def_correlation_random_variables", "definition", HS5, "הסתברות מתקדמת",
      r"**מתאם משתנים מקריים:** $\rho(X, Y) := \frac{\text{Cov}(X, Y)}{\sigma_X \sigma_Y} \in [-1, 1]$."),
    C("thm_binomial_mean_variance", "theorem", HS5, "הסתברות מתקדמת",
      r"**ממוצע ושונות בינומית:** עבור $X \sim \text{Bin}(n, p)$: $E[X] = n p$, $\text{Var}(X) = n p (1 - p)$."),

    # ═══ Calculus extended (math_hs_5) ═══
    C("def_taylor_series", "definition", HS5, "טור טיילור",
      r"**טור טיילור סביב $a$:** $f(x) = \sum_{n=0}^{\infty} \frac{f^{(n)}(a)}{n!} (x - a)^n$ — פיתוח פולינומיאלי-אינסופי של $f$ סביב $a$."),
    C("def_maclaurin_series", "definition", HS5, "טור טיילור",
      r"**טור מקלורין:** טור טיילור סביב $a = 0$: $f(x) = \sum_{n=0}^{\infty} \frac{f^{(n)}(0)}{n!} x^n$."),
    C("thm_maclaurin_exp", "theorem", HS5, "טור טיילור",
      r"**טור מקלורין של $e^x$:** $e^x = \sum_{n=0}^{\infty} \frac{x^n}{n!} = 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \cdots$"),
    C("thm_maclaurin_sin", "theorem", HS5, "טור טיילור",
      r"**טור מקלורין של $\sin x$:** $\sin x = \sum_{n=0}^{\infty} \frac{(-1)^n x^{2n+1}}{(2n+1)!} = x - \frac{x^3}{3!} + \frac{x^5}{5!} - \cdots$"),
    C("thm_maclaurin_cos", "theorem", HS5, "טור טיילור",
      r"**טור מקלורין של $\cos x$:** $\cos x = \sum_{n=0}^{\infty} \frac{(-1)^n x^{2n}}{(2n)!} = 1 - \frac{x^2}{2!} + \frac{x^4}{4!} - \cdots$"),
    C("def_partial_derivative", "definition", HS5, "חדו״א בכמה משתנים",
      r"**נגזרת חלקית:** עבור $f(x, y)$, $\frac{\partial f}{\partial x} := \lim_{h \to 0} \frac{f(x + h, y) - f(x, y)}{h}$ — גוזרים לפי $x$ תוך התייחסות ל-$y$ כקבוע."),
    C("def_gradient", "definition", HS5, "חדו״א בכמה משתנים",
      r"**גרדיאנט:** $\nabla f := \left(\frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}, \ldots\right)$ — וקטור הנגזרות החלקיות. מצביע על כיוון העלייה התלולה ביותר."),
    C("def_double_integral", "definition", HS5, "חדו״א בכמה משתנים",
      r"**אינטגרל כפול:** $\iint_R f(x, y) \, dA$ — אינטגרציה של $f$ על תחום $R$ במישור. מייצג נפח תחת המשטח $z = f(x, y)$."),
    C("def_critical_point_multivariable", "definition", HS5, "חדו״א בכמה משתנים",
      r"**נקודה קריטית רב-משתנית:** $(x_0, y_0)$ קריטית של $f$ אם $\nabla f(x_0, y_0) = \vec{0}$ — כל הנגזרות החלקיות מתאפסות."),
    C("def_directional_derivative", "definition", HS5, "חדו״א בכמה משתנים",
      r"**נגזרת כיוונית:** עבור פונקציה $f$ וכיוון יחידה $\hat{u}$, $D_{\hat{u}} f = \nabla f \cdot \hat{u}$ — קצב השינוי של $f$ בכיוון $\hat{u}$."),

    # ═══ Number theory extended (math_hs_5) ═══
    C("def_euler_totient", "definition", HS5, "תורת מספרים מתקדמת",
      r"**פונקציית אוילר $\varphi(n)$:** מספר השלמים $k$ ב-$\{1, \ldots, n\}$ עם $\gcd(k, n) = 1$."),
    C("thm_euler_totient_prime", "theorem", HS5, "תורת מספרים מתקדמת",
      r"**$\varphi$ של ראשוני:** עבור ראשוני $p$, $\varphi(p) = p - 1$."),
    C("thm_euler_theorem", "theorem", HS5, "תורת מספרים מתקדמת",
      r"**משפט אוילר:** עבור $\gcd(a, n) = 1$: $a^{\varphi(n)} \equiv 1 \pmod n$. הכללה של פרמה הקטן."),
    C("thm_chinese_remainder_theorem", "theorem", HS5, "תורת מספרים מתקדמת",
      r"**משפט השאריות הסיני (CRT):** אם $n_1, n_2, \ldots, n_k$ זרים בזוגות, אז למערכת $x \equiv a_i \pmod{n_i}$ לכל $i$ יש פתרון יחיד מודולו $n_1 n_2 \cdots n_k$."),
    C("thm_wilson_theorem", "theorem", HS5, "תורת מספרים מתקדמת",
      r"**משפט וילסון:** $n$ ראשוני אם ורק אם $(n - 1)! \equiv -1 \pmod n$."),
    C("def_quadratic_residue", "definition", HS5, "תורת מספרים מתקדמת",
      r"**שארית ריבועית:** $a$ נקראת **שארית ריבועית** מודולו $n$ אם קיים $x$ עם $x^2 \equiv a \pmod n$."),
    C("def_modular_exponentiation", "definition", HS5, "תורת מספרים מתקדמת",
      r"**חישוב חזקה מודולרית:** $a^k \mod n$ נחשב ביעילות ע״י חזקה חוזרת (Repeated Squaring): $O(\log k)$ פעולות."),
    C("thm_squares_mod_p", "theorem", HS5, "תורת מספרים מתקדמת",
      r"**ריבועים מודולו ראשוני אי-זוגי:** עבור ראשוני $p > 2$, בדיוק $\frac{p - 1}{2}$ מתוך $\{1, \ldots, p-1\}$ הם שאריות ריבועיות."),

    # ═══ Combinatorics extended (math_hs_5) ═══
    C("thm_inclusion_exclusion_two_sets", "theorem", HS5, "קומבינטוריקה מתקדמת",
      r"**הכלה-הפרדה (שתי קבוצות):** $|A \cup B| = |A| + |B| - |A \cap B|$."),
    C("thm_inclusion_exclusion_three_sets", "theorem", HS5, "קומבינטוריקה מתקדמת",
      r"**הכלה-הפרדה (שלוש קבוצות):** $|A \cup B \cup C| = |A| + |B| + |C| - |A \cap B| - |A \cap C| - |B \cap C| + |A \cap B \cap C|$."),
    C("def_permutation_with_repetition", "definition", HS5, "קומבינטוריקה מתקדמת",
      r"**תמורות עם חזרות:** מספר הסידורים של $n$ פריטים שמתוכם $n_1, n_2, \ldots, n_k$ חוזרים: $\frac{n!}{n_1! \cdot n_2! \cdots n_k!}$."),
    C("thm_multinomial_theorem", "theorem", HS5, "קומבינטוריקה מתקדמת",
      r"**משפט הרב-נומי:** $(x_1 + x_2 + \cdots + x_m)^n = \sum \frac{n!}{n_1! n_2! \cdots n_m!} x_1^{n_1} x_2^{n_2} \cdots x_m^{n_m}$, סכום על כל פירוקי $n = n_1 + \cdots + n_m$."),
    C("def_derangement", "definition", HS5, "קומבינטוריקה מתקדמת",
      r"**ערבול (Derangement):** פרמוטציה של $\{1, \ldots, n\}$ שאף איבר לא נשאר במקומו המקורי. מסומן $D_n$ או $!n$."),
    C("thm_derangement_formula", "theorem", HS5, "קומבינטוריקה מתקדמת",
      r"**נוסחת הערבולים:** $D_n = n! \sum_{k=0}^n \frac{(-1)^k}{k!}$, ובקירוב $D_n \approx \frac{n!}{e}$."),
    C("def_hypergeometric_distribution", "definition", HS5, "קומבינטוריקה מתקדמת",
      r"**התפלגות היפר-גאומטרית:** דגימה ללא החזרה. $P(X = k) = \frac{\binom{K}{k}\binom{N-K}{n-k}}{\binom{N}{n}}$."),
    C("thm_stars_and_bars", "theorem", HS5, "קומבינטוריקה מתקדמת",
      r"**כוכבים וקווים:** מספר הפתרונות במספרים שלמים אי-שליליים של $x_1 + x_2 + \cdots + x_k = n$ הוא $\binom{n + k - 1}{k - 1}$."),

    # ═══ Applied math (math_hs_4 / math_hs_5) ═══
    C("def_simple_interest", "definition", HS4, "מתמטיקה פיננסית",
      r"**ריבית פשוטה:** סכום בריבית פשוטה: $A = P(1 + rt)$, כאשר $P$ קרן, $r$ ריבית שנתית, $t$ זמן בשנים."),
    C("def_compound_interest", "definition", HS4, "מתמטיקה פיננסית",
      r"**ריבית דריבית:** ריבית שמחושבת על הקרן ועל הריבית שהצטברה. $n$ פעמים בשנה: $A = P\left(1 + \frac{r}{n}\right)^{nt}$."),
    C("thm_compound_interest_formula", "theorem", HS4, "מתמטיקה פיננסית",
      r"**ניסוח כללי לריבית דריבית:** $A = P(1 + r)^t$ עבור חיוב שנתי. אם מחושב $n$ פעמים בשנה: $A = P(1 + r/n)^{nt}$."),
    C("def_continuous_compounding", "definition", HS4, "מתמטיקה פיננסית",
      r"**ריבית רציפה:** הגבול של ריבית דריבית כש-$n \to \infty$: $A = P \cdot e^{rt}$."),
    C("thm_present_value", "theorem", HS4, "מתמטיקה פיננסית",
      r"**ערך נוכחי:** סכום $A$ עתידי בעוד $t$ שנים, בריבית $r$, שווה היום ל-$P = A \cdot (1 + r)^{-t}$ (או $A e^{-rt}$ לריבית רציפה)."),
    C("def_doubling_time", "definition", HS4, "מתמטיקה פיננסית",
      r"**זמן הכפלה:** הזמן הנדרש לסכום בריבית להכפיל את עצמו: $T_2 = \frac{\ln 2}{\ln(1 + r)} \approx \frac{0.693}{r}$ (לריבית רציפה: $T_2 = \frac{\ln 2}{r}$)."),
    C("def_motion_constant_velocity", "definition", HS5, "פיזיקה",
      r"**תנועה במהירות קבועה:** מיקום לאחר זמן $t$: $x(t) = x_0 + v \cdot t$. הנגזרת היא המהירות הקבועה $v$."),
    C("def_motion_constant_acceleration", "definition", HS5, "פיזיקה",
      r"**תנועה בתאוצה קבועה:** $v(t) = v_0 + a t$, ו-$x(t) = x_0 + v_0 t + \tfrac{1}{2} a t^2$."),
    C("thm_kinematic_no_time", "theorem", HS5, "פיזיקה",
      r"**משוואת קינמטיקה ללא זמן:** $v^2 = v_0^2 + 2 a (x - x_0)$ — מקשר מהירות, תאוצה והעתק בלי לכלול את הזמן במפורש."),
    C("def_exponential_decay_physics", "definition", HS5, "פיזיקה",
      r"**דעיכה מעריכית:** $N(t) = N_0 \cdot e^{-\lambda t}$ — מודל לכמות שמתפרקת בקצב פרופורציוני לעצמה (חומר רדיואקטיבי, רעלים בגוף, וכו')."),
    C("thm_carbon_dating", "theorem", HS5, "פיזיקה",
      r"**תיארוך פחמן-14:** עם זמן מחצית חיים $T_{1/2} \approx 5730$ שנים, הגיל מחושב מ-$N/N_0$: $t = -\frac{T_{1/2}}{\ln 2} \cdot \ln(N/N_0)$."),
    C("def_logistic_growth", "definition", HS5, "פיזיקה",
      r"**גדילה לוגיסטית:** $\frac{dP}{dt} = r P (1 - P/K)$ — גדילה מואצת בהתחלה ומאטה כשמתקרבים לקיבולת $K$."),
    C("thm_logistic_solution", "theorem", HS5, "פיזיקה",
      r"**פתרון משוואת לוגיסטית:** $P(t) = \frac{K}{1 + ((K - P_0)/P_0) e^{-rt}}$."),
]


PROOFS = [
    # ── Set theory ──
    P("prf_demorgan_sets_union", "thm_demorgan_sets_union",
      ["def_set_union", "def_set_intersection", "def_set_complement"],
      "$x \\in (A \\cup B)^c$ אם ורק אם $x \\notin A \\cup B$, אם ורק אם $x \\notin A$ וגם $x \\notin B$, אם ורק אם $x \\in A^c \\cap B^c$. $\\blacksquare$"),
    P("prf_demorgan_sets_intersection", "thm_demorgan_sets_intersection",
      ["def_set_union", "def_set_intersection", "def_set_complement"],
      "$x \\in (A \\cap B)^c$ אם ורק אם לא ($x \\in A$ וגם $x \\in B$), אם ורק אם $x \\notin A$ או $x \\notin B$, אם ורק אם $x \\in A^c \\cup B^c$. $\\blacksquare$"),

    # ── Matrices ──
    P("prf_matrix_multiplication_associative", "thm_matrix_multiplication_associative",
      ["def_matrix_multiplication", "ax_addition_associativity",
       "ax_multiplication_associativity"],
      "$((AB)C)_{ij} = \\sum_l (AB)_{il} c_{lj} = \\sum_l \\left(\\sum_k a_{ik} b_{kl}\\right) c_{lj} = \\sum_{k, l} a_{ik} b_{kl} c_{lj}$.\n\n$(A(BC))_{ij} = \\sum_k a_{ik} (BC)_{kj} = \\sum_k a_{ik} \\sum_l b_{kl} c_{lj} = \\sum_{k, l} a_{ik} b_{kl} c_{lj}$.\n\nשני האגפים שווים (החלפת סדר סכימה). $\\blacksquare$"),
    P("prf_determinant_product", "thm_determinant_product",
      ["def_determinant_2x2", "def_matrix_multiplication"],
      "**הוכחה ל-$2 \\times 2$ (ישירה):** אם $A = \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}$, $B = \\begin{pmatrix} e & f \\\\ g & h \\end{pmatrix}$, אז $AB = \\begin{pmatrix} ae+bg & af+bh \\\\ ce+dg & cf+dh \\end{pmatrix}$.\n\n$\\det(AB) = (ae+bg)(cf+dh) - (af+bh)(ce+dg) = (ad - bc)(eh - fg) = \\det(A)\\det(B)$ (פתיחה וצמצום). הכללה ל-$n \\times n$ דורשת רב-לינאריות הדטרמיננטה. $\\blacksquare$"),
    P("prf_inverse_via_determinant_2x2", "thm_inverse_via_determinant_2x2",
      ["def_determinant_2x2", "def_matrix_multiplication", "def_identity_matrix"],
      "כפל ישיר: $A \\cdot \\frac{1}{\\det A}\\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix} = \\frac{1}{ad - bc}\\begin{pmatrix} ad - bc & 0 \\\\ 0 & ad - bc \\end{pmatrix} = I$. $\\blacksquare$"),
    P("prf_cramer_rule", "thm_cramer_rule",
      ["def_determinant_2x2", "thm_determinant_product",
       "def_invertible_matrix"],
      "$A \\vec{x} = \\vec{b} \\Rightarrow \\vec{x} = A^{-1} \\vec{b}$. הרכיב ה-$i$ של $A^{-1} \\vec{b}$ הוא $\\frac{1}{\\det A}$ כפול הקופקטור של עמודה $i$, שווה ערך ל-$\\frac{\\det A_i}{\\det A}$ (לפי פיתוח לפי עמודה $i$). $\\blacksquare$"),

    # ── Triangle centers ──
    P("prf_medians_meet_at_centroid", "thm_medians_meet_at_centroid",
      ["def_centroid", "def_triangle", "thm_aa_similarity"],
      "ניקח שני תיכונים $AM, BN$ במשולש $\\triangle ABC$, נסמן את נקודת חיתוכם $G$.\n\n**גישה וקטורית:** מציבים את הקודקודים כווקטורים $\\vec{A}, \\vec{B}, \\vec{C}$. אמצע $BC$ הוא $\\vec{M} = \\frac{\\vec{B} + \\vec{C}}{2}$. נקודה על תיכון $AM$: $\\vec{A} + t(\\vec{M} - \\vec{A})$. חיתוך עם תיכון $BN$ נותן $\\vec{G} = \\frac{\\vec{A} + \\vec{B} + \\vec{C}}{3}$.\n\nלפי הסימטריה, גם התיכון השלישי עובר דרך $G$. יחס החלוקה $AG:GM = 2:1$ מקבלים מ-$t = \\tfrac{2}{3}$. $\\blacksquare$"),
    P("prf_perpendicular_bisectors_concur", "thm_perpendicular_bisectors_concur",
      ["def_circumcenter", "def_triangle", "thm_pythagoras"],
      "כל נקודה על אנך אמצע של $AB$ מקיימת $|PA| = |PB|$ (מתאפיין של אנך אמצע).\n\nניקח את נקודת החיתוך $O$ של אנכי האמצע של $AB$ ושל $AC$. אז $|OA| = |OB|$ ו-$|OA| = |OC|$, ולכן $|OB| = |OC|$ — $O$ נמצא גם על אנך האמצע של $BC$.\n\nשלושה אנכי האמצע נחתכים ב-$O$, שהוא במרחק שווה משלושה הקודקודים — מרכז המעגל החוסם. $\\blacksquare$"),
    P("prf_angle_bisectors_concur", "thm_angle_bisectors_concur",
      ["def_incenter", "def_triangle"],
      "נקודה על חוצה זווית של $\\angle A$ מקיימת מרחקים שווים משתי הצלעות $AB$ ו-$AC$.\n\nניקח חיתוך של חוצי זוויות של $A$ ו-$B$, נסמן $I$. אז $d(I, AB) = d(I, AC) = d(I, BC)$, ולכן $I$ נמצא גם על חוצה זווית $C$.\n\nשלושה חוצי הזוויות נחתכים ב-$I$, שהוא במרחק שווה משלוש הצלעות — מרכז המעגל החסום. $\\blacksquare$"),
    P("prf_euler_line", "thm_euler_line",
      ["def_centroid", "def_circumcenter", "def_orthocenter",
       "thm_medians_meet_at_centroid", "def_vector_2d"],
      "**הוכחה וקטורית.** סדר $O$ בראשית. אז $\\vec{G} = \\frac{1}{3}(\\vec{A} + \\vec{B} + \\vec{C})$ ולפי תכונה ידועה $\\vec{H} = \\vec{A} + \\vec{B} + \\vec{C}$.\n\nלכן $\\vec{H} = 3\\vec{G}$, כלומר $O, G, H$ קולינאריים עם $\\vec{OH} = 3 \\vec{OG}$, ובמיוחד $\\vec{HG} = -2 \\vec{OG}$, $|HG| = 2 |GO|$. $\\blacksquare$"),

    # ── Statistics extended ──
    P("prf_expected_value_linearity", "thm_expected_value_linearity",
      ["def_expected_value", "ax_distributive_law",
       "ax_addition_commutativity"],
      "$E[aX + bY] = \\sum_{x, y} (ax + by) P(X = x, Y = y) = a \\sum_x x \\sum_y P(x, y) + b \\sum_y y \\sum_x P(x, y) = a E[X] + b E[Y]$.\n\n(ההוכחה לרציף זהה עם אינטגרלים.) הזהות לא דורשת אי-תלות בין $X$ ו-$Y$. $\\blacksquare$"),
    P("prf_binomial_mean_variance", "thm_binomial_mean_variance",
      ["def_binomial_distribution", "def_expected_value",
       "thm_expected_value_linearity", "thm_variance_sum_independent",
       "def_variance_rv"],
      "$X = X_1 + X_2 + \\cdots + X_n$ כאשר $X_i \\sim \\text{Bernoulli}(p)$ בלתי-תלויים.\n\n$E[X_i] = p$, $\\text{Var}(X_i) = p(1 - p)$. לפי לינאריות התוחלת: $E[X] = np$. לפי שונות סכום בלתי-תלויים: $\\text{Var}(X) = n p(1-p)$. $\\blacksquare$"),

    # ── Probability extended ──
    P("prf_variance_sum_independent", "thm_variance_sum_independent",
      ["def_variance_rv", "def_expected_value",
       "def_independent_random_variables",
       "thm_expected_value_linearity"],
      "$\\text{Var}(X + Y) = E[(X + Y)^2] - (E[X + Y])^2 = E[X^2 + 2XY + Y^2] - (E[X] + E[Y])^2$\n\n$= E[X^2] + 2E[XY] + E[Y^2] - E[X]^2 - 2E[X]E[Y] - E[Y]^2$.\n\nבהינתן אי-תלות, $E[XY] = E[X]E[Y]$, אז המקדם של 2 מתבטל. נשאר $\\text{Var}(X) + \\text{Var}(Y)$. $\\blacksquare$"),
    P("prf_expected_value_of_function", "thm_expected_value_of_function",
      ["def_expected_value", "def_discrete_random_variable",
       "def_continuous_random_variable"],
      "**מקרה בדיד.** $g(X)$ הוא משתנה מקרי חדש. ערכיו האפשריים: $\\{g(x_i)\\}$ עם הסתברויות $P(X = x_i)$. לפי הגדרת תוחלת: $E[g(X)] = \\sum_i g(x_i) P(X = x_i)$ (במידה שאין שני $x_i$ שונים שמעבירים לאותו ערך — אז יש לאחד הסתברויות, אבל הסכום נשאר אותו דבר).\n\n**מקרה רציף.** באופן דומה אבל עם אינטגרל וצפיפות: $E[g(X)] = \\int g(x) f(x) dx$. $\\blacksquare$"),
    P("prf_law_of_total_probability", "thm_law_of_total_probability",
      ["ax_probability_additivity", "def_conditional_probability"],
      "$\\{B_i\\}$ חלוקה של $\\Omega$, אז $\\{A \\cap B_i\\}$ חלוקה של $A$ (זרים בזוגות). לפי אדיטיביות:\n\n$P(A) = \\sum_i P(A \\cap B_i) = \\sum_i P(A \\mid B_i) P(B_i)$ (לפי הגדרת הסתברות מותנית). $\\blacksquare$"),

    # ── Calculus extended ──
    P("prf_maclaurin_exp", "thm_maclaurin_exp",
      ["def_maclaurin_series", "thm_derivative_exp"],
      "$f(x) = e^x$ מקיים $f^{(n)}(x) = e^x$ לכל $n$, ולכן $f^{(n)}(0) = 1$.\n\nהצבה בנוסחת מקלורין: $e^x = \\sum_{n=0}^{\\infty} \\frac{1}{n!} x^n$. (התכנסות בכל $\\mathbb{R}$ מובטחת לפי מבחן המנה.) $\\blacksquare$"),
    P("prf_maclaurin_sin", "thm_maclaurin_sin",
      ["def_maclaurin_series", "thm_derivative_sin",
       "thm_derivative_cos"],
      "$\\sin(0) = 0$, $\\sin'(0) = \\cos(0) = 1$, $\\sin''(0) = -\\sin(0) = 0$, $\\sin'''(0) = -\\cos(0) = -1$. המחזור 4 חוזר.\n\nרק חזקות אי-זוגיות $x^{2k+1}$ נשארות, עם סימנים מתחלפים: $\\sin x = x - \\frac{x^3}{3!} + \\frac{x^5}{5!} - \\cdots = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n+1}}{(2n+1)!}$. $\\blacksquare$"),
    P("prf_maclaurin_cos", "thm_maclaurin_cos",
      ["def_maclaurin_series", "thm_derivative_sin",
       "thm_derivative_cos"],
      "$\\cos(0) = 1$, $\\cos'(0) = -\\sin(0) = 0$, $\\cos''(0) = -\\cos(0) = -1$, $\\cos'''(0) = \\sin(0) = 0$. מחזור 4.\n\nרק חזקות זוגיות נשארות: $\\cos x = 1 - \\frac{x^2}{2!} + \\frac{x^4}{4!} - \\cdots = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n}}{(2n)!}$. $\\blacksquare$"),

    # ── Number theory extended ──
    P("prf_euler_totient_prime", "thm_euler_totient_prime",
      ["def_euler_totient", "def_prime", "def_divisibility"],
      "עבור $p$ ראשוני, כל $k$ ב-$\\{1, 2, \\ldots, p - 1\\}$ זר ל-$p$ (אין מחלקים משותפים מלבד $1$ — כי $p$ ראשוני).\n\nלכן $\\varphi(p) = p - 1$. $\\blacksquare$"),
    P("prf_euler_theorem", "thm_euler_theorem",
      ["def_euler_totient", "def_congruence_mod",
       "thm_modular_arithmetic_properties"],
      "**הכללה של פרמה הקטן.** סדר השלמים הזרים ל-$n$ במודולו $n$: $\\{r_1, \\ldots, r_{\\varphi(n)}\\}$. כפל ב-$a$ (זר ל-$n$) נותן פרמוטציה של אותה קבוצה.\n\nלכן $\\prod a r_i \\equiv \\prod r_i \\pmod n$, כלומר $a^{\\varphi(n)} \\prod r_i \\equiv \\prod r_i$. צמצום (כי המכפלה זרה ל-$n$): $a^{\\varphi(n)} \\equiv 1 \\pmod n$. $\\blacksquare$"),
    P("prf_chinese_remainder_theorem", "thm_chinese_remainder_theorem",
      ["def_congruence_mod", "thm_bezout_identity"],
      "**הוכחה קונסטרוקטיבית.** עבור $k = 2$: $n_1, n_2$ זרים, אז זהות בזו נותנת $1 = n_1 u + n_2 v$. הפתרון: $x = a_2 \\cdot n_1 u + a_1 \\cdot n_2 v$.\n\nאינדוקציה על $k$. יחידות מודולו $N = \\prod n_i$ ממשפט פרמטר וזרות מודולוסים.  $\\blacksquare$"),
    P("prf_wilson_theorem", "thm_wilson_theorem",
      ["def_prime", "def_congruence_mod", "thm_fermat_little"],
      "**$\\Rightarrow$:** עבור $p$ ראשוני, כל $a \\in \\{1, \\ldots, p-1\\}$ הוא הפיך מודולו $p$. רוב הזוגות $(a, a^{-1})$ שונים והם מתבטלים במכפלה. הם זהים רק כש-$a = \\pm 1$. אז $(p-1)! \\equiv 1 \\cdot (-1) \\equiv -1 \\pmod p$.\n\n**$\\Leftarrow$:** אם $n$ פריק, $n = ab$ עם $1 < a, b < n$, אז $a \\mid (n-1)!$ ולכן לא ייתכן $(n-1)! \\equiv -1 \\pmod n$. $\\blacksquare$"),
    P("prf_squares_mod_p", "thm_squares_mod_p",
      ["def_quadratic_residue", "def_prime", "thm_no_zero_divisors"],
      "פונקציית $x \\mapsto x^2 \\pmod p$ מ-$\\{1, \\ldots, p-1\\}$ אל עצמה. כי $x^2 \\equiv y^2 \\Leftrightarrow (x-y)(x+y) \\equiv 0$ ולכן $x \\equiv \\pm y$ (לפי אי קיום מחלקי אפס בשדה $\\mathbb{Z}_p$).\n\nכל ערך בתמונה מתקבל בדיוק 2 פעמים, ולכן יש $\\frac{p-1}{2}$ ערכים שונים בתמונה — אלו הם השאריות הריבועיות. $\\blacksquare$"),

    # ── Combinatorics extended ──
    P("prf_inclusion_exclusion_two_sets", "thm_inclusion_exclusion_two_sets",
      ["def_set_union", "def_set_intersection", "def_set_cardinality"],
      "כל איבר ב-$A \\cup B$ נספר ב-$|A| + |B|$ פעם אחת אם הוא בקבוצה אחת בלבד, ופעמיים אם הוא בשתיהן. החיסור $|A \\cap B|$ מתקן את הספירה הכפולה. $\\blacksquare$"),
    P("prf_inclusion_exclusion_three_sets", "thm_inclusion_exclusion_three_sets",
      ["thm_inclusion_exclusion_two_sets", "def_set_union",
       "def_set_intersection"],
      "$|A \\cup B \\cup C| = |(A \\cup B) \\cup C| = |A \\cup B| + |C| - |(A \\cup B) \\cap C|$.\n\nפיתוח: $(A \\cup B) \\cap C = (A \\cap C) \\cup (B \\cap C)$. הפעלה שוב של הכלה-הפרדה: $|(A \\cup B) \\cap C| = |A \\cap C| + |B \\cap C| - |A \\cap B \\cap C|$.\n\nהצבה והחלפת $|A \\cup B|$ נותנת את הזהות. $\\blacksquare$"),
    P("prf_multinomial_theorem", "thm_multinomial_theorem",
      ["def_permutation_with_repetition", "thm_binomial_theorem"],
      "**הוכחה קומבינטורית.** $(x_1 + \\cdots + x_m)^n$ — מכפילים $n$ סוגריים, כל סוגריים בוחר אחד מ-$x_i$.\n\nאיבר $x_1^{n_1} x_2^{n_2} \\cdots x_m^{n_m}$ (עם $\\sum n_i = n$) נוצר בכמה דרכים שניתן לבחור איזה סוגריים נותן $x_1$ (יש $\\binom{n}{n_1}$), אז איזה נותן $x_2$ מהשאר, וכו'. סך הכל $\\frac{n!}{n_1! n_2! \\cdots n_m!}$. $\\blacksquare$"),
    P("prf_derangement_formula", "thm_derangement_formula",
      ["def_derangement", "thm_inclusion_exclusion_three_sets",
       "thm_maclaurin_exp"],
      "**ע״י הכלה-הפרדה.** $A_i$ — סט הפרמוטציות שמקבעות את $i$. $|A_i| = (n-1)!$, $|A_i \\cap A_j| = (n-2)!$, וכו'.\n\nמספר הפרמוטציות שמקבעות לפחות נקודה אחת: $\\sum (-1)^{k+1} \\binom{n}{k}(n-k)!$. $D_n = n! - $ זה $= n! \\sum_{k=0}^n \\frac{(-1)^k}{k!}$.\n\nכש-$n \\to \\infty$, הסכום הפנימי מתכנס ל-$e^{-1}$ (טור מקלורין של $e^{-1}$), ולכן $D_n \\approx n!/e$. $\\blacksquare$"),
    P("prf_stars_and_bars", "thm_stars_and_bars",
      ["thm_combinations_formula"],
      "מציגים $n$ כוכבים בשורה. כדי לפצל אותם ל-$k$ קבוצות (לפי המשתנים $x_1, \\ldots, x_k$) צריך להציב $k - 1$ קווי הפרדה ביניהם.\n\nסך הכל $n + (k-1)$ מקומות, בוחרים $k-1$ מהם להיות קווים: $\\binom{n + k - 1}{k - 1}$. $\\blacksquare$"),

    # ── Applied math ──
    P("prf_compound_interest_formula", "thm_compound_interest_formula",
      ["def_compound_interest", "def_natural_power"],
      "אחרי תקופת חישוב אחת בריבית $r$: סכום $P (1 + r)$. אחרי $t$ תקופות: $P(1 + r)^t$ ע״י אינדוקציה / שימוש חוזר בנוסחה.\n\nכשמחושב $n$ פעמים בשנה: כל תקופה ריבית $r/n$, ויש $nt$ תקופות, אז $A = P(1 + r/n)^{nt}$. $\\blacksquare$"),
    P("prf_present_value", "thm_present_value",
      ["thm_compound_interest_formula"],
      "אם $P$ היום שווה $A$ בעוד $t$ שנים: $A = P(1 + r)^t$. סידור ל-$P$: $P = A(1 + r)^{-t}$.\n\nבריבית רציפה $A = P e^{rt}$, ולכן $P = A e^{-rt}$. $\\blacksquare$"),
    P("prf_kinematic_no_time", "thm_kinematic_no_time",
      ["def_motion_constant_acceleration"],
      "מ-$v = v_0 + at$ נבודד $t = (v - v_0)/a$. נציב ב-$x = x_0 + v_0 t + \\tfrac{1}{2} a t^2$:\n\n$x - x_0 = v_0 \\cdot \\frac{v - v_0}{a} + \\frac{1}{2} a \\cdot \\frac{(v - v_0)^2}{a^2} = \\frac{v^2 - v_0^2}{2a}$.\n\nכפל ב-$2a$: $v^2 - v_0^2 = 2 a (x - x_0)$. $\\blacksquare$"),
    P("prf_carbon_dating", "thm_carbon_dating",
      ["def_exponential_decay_physics", "def_half_life",
       "thm_log_of_quotient"],
      "מהדעיכה: $N/N_0 = e^{-\\lambda t}$. לוקחים לוגריתם: $\\ln(N/N_0) = -\\lambda t$.\n\nמ-$T_{1/2} = \\ln 2 / \\lambda$ נקבל $\\lambda = \\ln 2 / T_{1/2}$. הצבה: $t = -\\frac{T_{1/2}}{\\ln 2} \\ln(N/N_0)$. $\\blacksquare$"),
    P("prf_logistic_solution", "thm_logistic_solution",
      ["def_logistic_growth", "thm_integral_substitution",
       "thm_integral_one_over_x"],
      "המשוואה $\\frac{dP}{dt} = rP(1 - P/K)$ ניתנת לפתרון בהפרדת משתנים: $\\int \\frac{dP}{P(1 - P/K)} = \\int r \\, dt$.\n\nפיצול לשברים חלקיים: $\\frac{1}{P(1-P/K)} = \\frac{1}{P} + \\frac{1/K}{1 - P/K}$.\n\nאינטגרציה ופתרון ל-$P(t)$ נותנים את הנוסחה הלוגיסטית. $\\blacksquare$"),
]
