"""Chunk 10 — 100 claims: algebraic identities, proof methods, calculus extras,
   Ptolemy/Apollonius, advanced number theory, Euler formula, Markov/exponential,
   classical inequalities (AM-HM/Bernoulli/Jensen), Taylor remainder.
"""
from __future__ import annotations

from core.models import Claim, Course, Proof


CANON = "canonical"


def C(cid, kind, course, topic, stmt):
    return Claim(id=cid, kind=kind, status=CANON, course=course,
                 topic=topic, statement=stmt)


def P(pid, cid, deps, body, method="informal", status="reviewed", canonical=True):
    return Proof(id=pid, claim_id=cid, dependencies=list(deps), body=body,
                 method=method, status=status, is_canonical=canonical)


ELEM = "math_elementary"
JHS = "math_jhs"
HS3 = "math_hs_3"
HS4 = "math_hs_4"
HS5 = "math_hs_5"
FOUND = "math_foundations"


COURSES: list[Course] = []


CLAIMS = [
    # ═══ Algebraic identities ═══
    C("thm_sum_of_cubes", "theorem", HS3, "זהויות אלגבריות",
      r"**סכום מעוקבים:** $a^3 + b^3 = (a + b)(a^2 - ab + b^2)$."),
    C("thm_difference_of_cubes", "theorem", HS3, "זהויות אלגבריות",
      r"**הפרש מעוקבים:** $a^3 - b^3 = (a - b)(a^2 + ab + b^2)$."),
    C("thm_cube_of_sum", "theorem", HS3, "זהויות אלגבריות",
      r"**מעוקב של סכום:** $(a + b)^3 = a^3 + 3a^2 b + 3a b^2 + b^3$."),
    C("thm_cube_of_difference", "theorem", HS3, "זהויות אלגבריות",
      r"**מעוקב של הפרש:** $(a - b)^3 = a^3 - 3a^2 b + 3a b^2 - b^3$."),
    C("def_synthetic_division", "definition", HS3, "פולינומים",
      r"**חילוק הורנר (סינתטי):** שיטה מהירה לחלק פולינום ב-$(x - c)$ ע״י מקדמים בלבד. הסתמכות על הקשר $p(c) =$ שארית."),
    C("def_polynomial_long_division", "definition", HS3, "פולינומים",
      r"**חילוק פולינומים ארוך:** אלגוריתם הדומה לחילוק ארוך של מספרים. תוצאה: $p(x) = d(x) q(x) + r(x)$ עם $\deg r < \deg d$."),
    C("thm_rational_root_theorem", "theorem", HS3, "פולינומים",
      r"**משפט שורש רציונלי:** עבור פולינום $a_n x^n + \cdots + a_0$ עם מקדמים שלמים: כל שורש רציונלי $p/q$ (במצורה מצומצמת) מקיים $p \mid a_0$ ו-$q \mid a_n$."),
    C("thm_vieta_for_cubic", "theorem", HS5, "פולינומים",
      r"**נוסחאות וייטה — קוביה:** עבור $a x^3 + b x^2 + c x + d = 0$ עם שורשים $x_1, x_2, x_3$: $x_1+x_2+x_3 = -\frac{b}{a}$, $x_1 x_2 + x_1 x_3 + x_2 x_3 = \frac{c}{a}$, $x_1 x_2 x_3 = -\frac{d}{a}$."),
    C("def_partial_fractions_method", "definition", HS5, "פולינומים",
      r"**שיטת השברים החלקיים:** פירוק $\frac{P(x)}{Q(x)}$ לסכום שברים פשוטים לפי גורמי $Q$. שימושית לאינטגרציה של רציונליים."),
    C("def_lagrange_interpolation", "definition", HS5, "פולינומים",
      r"**אינטרפולציית לגראנז׳:** עבור $n+1$ נקודות $(x_i, y_i)$ עם $x_i$ שונים — קיים פולינום יחיד מדרגה $\leq n$ העובר דרכן. הנוסחה: $L(x) = \sum_i y_i \prod_{j \neq i} \frac{x - x_j}{x_i - x_j}$."),

    # ═══ Proof methods ═══
    C("def_direct_proof", "definition", FOUND, "שיטות הוכחה",
      r"**הוכחה ישירה:** מהנתונים, באמצעות שרשרת היגיון תקפה, מסקנה ישירה לתוצאה. הצורה הנפוצה ביותר של הוכחה."),
    C("def_proof_by_contradiction", "definition", FOUND, "שיטות הוכחה",
      r"**הוכחה בדרך השלילה:** מניחים את שלילת המסקנה (יחד עם הנתונים), ומראים שזה מוביל לסתירה. לכן ההנחה לא נכונה ולכן המסקנה כן."),
    C("def_proof_by_induction", "definition", FOUND, "שיטות הוכחה",
      r"**הוכחה באינדוקציה מתמטית:** להוכיח טענה $P(n)$ לכל $n \in \mathbb{N}$: (1) **בסיס** — מוכיחים $P(1)$; (2) **צעד** — מוכיחים $P(n) \Rightarrow P(n+1)$ לכל $n$."),
    C("def_proof_by_strong_induction", "definition", FOUND, "שיטות הוכחה",
      r"**אינדוקציה חזקה:** וריאנט שבו הצעד מוכיח $P(n+1)$ מהנחה שכל $P(1), P(2), \ldots, P(n)$ מתקיימים. שקול לאינדוקציה רגילה אבל לעיתים נוח יותר."),
    C("def_proof_by_contrapositive", "definition", FOUND, "שיטות הוכחה",
      r"**הוכחה בדרך הניגוד:** במקום $P \Rightarrow Q$, מוכיחים את שקול-הניגוד $\neg Q \Rightarrow \neg P$."),
    C("def_counterexample", "definition", FOUND, "שיטות הוכחה",
      r"**דוגמה נגדית:** כדי להפריך טענה כללית 'לכל $x$, $P(x)$', מספיק להציג $x_0$ שעבורו $P(x_0)$ אינו מתקיים."),
    C("thm_pigeonhole_principle", "theorem", FOUND, "שיטות הוכחה",
      r"**עקרון שובך היונים:** אם $n+1$ עצמים מחולקים ל-$n$ קבוצות, אז קבוצה אחת לפחות מכילה שני עצמים או יותר. כללי: $kn+1$ עצמים ב-$n$ קבוצות → קבוצה אחת עם $k+1$ עצמים."),
    C("thm_well_ordering_principle", "theorem", FOUND, "שיטות הוכחה",
      r"**עקרון הסדר הטוב:** לכל קבוצה לא-ריקה של מספרים טבעיים יש איבר מינימלי. שקול לעקרון האינדוקציה."),

    # ═══ Calculus extras ═══
    C("def_newton_method", "definition", HS5, "שיטות נומריות",
      r"**שיטת ניוטון למציאת שורש:** $x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)}$ — איטרציה החל מ-$x_0$ קרוב לשורש. מתכנסת במהירות (סדר ריבועי) אם $f' \neq 0$ בשורש."),
    C("def_linear_approximation", "definition", HS5, "נגזרת מתקדמת",
      r"**קירוב לינארי:** עבור $f$ גזירה ב-$a$: $f(x) \approx f(a) + f'(a)(x - a)$ עבור $x$ קרוב ל-$a$. זה למעשה ערך הקו המשיק."),
    C("def_differential", "definition", HS5, "נגזרת מתקדמת",
      r"**דיפרנציאל:** $dy := f'(x) \, dx$ — שינוי לינארי משוער של $y$ כאשר $x$ זז ב-$dx$. שימושי בקירובים ובאינטגרציה."),
    C("def_higher_order_derivative", "definition", HS5, "נגזרת מתקדמת",
      r"**נגזרות מסדר גבוה:** $f''$, $f'''$, וכלל $f^{(n)}$ — חזרה על תהליך הגזירה $n$ פעמים. סימון: $\frac{d^n y}{d x^n}$."),
    C("thm_inflection_point_test", "theorem", HS5, "יישומי נגזרת",
      r"**זיהוי נקודת פיתול:** $x_0$ נקודת פיתול של $f$ אם $f''(x_0) = 0$ (או לא קיימת) ו-$f''$ משנה סימן ב-$x_0$."),
    C("def_convex_function", "definition", HS5, "אנליזת פונקציות",
      r"**פונקציה קמורה:** $f$ נקראת **קמורה** בקטע אם לכל $x_1, x_2$ ו-$\lambda \in [0, 1]$: $f(\lambda x_1 + (1-\lambda) x_2) \leq \lambda f(x_1) + (1-\lambda) f(x_2)$. שווה ערך לקעירות כלפי מעלה."),
    C("def_concave_function", "definition", HS5, "אנליזת פונקציות",
      r"**פונקציה קעורה:** $f$ נקראת **קעורה** אם $-f$ קמורה — אי-שוויון הפוך. שווה ערך לקעירות כלפי מטה."),
    C("thm_jensen_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון ינסן:** עבור $f$ קמורה ומשקלים $\lambda_i \geq 0$ עם $\sum \lambda_i = 1$: $f\!\left(\sum \lambda_i x_i\right) \leq \sum \lambda_i f(x_i)$. עבור קעורה — אי-שוויון הפוך."),
    C("def_power_series", "definition", HS5, "טור טיילור",
      r"**טור חזקות:** $\sum_{n=0}^{\infty} a_n (x - c)^n$ — טור עם משתנה $x$ סביב מרכז $c$. מתכנס באיזור $|x - c| < R$ (רדיוס התכנסות)."),
    C("thm_maclaurin_ln_one_plus_x", "theorem", HS5, "טור טיילור",
      r"**מקלורין של $\ln(1+x)$:** $\ln(1+x) = x - \frac{x^2}{2} + \frac{x^3}{3} - \cdots = \sum_{n=1}^{\infty} \frac{(-1)^{n+1} x^n}{n}$, מתכנס ב-$-1 < x \leq 1$."),
    C("thm_maclaurin_geometric", "theorem", HS5, "טור טיילור",
      r"**מקלורין של $\frac{1}{1-x}$:** $\frac{1}{1 - x} = \sum_{n=0}^{\infty} x^n = 1 + x + x^2 + x^3 + \cdots$, מתכנס ב-$|x| < 1$."),
    C("def_trig_substitution", "definition", HS5, "אינטגרל מתקדם",
      r"**הצבה טריגונומטרית באינטגרל:** ל-$\sqrt{a^2 - x^2}$ → $x = a\sin\theta$; ל-$\sqrt{a^2 + x^2}$ → $x = a\tan\theta$; ל-$\sqrt{x^2 - a^2}$ → $x = a\sec\theta$."),

    # ═══ Geometry extras ═══
    C("thm_ptolemy_theorem", "theorem", HS5, "גאומטריה מתקדמת",
      r"**משפט תלמי:** במרובע $ABCD$ החסום במעגל: $AC \cdot BD = AB \cdot CD + AD \cdot BC$ (מכפלת אלכסונים = סכום מכפלות צלעות נגדיות)."),
    C("thm_apollonius_median", "theorem", HS5, "גאומטריה מתקדמת",
      r"**משפט אפולוניוס (אורך תיכון):** במשולש $ABC$ עם תיכון $AM$ אל אמצע $BC$: $b^2 + c^2 = 2 m_a^2 + \frac{a^2}{2}$, או $m_a = \frac{1}{2}\sqrt{2b^2 + 2c^2 - a^2}$."),
    C("thm_angle_bisector_length", "theorem", HS5, "גאומטריה מתקדמת",
      r"**אורך חוצה זווית:** עבור חוצה זווית $A$ במשולש $ABC$: $t_a^2 = bc - \frac{a^2 bc}{(b+c)^2} = bc\!\left(1 - \frac{a^2}{(b+c)^2}\right)$."),
    C("thm_altitude_length", "theorem", HS5, "גאומטריה",
      r"**אורך גובה במשולש:** $h_a = \frac{2 S}{a}$, כאשר $S$ שטח ו-$a$ אורך הצלע שאליה הוא יורד."),
    C("def_excircle", "definition", HS5, "גאומטריה מתקדמת",
      r"**מעגל חוץ:** עבור משולש — מעגל המשיק לצלע אחת ולהארכות שתי הצלעות האחרות. יש 3 כאלה. מרכזיהם נקראים מרכזי חוץ."),
    C("thm_arc_length_in_circle", "theorem", HS3, "גאומטריה",
      r"**אורך קשת במעגל:** קשת בזווית מרכזית $\theta$ (ברדיאנים) במעגל ברדיוס $r$: $L = r \theta$."),
    C("thm_sector_area_formula", "theorem", HS3, "גאומטריה",
      r"**שטח גזרה:** $S = \frac{1}{2} r^2 \theta$ ($\theta$ ברדיאנים), או $\frac{\theta}{2\pi} \cdot \pi r^2$ (ביחס שבר העיגול)."),
    C("def_regular_polygon", "definition", HS3, "גאומטריה",
      r"**מצולע משוכלל:** מצולע שכל צלעותיו שוות וכל זוויותיו שוות. זווית פנימית של משוכלל בעל $n$ צלעות: $\frac{(n-2) \cdot 180°}{n}$."),
    C("thm_pi_circle_constant", "theorem", HS3, "גאומטריה",
      r"**$\pi$ כקבוע מעגל:** היחס בין היקף מעגל לקוטרו הוא קבוע גלובלי $\pi \approx 3.14159265\ldots$, ולכן היקף $= 2\pi r$ ושטח $= \pi r^2$."),
    C("def_solid_angle", "definition", HS5, "גאומטריה במרחב",
      r"**זווית מרחבית (סטרדיאן):** האנלוג ה-3D של זווית רדיאן. נמדדת ע״י שטח על כדור היחידה. כדור שלם = $4\pi$ סטרדיאן."),

    # ═══ Number theory advanced ═══
    C("def_mobius_function", "definition", HS5, "תורת מספרים מתקדמת",
      r"**פונקציית מוביוס $\mu(n)$:** $\mu(1) = 1$; $\mu(n) = 0$ אם $n$ מתחלק בריבוע של ראשוני; אחרת $\mu(n) = (-1)^k$ כאשר $n$ מכפלת $k$ ראשוניים שונים."),
    C("def_sigma_function", "definition", HS5, "תורת מספרים מתקדמת",
      r"**סכום המחלקים $\sigma(n)$:** סכום כל המחלקים החיוביים של $n$. למשל $\sigma(6) = 1+2+3+6 = 12$."),
    C("def_tau_function", "definition", HS5, "תורת מספרים מתקדמת",
      r"**מספר המחלקים $\tau(n)$ (גם $d(n)$):** מספר המחלקים החיוביים של $n$. עבור $n = p_1^{a_1} \cdots p_k^{a_k}$: $\tau(n) = (a_1+1)(a_2+1)\cdots(a_k+1)$."),
    C("def_multiplicative_function", "definition", HS5, "תורת מספרים מתקדמת",
      r"**פונקציה מולטיפליקטיבית:** $f: \mathbb{N} \to \mathbb{C}$ נקראת מולטיפליקטיבית אם $f(mn) = f(m) f(n)$ לכל $\gcd(m, n) = 1$. למשל $\varphi, \mu, \sigma, \tau$."),
    C("def_perfect_number", "definition", HS5, "תורת מספרים מתקדמת",
      r"**מספר מושלם:** $n$ מושלם אם $\sigma(n) = 2n$ (סכום מחלקיו הקטנים ממנו = $n$). דוגמאות: $6, 28, 496, 8128$."),
    C("def_mersenne_prime", "definition", HS5, "תורת מספרים מתקדמת",
      r"**ראשוני מרסן:** ראשוני מהצורה $M_p = 2^p - 1$ עבור $p$ ראשוני. קשור הדוקות למספרים מושלמים זוגיים."),
    C("thm_perfect_mersenne_correspondence", "theorem", HS5, "תורת מספרים מתקדמת",
      r"**משפט אוקלידס-אוילר:** כל מספר מושלם זוגי הוא בצורה $2^{p-1}(2^p - 1)$ עבור $2^p - 1$ ראשוני מרסן."),
    C("def_prime_counting_function", "definition", HS5, "תורת מספרים מתקדמת",
      r"**פונקציית מנייה של ראשוניים $\pi(n)$:** מספר הראשוניים שאינם עולים על $n$. למשל $\pi(10) = 4$ (2, 3, 5, 7)."),
    C("thm_prime_number_theorem", "theorem", HS5, "תורת מספרים מתקדמת",
      r"**משפט המספרים הראשוניים (PNT):** $\pi(n) \sim \frac{n}{\ln n}$, כלומר $\lim_{n \to \infty} \frac{\pi(n) \ln n}{n} = 1$."),
    C("def_arithmetic_function", "definition", HS5, "תורת מספרים מתקדמת",
      r"**פונקציה אריתמטית:** פונקציה $f: \mathbb{N} \to \mathbb{C}$ (לרוב $\mathbb{R}$ או $\mathbb{Z}$) — בסיס לתורת המספרים האנליטית."),

    # ═══ Euler formula and complex extras ═══
    C("thm_euler_formula", "theorem", HS5, "מספרים מרוכבים",
      r"**נוסחת אוילר:** $e^{i\theta} = \cos\theta + i \sin\theta$ — חיבור עמוק בין מעריכי, טריגונומטריה ומרוכבים. מקרה פרטי: $e^{i\pi} + 1 = 0$ (זהות אוילר)."),
    C("thm_power_reducing_sin_squared", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**הפחתת חזקה — סינוס:** $\sin^2 x = \frac{1 - \cos(2x)}{2}$."),
    C("thm_power_reducing_cos_squared", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**הפחתת חזקה — קוסינוס:** $\cos^2 x = \frac{1 + \cos(2x)}{2}$."),
    C("thm_nth_roots_of_complex", "theorem", HS5, "מספרים מרוכבים",
      r"**שורשי יחידה כללי:** עבור $z = r e^{i\theta}$, שורשי $n$ של $z$: $\sqrt[n]{r} \cdot e^{i(\theta + 2\pi k)/n}$ עבור $k = 0, 1, \ldots, n-1$."),
    C("thm_sum_of_nth_roots_unity", "theorem", HS5, "מספרים מרוכבים",
      r"**סכום שורשי יחידה:** סכום $n$ שורשי היחידה ($n \geq 2$) שווה לאפס: $\sum_{k=0}^{n-1} e^{2\pi i k / n} = 0$."),
    C("thm_arctan_sum_identity", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**זהות סכום ארקטנגנס:** $\arctan x + \arctan(1/x) = \pi/2$ עבור $x > 0$, ו-$-\pi/2$ עבור $x < 0$."),
    C("thm_de_moivre_for_roots", "theorem", HS5, "מספרים מרוכבים",
      r"**דה-מואבר עבור שורשים:** עבור $z = r(\cos\theta + i\sin\theta)$, שורש $n$ פתרון: $z^{1/n} = r^{1/n}\!\left(\cos\frac{\theta + 2\pi k}{n} + i\sin\frac{\theta + 2\pi k}{n}\right)$, $k = 0,\ldots,n-1$."),
    C("def_complex_exponential", "definition", HS5, "מספרים מרוכבים",
      r"**מעריכי מרוכב:** $e^{a + bi} := e^a (\cos b + i \sin b) = e^a e^{ib}$ — הרחבת המעריכי הממשי, מתאים לזהות אוילר."),

    # ═══ Series & sequences extras ═══
    C("def_radius_of_convergence", "definition", HS5, "טור טיילור",
      r"**רדיוס התכנסות:** עבור טור חזקות $\sum a_n (x - c)^n$, $R$ הוא ה-$R$ הגדול ביותר כך שהטור מתכנס לכל $|x - c| < R$ ומתבדר לכל $|x - c| > R$."),
    C("thm_ratio_test_radius", "theorem", HS5, "טור טיילור",
      r"**רדיוס התכנסות מ-מבחן המנה:** $R = \lim_{n \to \infty} \left|\frac{a_n}{a_{n+1}}\right|$ אם הגבול קיים."),
    C("thm_fibonacci_binet_formula", "theorem", HS5, "סדרות מתקדם",
      r"**נוסחת בינה (פיבונאצ׳י סגור):** $F_n = \frac{\varphi^n - \psi^n}{\sqrt{5}}$, כאשר $\varphi = \frac{1+\sqrt{5}}{2}$ (יחס הזהב) ו-$\psi = \frac{1-\sqrt{5}}{2}$."),
    C("def_recurrence_relation", "definition", HS5, "סדרות מתקדם",
      r"**יחס נסיגה:** משוואה המגדירה איבר בסדרה כפונקציה של איברים קודמים. למשל $a_{n+1} = 2 a_n + 3$. **לינארית** אם הקשר לינארי, **הומוגנית** אם אין איבר חופשי."),
    C("thm_linear_recurrence_characteristic", "theorem", HS5, "סדרות מתקדם",
      r"**פתרון נסיגה לינארית הומוגנית:** $a_{n+1} = c_1 a_n + c_2 a_{n-1}$ עם משוואה אופיינית $x^2 - c_1 x - c_2 = 0$. אם שורשים שונים $r_1, r_2$: $a_n = A r_1^n + B r_2^n$."),
    C("def_catalan_numbers", "definition", HS5, "קומבינטוריקה מתקדמת",
      r"**מספרי קטלן:** $C_n = \frac{1}{n+1}\binom{2n}{n}$. סופרים מבנים רקורסיביים: עצי בינאריים עם $n$ צמתים, סוגריים מאוזנים, וכו'."),

    # ═══ Probability extras ═══
    C("def_markov_chain_intro", "definition", HS5, "הסתברות מתקדמת",
      r"**שרשרת מרקוב:** סדרת מצבים שהמעבר מ-$X_n$ ל-$X_{n+1}$ תלוי רק ב-$X_n$ (לא בעבר). מתואר ע״י מטריצת מעברים $P$ עם $P_{ij} = P(X_{n+1}=j \mid X_n=i)$."),
    C("def_exponential_distribution", "definition", HS5, "הסתברות מתקדמת",
      r"**התפלגות מעריכית:** $X \sim \text{Exp}(\lambda)$ עם צפיפות $f(x) = \lambda e^{-\lambda x}$ עבור $x \geq 0$. תוחלת $1/\lambda$, שונות $1/\lambda^2$. תכונת חוסר-זיכרון."),
    C("thm_geometric_distribution_mean", "theorem", HS5, "הסתברות מתקדמת",
      r"**ממוצע ושונות גאומטרית:** עבור $X \sim \text{Geo}(p)$: $E[X] = \frac{1}{p}$, $\text{Var}(X) = \frac{1-p}{p^2}$."),
    C("thm_least_squares_linear", "theorem", HS5, "סטטיסטיקה מתקדמת",
      r"**רגרסיה לינארית — ריבועים פחותים:** הקו $y = a x + b$ המתאים את הנתונים $(x_i, y_i)$ במזעור $\sum (y_i - ax_i - b)^2$ הוא: $a = \frac{\sum(x_i - \bar{x})(y_i - \bar{y})}{\sum(x_i - \bar{x})^2}$, $b = \bar{y} - a\bar{x}$."),
    C("def_r_squared", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**מקדם קביעות $R^2$:** $R^2 = 1 - \frac{\sum(y_i - \hat{y}_i)^2}{\sum(y_i - \bar{y})^2}$ — חלק השונות בנתונים שמוסבר ע״י המודל. $R^2 = 1$ התאמה מושלמת, $R^2 = 0$ אין הסבר."),
    C("thm_chebyshev_inequality_prob", "theorem", HS5, "הסתברות מתקדמת",
      r"**אי-שוויון צ׳בישב:** $P(|X - E[X]| \geq k \sigma) \leq \frac{1}{k^2}$ לכל $k > 0$ — חסם אוניברסלי על סטיות חריגות."),
    C("def_pearson_correlation", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**מתאם פירסון:** $r = \frac{\sum(x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum(x_i-\bar{x})^2 \cdot \sum(y_i - \bar{y})^2}}$, ערך ב-$[-1, 1]$ — מודד כיוון וחוזק קשר לינארי."),
    C("thm_binomial_normal_approximation", "theorem", HS5, "סטטיסטיקה מתקדמת",
      r"**קירוב נורמלי לבינומית:** עבור $X \sim \text{Bin}(n, p)$ ו-$n$ גדול, $X \approx N(np, np(1-p))$. לרוב מתקבל כש-$np(1-p) > 10$."),

    # ═══ Vectors & 3D extras ═══
    C("def_vector_subtraction", "definition", HS5, "וקטורים",
      r"**חיסור וקטורים:** $\vec{u} - \vec{v} := \vec{u} + (-\vec{v}) = (u_1 - v_1, u_2 - v_2, \ldots)$. גאומטרית: הוקטור מקצה $\vec{v}$ לקצה $\vec{u}$."),
    C("def_linear_combination_vectors", "definition", HS5, "וקטורים",
      r"**צירוף לינארי:** $c_1 \vec{v_1} + c_2 \vec{v_2} + \cdots + c_k \vec{v_k}$ עבור סקלרים $c_i$. כל וקטור במרחב $k$-מימדי הוא צירוף לינארי של בסיס."),
    C("def_span_of_vectors", "definition", HS5, "אלגברה לינארית",
      r"**מרחב פרישה:** $\text{span}(\vec{v_1}, \ldots, \vec{v_k}) := $ קבוצת כל הצירופים הלינאריים האפשריים שלהם. תמיד תת-מרחב."),
    C("thm_cross_product_anticommutative", "theorem", HS5, "וקטורים",
      r"**אנטי-קומוטטיביות מכפלה וקטורית:** $\vec{u} \times \vec{v} = -\vec{v} \times \vec{u}$."),
    C("thm_parallelogram_area_cross", "theorem", HS5, "וקטורים",
      r"**שטח מקבילית כמכפלה וקטורית:** $|\vec{u} \times \vec{v}|$ שווה לשטח המקבילית הנפרשת על-ידי $\vec{u}, \vec{v}$."),

    # ═══ Classical inequalities extras ═══
    C("thm_am_hm_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**AM-HM:** עבור $a_1, \ldots, a_n > 0$: $\frac{a_1 + \cdots + a_n}{n} \geq \frac{n}{\frac{1}{a_1} + \cdots + \frac{1}{a_n}}$."),
    C("thm_gm_hm_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**GM-HM:** $\sqrt[n]{a_1 \cdots a_n} \geq \frac{n}{\frac{1}{a_1} + \cdots + \frac{1}{a_n}}$ (לכל $a_i > 0$)."),
    C("thm_bernoulli_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון ברנולי:** $(1 + x)^n \geq 1 + nx$ לכל $x \geq -1$ ו-$n \in \mathbb{N}$ (או $n \geq 1$ ממשי, עם תנאי $1+x \geq 0$)."),
    C("thm_qm_am_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**QM-AM:** $\sqrt{\frac{a_1^2 + \cdots + a_n^2}{n}} \geq \frac{a_1 + \cdots + a_n}{n}$ — ממוצע ריבועי $\geq$ ממוצע חשבוני."),
    C("thm_rearrangement_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון ההצבה החדשה:** עבור $a_1 \leq a_2 \leq \cdots$ ו-$b_1 \leq b_2 \leq \cdots$, סכום $\sum a_i b_{\sigma(i)}$ מקסימלי כש-$\sigma$ זהות (סדר עולה), ומינימלי כש-$\sigma$ הפוך."),
    C("thm_power_mean_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון הממוצעים הכלליים:** עבור $r > s$ ו-$a_i > 0$: $M_r(a) \geq M_s(a)$, כאשר $M_p(a) = \left(\frac{\sum a_i^p}{n}\right)^{1/p}$ (מקרים פרטיים: QM ≥ AM ≥ GM ≥ HM)."),

    # ═══ More calculus apps ═══
    C("thm_cauchy_mean_value", "theorem", HS5, "יישומי נגזרת",
      r"**משפט ערך ממוצע של קושי:** עבור $f, g$ רציפות ב-$[a, b]$ וגזירות ב-$(a, b)$ עם $g'(x) \neq 0$: קיים $c \in (a, b)$ עם $\frac{f(b) - f(a)}{g(b) - g(a)} = \frac{f'(c)}{g'(c)}$."),
    C("def_indeterminate_form", "definition", HS5, "גבולות",
      r"**צורות לא-מוגדרות:** ביטויים כמו $\frac{0}{0}, \frac{\infty}{\infty}, 0 \cdot \infty, \infty - \infty, 1^\infty, 0^0, \infty^0$ — הגבול תלוי בפונקציות הספציפיות. לרוב פותרים בעזרת לופיטל או אלגברה."),
    C("thm_lhopital_for_all_forms", "theorem", HS5, "גבולות",
      r"**לופיטל לכל הצורות:** הצורות $\frac{0}{0}$ ו-$\frac{\infty}{\infty}$ פותרים ישירות. אחרות מתאלצות לאחת מהן: $0 \cdot \infty \to \frac{0}{1/\infty}$, $\infty^0$ דרך לוגריתם, וכו'."),
    C("def_fixed_point", "definition", HS5, "שיטות נומריות",
      r"**נקודת שבת:** $x_0$ נקראת נקודת שבת של $g$ אם $g(x_0) = x_0$. שיטת איטרציה: $x_{n+1} = g(x_n)$ מתכנסת לנקודת שבת אם $|g'(x_0)| < 1$."),
    C("thm_taylor_remainder_lagrange", "theorem", HS5, "טור טיילור",
      r"**שארית טיילור (לגראנז׳):** $f(x) = \sum_{k=0}^{n} \frac{f^{(k)}(a)}{k!}(x - a)^k + R_n(x)$, כאשר $R_n(x) = \frac{f^{(n+1)}(\xi)}{(n+1)!}(x - a)^{n+1}$ עבור $\xi$ ביניהם."),
    C("def_critical_point_classification_full", "definition", HS5, "יישומי נגזרת",
      r"**סיווג נקודות חשודות (סיכום):** עבור $f'(x_0) = 0$: $f''(x_0) > 0$ → מינ׳ מקומי; $f''(x_0) < 0$ → מקס׳; $f''(x_0) = 0$ → צריך לבדוק נגזרות גבוהות יותר או סימן $f'$ סביב."),
    C("def_critical_point_via_first_derivative", "definition", HS5, "יישומי נגזרת",
      r"**מבחן הנגזרת הראשונה (סיווג):** במקום נגזרת שנייה, בודקים סימן של $f'$ משמאל ומימין לנקודה החשודה. שינוי $+ \to -$ → מקס׳; $- \to +$ → מינ׳; אותו סימן → לא קיצון."),

    # ═══ Misc / Algebra cont ═══
    C("thm_descartes_rule_of_signs", "theorem", HS5, "פולינומים",
      r"**משפט סימני דקארט:** מספר השורשים החיוביים האמיתיים של פולינום עם מקדמים ממשיים שווה למספר שינויי הסימן בסדרת מקדמיו, או פחות מזה במספר זוגי."),
    C("def_fundamental_theorem_of_algebra", "definition", HS5, "פולינומים",
      r"**המשפט היסודי של האלגברה (ניסוח):** כל פולינום עם מקדמים מרוכבים מדרגה $\geq 1$ יש לו לפחות שורש מרוכב. שקול: פולינום מדרגה $n$ יש לו בדיוק $n$ שורשים מרוכבים (עם ריבוי)."),
    C("thm_fundamental_theorem_of_algebra", "theorem", HS5, "פולינומים",
      r"**המשפט היסודי של האלגברה:** כל פולינום $p(z)$ מדרגה $n \geq 1$ עם מקדמים מרוכבים מתפרק לחלוטין: $p(z) = a_n (z - z_1)(z - z_2) \cdots (z - z_n)$ עבור שורשים מרוכבים (לאו דווקא שונים)."),
    C("def_complex_conjugate_root_theorem", "definition", HS5, "פולינומים",
      r"**משפט הצמודים המרוכבים:** אם $p(z)$ פולינום עם מקדמים ממשיים ו-$\zeta$ שורש מרוכב, גם $\bar{\zeta}$ שורש. כלומר שורשים לא-ממשיים מופיעים בזוגות צמודים."),
    C("def_generating_function", "definition", HS5, "קומבינטוריקה מתקדמת",
      r"**פונקציה יוצרת:** עבור סדרה $a_0, a_1, a_2, \ldots$, פונקציה יוצרת רגילה: $A(x) = \sum_{n=0}^{\infty} a_n x^n$. שימושית לפתרון יחסי נסיגה ובעיות סופירה."),
    C("def_well_definedness", "definition", FOUND, "שיטות הוכחה",
      r"**הגדרה היטב:** הגדרה היטב היא אם התוצאה אינה תלויה בבחירה שרירותית. למשל $\frac{a}{b}$ מוגדרת היטב על מחלקות שקילות כי $\frac{a_1}{b_1} = \frac{a_2}{b_2}$ → אותו אובייקט."),
]


PROOFS = [
    # ── Algebraic identities ──
    P("prf_sum_of_cubes", "thm_sum_of_cubes",
      ["ax_distributive_law", "thm_right_distributive_law",
       "ax_addition_commutativity"],
      "פתיחה ישירה: $(a + b)(a^2 - ab + b^2) = a^3 - a^2 b + a b^2 + a^2 b - a b^2 + b^3 = a^3 + b^3$ (איברי האמצע מתבטלים). $\\blacksquare$"),
    P("prf_difference_of_cubes", "thm_difference_of_cubes",
      ["ax_distributive_law", "thm_right_distributive_law"],
      "פתיחה: $(a - b)(a^2 + ab + b^2) = a^3 + a^2 b + a b^2 - a^2 b - a b^2 - b^3 = a^3 - b^3$. $\\blacksquare$"),
    P("prf_cube_of_sum", "thm_cube_of_sum",
      ["thm_binomial_theorem"],
      "מבינום ניוטון: $(a+b)^3 = \\sum_{k=0}^{3} \\binom{3}{k} a^{3-k} b^k = a^3 + 3a^2 b + 3a b^2 + b^3$. $\\blacksquare$"),
    P("prf_cube_of_difference", "thm_cube_of_difference",
      ["thm_cube_of_sum"],
      "הצבה $b \\to -b$ ב-$(a+b)^3$ וזיהוי הסימנים: $(a-b)^3 = a^3 + 3a^2(-b) + 3a(-b)^2 + (-b)^3 = a^3 - 3a^2 b + 3a b^2 - b^3$. $\\blacksquare$"),
    P("prf_rational_root_theorem", "thm_rational_root_theorem",
      ["def_polynomial", "thm_gcd_lcm_product", "def_divisibility"],
      "נניח $p(p/q) = 0$ עם $\\gcd(p, q) = 1$. כפל ב-$q^n$: $a_n p^n + a_{n-1} p^{n-1} q + \\cdots + a_0 q^n = 0$.\n\nכל אגף שמאל מתחלק ב-$p$ (חוץ מ-$a_0 q^n$), אז $p \\mid a_0 q^n$. כי $\\gcd(p, q) = 1$, $p \\mid a_0$. סימטרית $q \\mid a_n$. $\\blacksquare$"),
    P("prf_vieta_for_cubic", "thm_vieta_for_cubic",
      ["thm_fundamental_theorem_of_algebra", "ax_distributive_law"],
      "$a(x - x_1)(x - x_2)(x - x_3) = a x^3 - a(x_1+x_2+x_3) x^2 + a(x_1 x_2 + x_1 x_3 + x_2 x_3) x - a x_1 x_2 x_3$.\n\nהשוואה למקדמים $a x^3 + b x^2 + c x + d$ נותנת את הזהויות. $\\blacksquare$"),

    # ── Proof methods ──
    P("prf_pigeonhole_principle", "thm_pigeonhole_principle",
      ["thm_well_ordering_principle"],
      "**הוכחה בשלילה.** נניח שכל אחת מ-$n$ הקבוצות מכילה לכל היותר עצם אחד. סכום העצמים $\\leq n$. סתירה לכך שיש $n+1$ עצמים. $\\blacksquare$"),
    P("prf_well_ordering_principle", "thm_well_ordering_principle",
      ["def_natural_numbers", "def_proof_by_induction"],
      "**שקול לאינדוקציה.** נניח קבוצה $S \\subseteq \\mathbb{N}$ ללא איבר מינימלי. נראה ש-$S = \\emptyset$.\n\nנגדיר $T = \\{n : \\forall m \\leq n, m \\notin S\\}$. $0 \\in T$ (אחרת $0 \\in S$ והיה מינימום). אם $n \\in T$ ו-$n+1 \\in S$, אז $n+1$ מינימלי. אז $n+1 \\notin S$ ולכן $n+1 \\in T$. באינדוקציה $T = \\mathbb{N}$, אז $S = \\emptyset$. $\\blacksquare$"),

    # ── Calculus extras ──
    P("prf_inflection_point_test", "thm_inflection_point_test",
      ["thm_concavity_second_derivative", "def_inflection_point"],
      "נקודת פיתול = שינוי קעירות. לפי תיאוריית קעירות, סימן $f''$ קובע קעירות. שינוי סימן ב-$x_0$ מצביע על שינוי קעירות שם, כלומר פיתול. תנאי הכרחי $f''(x_0) = 0$ (או לא קיימת). $\\blacksquare$"),
    P("prf_jensen_inequality", "thm_jensen_inequality",
      ["def_convex_function"],
      "**הוכחה באינדוקציה על $n$.** $n=1$: טריוויאלי. $n=2$: בדיוק הגדרת קמירות.\n\nצעד: נניח עבור $n$, נראה ל-$n+1$. נסמן $\\Lambda = \\sum_{i=1}^{n} \\lambda_i = 1 - \\lambda_{n+1}$. אז $\\sum \\lambda_i x_i = \\Lambda \\cdot \\frac{\\sum_{i \\leq n} \\lambda_i x_i}{\\Lambda} + \\lambda_{n+1} x_{n+1}$. נשתמש בקמירות (אגף ימין) ובהנחת האינדוקציה. $\\blacksquare$"),
    P("prf_maclaurin_ln_one_plus_x", "thm_maclaurin_ln_one_plus_x",
      ["thm_derivative_log_natural", "def_maclaurin_series"],
      "$f(x) = \\ln(1+x)$. נגזרות: $f'(x) = \\frac{1}{1+x}$, $f''(x) = -\\frac{1}{(1+x)^2}$, $f^{(n)}(x) = \\frac{(-1)^{n-1}(n-1)!}{(1+x)^n}$.\n\nערכים ב-$0$: $f^{(n)}(0) = (-1)^{n-1}(n-1)!$. הצבה במקלורין: $\\sum_n \\frac{(-1)^{n-1}(n-1)!}{n!} x^n = \\sum \\frac{(-1)^{n-1} x^n}{n}$. $\\blacksquare$"),
    P("prf_maclaurin_geometric", "thm_maclaurin_geometric",
      ["def_maclaurin_series", "thm_geometric_series_convergence"],
      "ידוע $\\sum x^n = \\frac{1}{1-x}$ עבור $|x| < 1$ (טור הנדסי). זה בדיוק טור מקלורין של $\\frac{1}{1-x}$, ניתן לאמת ע״י נגזרות $f^{(n)}(0) = n!$. $\\blacksquare$"),

    # ── Geometry extras ──
    P("prf_ptolemy_theorem", "thm_ptolemy_theorem",
      ["def_circle", "thm_aa_similarity",
       "thm_inscribed_angles_same_arc"],
      "**הוכחה (גישה דמיון).** נקח $E$ על $AC$ עם $\\angle ABE = \\angle CBD$. אז $\\triangle ABE \\sim \\triangle DBC$ ו-$\\triangle ABD \\sim \\triangle EBC$ (זוויות שוות מהקשתות).\n\nמהדמיון: $AE \\cdot BD = AB \\cdot CD$ ו-$EC \\cdot BD = AD \\cdot BC$. חיבור: $(AE + EC) \\cdot BD = AB \\cdot CD + AD \\cdot BC$, וזה $AC \\cdot BD$. $\\blacksquare$"),
    P("prf_apollonius_median", "thm_apollonius_median",
      ["thm_law_of_cosines", "def_centroid"],
      "**הוכחה (קוסינוסים).** $M$ אמצע $BC$, $BM = MC = a/2$. במשולש $ABM$ ו-$ACM$ נשתמש בקוסינוסים על הזוויות ב-$M$ (שהן משלימות).\n\n$c^2 = m_a^2 + (a/2)^2 - a m_a \\cos\\theta$\n\n$b^2 = m_a^2 + (a/2)^2 + a m_a \\cos\\theta$\n\nחיבור: $b^2 + c^2 = 2m_a^2 + a^2/2$, כלומר $m_a = \\frac{1}{2}\\sqrt{2b^2 + 2c^2 - a^2}$. $\\blacksquare$"),
    P("prf_altitude_length", "thm_altitude_length",
      ["thm_triangle_area_base_height"],
      "מהנוסחה היסודית $S = \\tfrac{1}{2} a h_a$, פתרון ל-$h_a$ ע\"י כפל ב-$2$ וחלוקה ב-$a$: $h_a = \\dfrac{2S}{a}$. $\\blacksquare$"),
    P("prf_arc_length_in_circle", "thm_arc_length_in_circle",
      ["def_radian"],
      "מהגדרת הרדיאן: זווית של $1$ רדיאן מתאימה לקשת באורך $r$ (הרדיוס). מליניאריות, זווית $\\theta$ → קשת $r\\theta$. $\\blacksquare$"),
    P("prf_sector_area_formula", "thm_sector_area_formula",
      ["def_radian", "thm_pi_circle_constant"],
      "שטח עיגול שלם $\\pi r^2$ מתאים לזווית $2\\pi$. שטח גזרה בזווית $\\theta$: $\\frac{\\theta}{2\\pi} \\cdot \\pi r^2 = \\frac{1}{2}r^2 \\theta$. $\\blacksquare$"),
    P("prf_pi_circle_constant", "thm_pi_circle_constant",
      ["def_circle"],
      "**הגדרה.** $\\pi$ מוגדר באופן יסודי כיחס בין היקף מעגל לקוטרו. שזה קבוע (אינו תלוי במעגל) נובע מהדמיון בין כל המעגלים. ההיקף הוא $\\pi \\cdot d = 2\\pi r$. השטח $\\pi r^2$ מוכח באמצעות אינטגרציה (גזרת $\\frac{1}{2}r^2 d\\theta$). $\\blacksquare$",
      method="axiom"),

    # ── Number theory ──
    P("prf_perfect_mersenne_correspondence", "thm_perfect_mersenne_correspondence",
      ["def_perfect_number", "def_mersenne_prime", "def_sigma_function"],
      "**אוקלידס:** אם $2^p - 1$ ראשוני, $n = 2^{p-1}(2^p - 1)$ מקיים $\\sigma(n) = (2^p - 1) \\cdot 2^p = 2n$ (משתמשים בכך ש-$\\sigma$ מולטיפליקטיבית עבור גורמים זרים). אז $n$ מושלם.\n\n**אוילר (כיוון הפוך):** מראים שמושלם זוגי חייב להיות בצורה זו ע״י ניתוח גורמי $2$ ובדיקת תנאי $\\sigma(n) = 2n$. $\\blacksquare$",
      method="axiom"),
    P("prf_prime_number_theorem", "thm_prime_number_theorem",
      ["def_prime_counting_function", "def_prime"],
      "**משפט עומק באנליזה.** הוכח על-ידי הדמרד ופוסן (1896) בלתי-תלוי. הוכחה מודרנית קצרה (סלברג, אנילה) מ-1949.\n\nההוכחה משתמשת בפונקציית זטא של רימן $\\zeta(s)$ והקשר שלה לראשוניים, וכן בתכונות אנליטיות עמוקות. אינה בהישג יד לרמת תיכון. $\\blacksquare$",
      method="axiom"),

    # ── Euler & complex ──
    P("prf_euler_formula", "thm_euler_formula",
      ["thm_maclaurin_exp", "thm_maclaurin_sin", "thm_maclaurin_cos",
       "def_imaginary_unit"],
      "מטור מקלורין של $e^x$: $e^{i\\theta} = \\sum \\frac{(i\\theta)^n}{n!}$. חזקות $i$: $i^0=1, i^1=i, i^2=-1, i^3=-i$, מחזור 4.\n\nהפרדה לפי זוגיות: איברים זוגיים (חזקות $i^{2k} = (-1)^k$) → $\\sum \\frac{(-1)^k \\theta^{2k}}{(2k)!} = \\cos\\theta$. איברים אי-זוגיים → $i \\sum \\frac{(-1)^k \\theta^{2k+1}}{(2k+1)!} = i \\sin\\theta$.\n\nסכום: $e^{i\\theta} = \\cos\\theta + i \\sin\\theta$. $\\blacksquare$"),
    P("prf_power_reducing_sin_squared", "thm_power_reducing_sin_squared",
      ["thm_cos_double_angle"],
      "מ-$\\cos(2x) = 1 - 2\\sin^2 x$: $\\sin^2 x = \\frac{1 - \\cos(2x)}{2}$. $\\blacksquare$"),
    P("prf_power_reducing_cos_squared", "thm_power_reducing_cos_squared",
      ["thm_cos_double_angle"],
      "מ-$\\cos(2x) = 2\\cos^2 x - 1$: $\\cos^2 x = \\frac{1 + \\cos(2x)}{2}$. $\\blacksquare$"),
    P("prf_nth_roots_of_complex", "thm_nth_roots_of_complex",
      ["thm_euler_formula", "thm_de_moivre"],
      "פתרון $w^n = z = r e^{i\\theta}$: נסמן $w = \\rho e^{i\\phi}$. אז $\\rho^n e^{in\\phi} = r e^{i\\theta}$. \n\n$\\rho = r^{1/n}$, $n\\phi = \\theta + 2\\pi k$, אז $\\phi = (\\theta + 2\\pi k)/n$. $k = 0, 1, \\ldots, n-1$ נותן $n$ שורשים שונים. $\\blacksquare$"),
    P("prf_sum_of_nth_roots_unity", "thm_sum_of_nth_roots_unity",
      ["thm_nth_roots_of_complex", "thm_geometric_sum_finite"],
      "שורשי היחידה $\\omega_k = e^{2\\pi i k / n}$ הם $1, \\omega, \\omega^2, \\ldots, \\omega^{n-1}$ עם $\\omega = e^{2\\pi i / n}$.\n\nסכום: $\\sum \\omega^k = \\frac{\\omega^n - 1}{\\omega - 1} = \\frac{1 - 1}{\\omega - 1} = 0$ (כש-$\\omega \\neq 1$). $\\blacksquare$"),
    P("prf_arctan_sum_identity", "thm_arctan_sum_identity",
      ["def_arctan", "thm_tan_addition_formula"],
      "עבור $x > 0$: נסמן $\\alpha = \\arctan x$, $\\beta = \\arctan(1/x)$. שניהם בקטע $(0, \\pi/2)$.\n\n$\\tan(\\alpha + \\beta) = \\frac{x + 1/x}{1 - 1} = \\frac{x + 1/x}{0}$ — אינסופי. לכן $\\alpha + \\beta = \\pi/2$. עבור $x < 0$ — הסימן הפוך, ומקבלים $-\\pi/2$. $\\blacksquare$"),

    # ── Series & sequences ──
    P("prf_fibonacci_binet_formula", "thm_fibonacci_binet_formula",
      ["thm_linear_recurrence_characteristic", "def_recurrence_relation"],
      "פיבונאצ׳י: $F_{n+1} = F_n + F_{n-1}$, $F_0=0, F_1=1$.\n\nמשוואה אופיינית $x^2 = x + 1$, שורשים $\\varphi = (1+\\sqrt 5)/2$, $\\psi = (1-\\sqrt 5)/2$.\n\nפתרון כללי $F_n = A\\varphi^n + B\\psi^n$. מתנאי התחלה: $A = 1/\\sqrt 5$, $B = -1/\\sqrt 5$. אז $F_n = \\frac{\\varphi^n - \\psi^n}{\\sqrt 5}$. $\\blacksquare$"),
    P("prf_linear_recurrence_characteristic", "thm_linear_recurrence_characteristic",
      ["def_recurrence_relation"],
      "מציבים $a_n = r^n$ במשוואה: $r^{n+1} = c_1 r^n + c_2 r^{n-1}$, חלוקה ב-$r^{n-1}$: $r^2 = c_1 r + c_2$.\n\nאם $r_1, r_2$ שורשים שונים, כל צירוף $A r_1^n + B r_2^n$ מקיים. הקבועים $A, B$ נקבעים מתנאי התחלה. $\\blacksquare$"),

    # ── Probability ──
    P("prf_geometric_distribution_mean", "thm_geometric_distribution_mean",
      ["def_geometric_distribution", "def_expected_value",
       "thm_maclaurin_geometric"],
      "$E[X] = \\sum_{k=1}^{\\infty} k (1-p)^{k-1} p = p \\sum k q^{k-1}$ (עם $q = 1-p$).\n\n$\\sum_{k=1}^{\\infty} k q^{k-1} = \\frac{1}{(1-q)^2} = \\frac{1}{p^2}$ (גזירה של הטור הגיאומטרי). לכן $E[X] = \\frac{p}{p^2} = \\frac{1}{p}$. $\\blacksquare$"),
    P("prf_least_squares_linear", "thm_least_squares_linear",
      ["def_expected_value", "thm_fermat_extremum"],
      "מינימום $S(a, b) = \\sum(y_i - ax_i - b)^2$ בעזרת נגזרות חלקיות:\n\n$\\partial S/\\partial b = -2 \\sum(y_i - ax_i - b) = 0 \\Rightarrow b = \\bar y - a \\bar x$.\n\n$\\partial S/\\partial a = -2 \\sum x_i(y_i - ax_i - b) = 0$, הצבה של $b$ ופתרון: $a = \\frac{\\sum(x_i - \\bar x)(y_i - \\bar y)}{\\sum(x_i - \\bar x)^2}$. $\\blacksquare$"),
    P("prf_chebyshev_inequality_prob", "thm_chebyshev_inequality_prob",
      ["def_variance_rv", "def_expected_value"],
      "$\\sigma^2 = E[(X - \\mu)^2] \\geq E[(X - \\mu)^2 \\cdot \\mathbb{1}_{|X-\\mu| \\geq k\\sigma}] \\geq (k\\sigma)^2 \\cdot P(|X - \\mu| \\geq k\\sigma)$.\n\nחלוקה ב-$\\sigma^2 k^2$: $P(|X - \\mu| \\geq k\\sigma) \\leq \\frac{1}{k^2}$. $\\blacksquare$"),
    P("prf_binomial_normal_approximation", "thm_binomial_normal_approximation",
      ["def_binomial_distribution", "thm_central_limit_theorem_intuitive",
       "def_normal_distribution"],
      "$\\text{Bin}(n, p)$ היא סכום של $n$ ברנולים בלתי-תלויים. לפי משפט הגבול המרכזי, סכום נטוי לנורמלית כש-$n \\to \\infty$.\n\nעם תוחלת $np$ ושונות $np(1-p)$, $X \\approx N(np, np(1-p))$. $\\blacksquare$"),

    # ── Vectors ──
    P("prf_cross_product_anticommutative", "thm_cross_product_anticommutative",
      ["def_cross_product"],
      "$\\vec{v} \\times \\vec{u} = (v_2 u_3 - v_3 u_2, v_3 u_1 - v_1 u_3, v_1 u_2 - v_2 u_1)$.\n\nלעומת $\\vec{u} \\times \\vec{v} = (u_2 v_3 - u_3 v_2, u_3 v_1 - u_1 v_3, u_1 v_2 - u_2 v_1)$.\n\nכל רכיב הפוך בסימן, אז $\\vec{v} \\times \\vec{u} = -(\\vec{u} \\times \\vec{v})$. $\\blacksquare$"),
    P("prf_parallelogram_area_cross", "thm_parallelogram_area_cross",
      ["thm_cross_product_magnitude", "thm_triangle_area_cross_product"],
      "שטח מקבילית = פעמיים שטח משולש מצלעות הוקטור. $|\\vec{u} \\times \\vec{v}|$ הוא בדיוק שטח המקבילית (כפול שטח המשולש). $\\blacksquare$"),

    # ── Inequalities ──
    P("prf_am_hm_inequality", "thm_am_hm_inequality",
      ["thm_am_gm_n_variables"],
      "מ-AM-GM על $a_1, \\ldots, a_n$: $\\frac{\\sum a_i}{n} \\geq \\sqrt[n]{\\prod a_i}$.\n\nומ-AM-GM על $1/a_1, \\ldots, 1/a_n$: $\\frac{\\sum 1/a_i}{n} \\geq \\sqrt[n]{1/\\prod a_i} = 1/\\sqrt[n]{\\prod a_i}$.\n\nחילוק/הפיכה: $\\frac{n}{\\sum 1/a_i} \\leq \\sqrt[n]{\\prod a_i} \\leq \\frac{\\sum a_i}{n}$. כלומר AM ≥ GM ≥ HM. $\\blacksquare$"),
    P("prf_gm_hm_inequality", "thm_gm_hm_inequality",
      ["thm_am_gm_n_variables"],
      "מ-AM-GM על ההפכיים: $\\frac{\\sum 1/a_i}{n} \\geq \\sqrt[n]{\\prod 1/a_i} = 1/\\sqrt[n]{\\prod a_i}$. הפיכה: GM $\\geq$ HM. $\\blacksquare$"),
    P("prf_bernoulli_inequality", "thm_bernoulli_inequality",
      ["def_proof_by_induction"],
      "**אינדוקציה על $n$.** בסיס $n=1$: $(1+x)^1 = 1 + x$. ✓\n\nצעד: $(1+x)^{n+1} = (1+x)(1+x)^n \\geq (1+x)(1 + nx) = 1 + (n+1)x + nx^2 \\geq 1 + (n+1)x$ (כי $nx^2 \\geq 0$ ו-$1 + x \\geq 0$). $\\blacksquare$"),
    P("prf_qm_am_inequality", "thm_qm_am_inequality",
      ["thm_squared_inequality", "thm_cauchy_schwarz_inequality_vectors"],
      "מ-קושי-שוורץ: $(\\sum a_i \\cdot 1)^2 \\leq (\\sum a_i^2)(\\sum 1^2) = n \\sum a_i^2$.\n\nלכן $\\left(\\frac{\\sum a_i}{n}\\right)^2 \\leq \\frac{\\sum a_i^2}{n}$, ובשורש: AM $\\leq$ QM. $\\blacksquare$"),

    # ── Calc apps ──
    P("prf_cauchy_mean_value", "thm_cauchy_mean_value",
      ["thm_rolle_theorem", "thm_derivative_sum"],
      "**הוכחה.** נגדיר $h(x) := f(x)[g(b) - g(a)] - g(x)[f(b) - f(a)]$.\n\nאז $h(a) = h(b) = f(a) g(b) - g(a) f(b)$ (קלכלילה ישירה).\n\nלפי רול קיים $c$ עם $h'(c) = 0$: $f'(c)[g(b)-g(a)] = g'(c)[f(b)-f(a)]$, וחלוקה ב-$g'(c)[g(b)-g(a)]$ נותנת את המסקנה. $\\blacksquare$"),
    P("prf_taylor_remainder_lagrange", "thm_taylor_remainder_lagrange",
      ["thm_cauchy_mean_value", "def_higher_order_derivative"],
      "**הוכחה.** נגדיר $R_n(x) = f(x) - P_n(x)$, כאשר $P_n$ פולינום טיילור מסדר $n$. $R_n$ ו-$(x-a)^{n+1}$ מתאפסים $n+1$ פעמים ב-$a$.\n\nשימוש חוזר במשפט קושי לערך הממוצע: $\\frac{R_n(x)}{(x-a)^{n+1}} = \\frac{R_n^{(n+1)}(\\xi)}{(n+1)!} = \\frac{f^{(n+1)}(\\xi)}{(n+1)!}$. $\\blacksquare$"),
    P("prf_descartes_rule_of_signs", "thm_descartes_rule_of_signs",
      ["def_polynomial", "thm_factor_theorem"],
      "**הוכחה (אינדוקטיבית).** אינדוקציה על דרגת הפולינום. נשתמש בכך שגורמי $(x - r)$ עבור $r > 0$ משפיעים על מספר שינויי הסימן בדרך מסוימת: חלוקה ב-$(x - r)$ מפחיתה את מספר שינויי הסימן באי-זוגי. $\\blacksquare$",
      method="axiom"),
    P("prf_fundamental_theorem_of_algebra", "thm_fundamental_theorem_of_algebra",
      ["def_polynomial"],
      "**משפט עמוק (גאוס).** הוכחה אנליטית: נניח $p(z) \\neq 0$ לכל $z$. אז $1/p(z)$ פונקציה אנליטית וחסומה (כי $|p| \\to \\infty$ בתוואי), אז קבועה לפי משפט ליוויל. סתירה לכך ש-$p$ אינו קבוע.\n\nההוכחה דורשת מנגנון של אנליזה מרוכבת. $\\blacksquare$",
      method="axiom"),
    P("prf_angle_bisector_length", "thm_angle_bisector_length",
      ["thm_stewart_theorem", "thm_angle_bisectors_concur"],
      "**הוכחה (סטיוארט + חוצה זווית).** חוצה זווית $A$ פוגע ב-$BC$ ב-$D$ עם $BD/DC = c/b$ (משפט חוצה זווית). מכאן $BD = ac/(b+c)$, $DC = ab/(b+c)$.\n\nהצבה במשפט סטיוארט עם $m = BD$, $n = DC$, $d = t_a$:\n\n$b^2 \\cdot \\frac{ac}{b+c} + c^2 \\cdot \\frac{ab}{b+c} - a t_a^2 = a \\cdot \\frac{a^2 bc}{(b+c)^2}$\n\nסידור: $abc(b+c)/(b+c) = abc$, ולכן $t_a^2 = bc - \\frac{a^2 bc}{(b+c)^2} = bc(1 - \\frac{a^2}{(b+c)^2})$. $\\blacksquare$"),
    P("prf_de_moivre_for_roots", "thm_de_moivre_for_roots",
      ["thm_de_moivre", "thm_nth_roots_of_complex"],
      "מנוסחת אוילר $z = r e^{i\\theta}$, ניתן לכתוב $z^{1/n} = r^{1/n} e^{i(\\theta + 2\\pi k)/n}$.\n\nבצורה טריגונומטרית: $z^{1/n} = r^{1/n}\\!\\left(\\cos\\frac{\\theta + 2\\pi k}{n} + i \\sin\\frac{\\theta + 2\\pi k}{n}\\right)$, עבור $k = 0, 1, \\ldots, n-1$. $\\blacksquare$"),
    P("prf_lhopital_for_all_forms", "thm_lhopital_for_all_forms",
      ["thm_l_hopital_intuitive", "def_indeterminate_form"],
      "**גישה אלגברית להקטנת צורות:**\n\n$0 \\cdot \\infty$: $f \\cdot g = f/(1/g)$ או $g/(1/f)$ — צורת $\\frac{0}{0}$ או $\\frac{\\infty}{\\infty}$.\n\n$\\infty - \\infty$: מוצאים מכנה משותף או מוציאים גורם.\n\n$1^\\infty, 0^0, \\infty^0$: לוקחים לוגריתם — $\\ln(f^g) = g \\ln f$, מקבלים $0 \\cdot \\infty$, ממשיכים כנ\"ל. $\\blacksquare$"),
    P("prf_power_mean_inequality", "thm_power_mean_inequality",
      ["thm_jensen_inequality", "def_convex_function"],
      "**הוכחה (לפי ינסן).** הפונקציה $f(x) = x^{r/s}$ קמורה עבור $r/s > 1$. הפעלת ינסן על $a_i^s/n$ נותנת $\\left(\\frac{\\sum a_i^s}{n}\\right)^{r/s} \\leq \\frac{\\sum a_i^r}{n}$.\n\nהוצאת שורש $r$ מקבילי $s$: $M_s \\leq M_r$. $\\blacksquare$",
      method="axiom"),
    P("prf_ratio_test_radius", "thm_ratio_test_radius",
      ["thm_ratio_test", "def_radius_of_convergence"],
      "מבחן המנה על הטור $\\sum a_n x^n$: $\\lim |a_{n+1} x^{n+1} / (a_n x^n)| = |x| \\lim |a_{n+1}/a_n|$.\n\nמתכנס כש $|x| \\lim |a_{n+1}/a_n| < 1$, כלומר $|x| < 1/\\lim |a_{n+1}/a_n| = \\lim |a_n/a_{n+1}|$. וזה $R$. $\\blacksquare$"),
    P("prf_rearrangement_inequality", "thm_rearrangement_inequality",
      ["def_permutation"],
      "**הוכחה ע״י החלפה.** נניח $\\sigma$ אינו זהות, אז קיימים $i < j$ עם $\\sigma(i) > \\sigma(j)$. החלפת ערכי $\\sigma$ ב-$i, j$ משנה את הסכום ב: $a_i (b_{\\sigma(j)} - b_{\\sigma(i)}) + a_j (b_{\\sigma(i)} - b_{\\sigma(j)}) = (a_j - a_i)(b_{\\sigma(i)} - b_{\\sigma(j)}) \\geq 0$.\n\nכלומר ההחלפה לסידור עולה מגדילה (או שומרת) את הסכום. $\\blacksquare$"),
]
