"""Chunk 6 — 100 claims: full calculus core (limits, derivatives, integrals),
   vectors, complex numbers — the 5-unit matriculation backbone.
"""
from __future__ import annotations

from core.models import Claim, Course, Proof


CANON = "canonical"


def C(cid, kind, course, topic, stmt):
    return Claim(id=cid, kind=kind, status=CANON, course=course,
                 topic=topic, statement=stmt)


def P(pid, cid, deps, body, method="informal", status="reviewed", canonical=True):
    return Proof(id=pid, claim_id=cid, dependencies=list(deps), body=body,
                 method=method, status=status, is_canonical=canonical)


HS4 = "math_hs_4"
HS5 = "math_hs_5"


COURSES = [
    Course(id=HS5, name="מתמטיקה תיכון 5 יחל",
           prerequisites=["math_hs_4"]),
]


CLAIMS = [
    # ═══ Limits (foundation for derivatives) — HS4 ═══
    C("def_function_limit_formal", "definition", HS4, "גבולות",
      r"**הגדרת גבול פונקציה (אפסילון-דלתא):** $\lim_{x \to x_0} f(x) = L$ אם לכל $\epsilon > 0$ קיים $\delta > 0$ כך שלכל $x$ עם $0 < |x - x_0| < \delta$ מתקיים $|f(x) - L| < \epsilon$."),
    C("def_one_sided_limit_right", "definition", HS4, "גבולות",
      r"**גבול חד-צדדי מימין:** $\lim_{x \to x_0^+} f(x) = L$ אם לכל $\epsilon > 0$ קיים $\delta > 0$ כך שלכל $x$ עם $x_0 < x < x_0 + \delta$ מתקיים $|f(x) - L| < \epsilon$."),
    C("def_one_sided_limit_left", "definition", HS4, "גבולות",
      r"**גבול חד-צדדי משמאל:** $\lim_{x \to x_0^-} f(x) = L$ באופן סימטרי, עבור $x_0 - \delta < x < x_0$."),
    C("def_continuity_at_point", "definition", HS4, "גבולות",
      r"**רציפות בנקודה:** $f$ רציפה ב-$x_0$ אם $\lim_{x \to x_0} f(x) = f(x_0)$ (הגבול קיים ושווה לערך הפונקציה)."),
    C("def_continuity_on_interval", "definition", HS4, "גבולות",
      r"**רציפות בקטע:** $f$ רציפה בקטע $I$ אם היא רציפה בכל נקודה $x_0 \in I$."),
    C("thm_limit_constant", "theorem", HS4, "גבולות",
      r"**גבול קבוע:** $\lim_{x \to x_0} c = c$ עבור כל קבוע $c$."),
    C("thm_limit_identity", "theorem", HS4, "גבולות",
      r"**גבול $x$:** $\lim_{x \to x_0} x = x_0$."),
    C("thm_limit_sum", "theorem", HS4, "גבולות",
      r"**גבול של סכום:** אם $\lim_{x \to x_0} f(x) = L$ ו-$\lim_{x \to x_0} g(x) = M$, אז $\lim_{x \to x_0} (f + g)(x) = L + M$."),
    C("thm_limit_product", "theorem", HS4, "גבולות",
      r"**גבול של מכפלה:** באותם תנאים, $\lim_{x \to x_0} (f \cdot g)(x) = L \cdot M$."),
    C("thm_limit_quotient", "theorem", HS4, "גבולות",
      r"**גבול של מנה:** באותם תנאים, אם $M \neq 0$, אז $\lim_{x \to x_0} \frac{f(x)}{g(x)} = \frac{L}{M}$."),
    C("thm_limit_polynomial_continuous", "theorem", HS4, "גבולות",
      r"**פולינומים רציפים:** כל פולינום $p(x)$ רציף בכל $x_0 \in \mathbb{R}$, ובפרט $\lim_{x \to x_0} p(x) = p(x_0)$."),
    C("thm_limit_composition", "theorem", HS4, "גבולות",
      r"**גבול של הרכבה:** אם $\lim_{x \to x_0} g(x) = M$ ו-$f$ רציפה ב-$M$, אז $\lim_{x \to x_0} f(g(x)) = f(M)$."),
    C("thm_limit_sin_over_x", "theorem", HS4, "גבולות",
      r"**הגבול היסודי של סינוס:** $\lim_{x \to 0} \frac{\sin x}{x} = 1$."),
    C("thm_limit_one_plus_inv_n_to_e", "theorem", HS4, "גבולות",
      r"**הגדרת $e$ כגבול:** $e := \lim_{n \to \infty} \left(1 + \frac{1}{n}\right)^n$."),
    C("thm_l_hopital_intuitive", "theorem", HS4, "גבולות",
      r"**כלל לופיטל (אינטואיטיבי):** אם $\lim \frac{f(x)}{g(x)}$ הוא צורה $\frac{0}{0}$ או $\frac{\infty}{\infty}$, ו-$f, g$ גזירות עם $g'(x) \neq 0$, אז $\lim \frac{f(x)}{g(x)} = \lim \frac{f'(x)}{g'(x)}$ (אם הגבול האחרון קיים)."),

    # ═══ Derivatives — HS5 ═══
    C("def_derivative_at_point", "definition", HS5, "נגזרות",
      r"**נגזרת בנקודה:** $f'(x_0) := \lim_{h \to 0} \frac{f(x_0 + h) - f(x_0)}{h}$ (אם הגבול קיים)."),
    C("def_derivative_function", "definition", HS5, "נגזרות",
      r"**פונקציית הנגזרת:** $f': x \mapsto f'(x)$ — הפונקציה המתאימה לכל $x$ שבו $f$ גזירה את הנגזרת שלה באותה נקודה."),
    C("def_differentiable_function", "definition", HS5, "נגזרות",
      r"**גזירה:** פונקציה $f$ נקראת **גזירה** ב-$x_0$ אם הגבול $\lim_{h \to 0} \frac{f(x_0 + h) - f(x_0)}{h}$ קיים."),
    C("thm_differentiable_implies_continuous", "theorem", HS5, "נגזרות",
      r"**גזירות גוררת רציפות:** אם $f$ גזירה ב-$x_0$ אז $f$ רציפה ב-$x_0$. (הכיוון ההפוך לא מתקיים — דוגמה: $|x|$ ב-$0$.)"),
    C("thm_derivative_constant", "theorem", HS5, "כללי גזירה",
      r"**נגזרת קבוע:** $(c)' = 0$ לכל קבוע $c$."),
    C("thm_derivative_x", "theorem", HS5, "כללי גזירה",
      r"**נגזרת $x$:** $(x)' = 1$."),
    C("thm_derivative_power", "theorem", HS5, "כללי גזירה",
      r"**נגזרת חזקה:** $\left(x^n\right)' = n \cdot x^{n-1}$ לכל $n \in \mathbb{R}$ (כאשר הביטוי מוגדר)."),
    C("thm_derivative_sum", "theorem", HS5, "כללי גזירה",
      r"**נגזרת סכום:** $(f + g)'(x) = f'(x) + g'(x)$."),
    C("thm_derivative_constant_multiple", "theorem", HS5, "כללי גזירה",
      r"**נגזרת כפל בקבוע:** $(c \cdot f)'(x) = c \cdot f'(x)$."),
    C("thm_derivative_product", "theorem", HS5, "כללי גזירה",
      r"**נגזרת מכפלה (לייבניץ):** $(f \cdot g)'(x) = f'(x) g(x) + f(x) g'(x)$."),
    C("thm_derivative_quotient", "theorem", HS5, "כללי גזירה",
      r"**נגזרת מנה:** $\left(\frac{f}{g}\right)'(x) = \frac{f'(x) g(x) - f(x) g'(x)}{g(x)^2}$ (כש-$g(x) \neq 0$)."),
    C("thm_derivative_chain", "theorem", HS5, "כללי גזירה",
      r"**כלל השרשרת:** אם $h(x) = f(g(x))$, אז $h'(x) = f'(g(x)) \cdot g'(x)$."),
    C("thm_derivative_inverse_function", "theorem", HS5, "כללי גזירה",
      r"**נגזרת פונקציה הפוכה:** אם $f$ גזירה והפיכה, $f^{-1}$ גזירה ו-$\left(f^{-1}\right)'(y) = \frac{1}{f'(f^{-1}(y))}$."),
    C("thm_derivative_sin", "theorem", HS5, "נגזרות פונקציות",
      r"**נגזרת סינוס:** $(\sin x)' = \cos x$."),
    C("thm_derivative_cos", "theorem", HS5, "נגזרות פונקציות",
      r"**נגזרת קוסינוס:** $(\cos x)' = -\sin x$."),
    C("thm_derivative_tan", "theorem", HS5, "נגזרות פונקציות",
      r"**נגזרת טנגנס:** $(\tan x)' = \frac{1}{\cos^2 x} = \sec^2 x$."),
    C("thm_derivative_exp", "theorem", HS5, "נגזרות פונקציות",
      r"**נגזרת $e^x$:** $(e^x)' = e^x$."),
    C("thm_derivative_log_natural", "theorem", HS5, "נגזרות פונקציות",
      r"**נגזרת לוגריתם טבעי:** $(\ln x)' = \frac{1}{x}$ עבור $x > 0$."),
    C("thm_derivative_a_to_x", "theorem", HS5, "נגזרות פונקציות",
      r"**נגזרת מעריכית כללית:** $(a^x)' = a^x \cdot \ln a$ עבור $a > 0$."),
    C("thm_derivative_log_general", "theorem", HS5, "נגזרות פונקציות",
      r"**נגזרת לוגריתם כללי:** $(\log_a x)' = \frac{1}{x \cdot \ln a}$ עבור $a > 0, a \neq 1$."),

    # ═══ Applications of derivatives — HS5 ═══
    C("def_critical_point", "definition", HS5, "יישומי נגזרת",
      r"**נקודה חשודה לקיצון (קריטית):** $x_0$ נקראת **נקודה חשודה** של $f$ אם $f'(x_0) = 0$ או $f$ אינה גזירה ב-$x_0$."),
    C("thm_fermat_extremum", "theorem", HS5, "יישומי נגזרת",
      r"**משפט פרמה (תנאי הכרחי לקיצון):** אם ל-$f$ ערך קיצון מקומי ב-$x_0$ פנימית בתחום, ו-$f$ גזירה ב-$x_0$, אז $f'(x_0) = 0$."),
    C("thm_rolle_theorem", "theorem", HS5, "יישומי נגזרת",
      r"**משפט רול:** אם $f$ רציפה ב-$[a, b]$, גזירה ב-$(a, b)$, ו-$f(a) = f(b)$, אז קיים $c \in (a, b)$ עם $f'(c) = 0$."),
    C("thm_mean_value_theorem", "theorem", HS5, "יישומי נגזרת",
      r"**משפט הערך הממוצע (לגראנז׳):** אם $f$ רציפה ב-$[a, b]$ וגזירה ב-$(a, b)$, אז קיים $c \in (a, b)$ עם $f'(c) = \frac{f(b) - f(a)}{b - a}$."),
    C("thm_increasing_test", "theorem", HS5, "יישומי נגזרת",
      r"**מבחן עלייה:** אם $f'(x) > 0$ בקטע $I$, אז $f$ עולה ממש ב-$I$."),
    C("thm_decreasing_test", "theorem", HS5, "יישומי נגזרת",
      r"**מבחן ירידה:** אם $f'(x) < 0$ בקטע $I$, אז $f$ יורדת ממש ב-$I$."),
    C("def_second_derivative", "definition", HS5, "יישומי נגזרת",
      r"**נגזרת שנייה:** $f''(x) := (f')'(x)$ — הנגזרת של פונקציית הנגזרת."),
    C("thm_concavity_second_derivative", "theorem", HS5, "יישומי נגזרת",
      r"**קעירות לפי נגזרת שנייה:** אם $f''(x) > 0$ בקטע, $f$ קעורה כלפי מעלה שם. אם $f''(x) < 0$, קעורה כלפי מטה."),
    C("def_inflection_point", "definition", HS5, "יישומי נגזרת",
      r"**נקודת פיתול:** נקודה שבה הקעירות של הפונקציה משתנה (מקעורה כלפי מעלה לקעורה כלפי מטה או להפך)."),
    C("thm_first_derivative_test", "theorem", HS5, "יישומי נגזרת",
      r"**מבחן הנגזרת הראשונה:** אם $f'$ משנה סימן מ-$+$ ל-$-$ ב-$x_0$, אז ל-$f$ מקסימום מקומי שם. שינוי מ-$-$ ל-$+$ — מינימום מקומי."),
    C("thm_second_derivative_test", "theorem", HS5, "יישומי נגזרת",
      r"**מבחן הנגזרת השנייה:** אם $f'(x_0) = 0$ ו-$f''(x_0) > 0$, אז $x_0$ מינימום מקומי. אם $f''(x_0) < 0$, מקסימום מקומי."),
    C("thm_tangent_line_equation", "theorem", HS5, "יישומי נגזרת",
      r"**משוואת המשיק לגרף:** המשיק לגרף $f$ בנקודה $(x_0, f(x_0))$ ניתן ע״י $y - f(x_0) = f'(x_0) \cdot (x - x_0)$."),
    C("def_normal_line", "definition", HS5, "יישומי נגזרת",
      r"**נורמל לגרף:** הישר העובר בנקודה $(x_0, f(x_0))$ ומאונך למשיק שם. שיפועו $-\frac{1}{f'(x_0)}$ (כש-$f'(x_0) \neq 0$)."),
    C("thm_extreme_value_theorem", "theorem", HS5, "יישומי נגזרת",
      r"**משפט ויירשטראס לערכי קיצון:** פונקציה רציפה בקטע סגור $[a, b]$ מקבלת בו את מקסימום המוחלט ואת המינימום המוחלט."),

    # ═══ Integrals — HS5 ═══
    C("def_antiderivative", "definition", HS5, "אינטגרלים",
      r"**פונקציה קדומה:** $F$ נקראת **פונקציה קדומה** של $f$ אם $F'(x) = f(x)$ בכל $x$ בתחום."),
    C("def_indefinite_integral", "definition", HS5, "אינטגרלים",
      r"**אינטגרל בלתי מסוים:** $\int f(x) \, dx := F(x) + C$ כאשר $F$ פונקציה קדומה כלשהי של $f$ ו-$C \in \mathbb{R}$ קבוע אינטגרציה."),
    C("thm_antiderivative_differ_by_constant", "theorem", HS5, "אינטגרלים",
      r"**יחידות פונקציה קדומה עד כדי קבוע:** אם $F_1, F_2$ קדומות של $f$ באותו קטע, אז $F_1 - F_2$ קבוע."),
    C("thm_integral_constant_multiple", "theorem", HS5, "אינטגרלים",
      r"**אינטגרל של כפל בקבוע:** $\int c \cdot f(x) \, dx = c \int f(x) \, dx$."),
    C("thm_integral_sum", "theorem", HS5, "אינטגרלים",
      r"**אינטגרל של סכום:** $\int (f(x) + g(x)) \, dx = \int f(x) \, dx + \int g(x) \, dx$."),
    C("thm_integral_power", "theorem", HS5, "אינטגרלים",
      r"**אינטגרל חזקה:** $\int x^n \, dx = \frac{x^{n+1}}{n+1} + C$ עבור $n \neq -1$."),
    C("thm_integral_one_over_x", "theorem", HS5, "אינטגרלים",
      r"**אינטגרל $\frac{1}{x}$:** $\int \frac{1}{x} \, dx = \ln|x| + C$."),
    C("thm_integral_exp", "theorem", HS5, "אינטגרלים",
      r"**אינטגרל $e^x$:** $\int e^x \, dx = e^x + C$."),
    C("thm_integral_sin", "theorem", HS5, "אינטגרלים",
      r"**אינטגרל סינוס:** $\int \sin x \, dx = -\cos x + C$."),
    C("thm_integral_cos", "theorem", HS5, "אינטגרלים",
      r"**אינטגרל קוסינוס:** $\int \cos x \, dx = \sin x + C$."),
    C("thm_integral_substitution", "theorem", HS5, "אינטגרלים",
      r"**אינטגרציה בהצבה:** $\int f(g(x)) \cdot g'(x) \, dx = \int f(u) \, du$ (כאשר $u = g(x)$, $du = g'(x) dx$)."),
    C("thm_integral_by_parts", "theorem", HS5, "אינטגרלים",
      r"**אינטגרציה בחלקים:** $\int u \, dv = u \cdot v - \int v \, du$, או באופן שקול $\int f(x) g'(x) \, dx = f(x) g(x) - \int f'(x) g(x) \, dx$."),

    # ═══ Definite integrals — HS5 ═══
    C("def_riemann_sum", "definition", HS5, "אינטגרל מסוים",
      r"**סכום רימן:** עבור חלוקה $a = x_0 < x_1 < \cdots < x_n = b$ ובחירת נקודות $\xi_i \in [x_{i-1}, x_i]$, סכום רימן הוא $\sum_{i=1}^n f(\xi_i)(x_i - x_{i-1})$."),
    C("def_definite_integral", "definition", HS5, "אינטגרל מסוים",
      r"**אינטגרל מסוים:** $\int_a^b f(x) \, dx := \lim_{n \to \infty} \sum_{i=1}^n f(\xi_i) \Delta x_i$, כאשר $\Delta x_i \to 0$ (הגבול של סכומי רימן, אם קיים)."),
    C("thm_definite_integral_linearity", "theorem", HS5, "אינטגרל מסוים",
      r"**לינאריות האינטגרל המסוים:** $\int_a^b (\alpha f + \beta g) \, dx = \alpha \int_a^b f \, dx + \beta \int_a^b g \, dx$."),
    C("thm_definite_integral_additivity", "theorem", HS5, "אינטגרל מסוים",
      r"**אדיטיביות לפי קטעים:** $\int_a^b f \, dx + \int_b^c f \, dx = \int_a^c f \, dx$ (עבור $a \leq b \leq c$)."),
    C("thm_definite_integral_reversed", "theorem", HS5, "אינטגרל מסוים",
      r"**היפוך גבולות:** $\int_a^b f \, dx = -\int_b^a f \, dx$."),
    C("thm_definite_integral_zero_width", "theorem", HS5, "אינטגרל מסוים",
      r"**רוחב אפס:** $\int_a^a f \, dx = 0$."),
    C("thm_ftc_part1", "theorem", HS5, "אינטגרל מסוים",
      r"**המשפט היסודי של החדו״א — חלק ראשון:** אם $f$ רציפה ב-$[a, b]$, אז $F(x) := \int_a^x f(t) \, dt$ גזירה ו-$F'(x) = f(x)$."),
    C("thm_ftc_part2", "theorem", HS5, "אינטגרל מסוים",
      r"**המשפט היסודי של החדו״א — חלק שני (נוסחת ניוטון-לייבניץ):** אם $F$ קדומה של $f$ רציפה ב-$[a, b]$, אז $\int_a^b f(x) \, dx = F(b) - F(a)$."),

    # ═══ Applications of integration — HS5 ═══
    C("thm_area_under_curve", "theorem", HS5, "יישומי אינטגרל",
      r"**שטח מתחת לעקומה:** עבור $f(x) \geq 0$ ב-$[a, b]$, השטח הכלוא בין הגרף לציר ה-$x$ הוא $\int_a^b f(x) \, dx$."),
    C("thm_area_between_curves", "theorem", HS5, "יישומי אינטגרל",
      r"**שטח בין שני גרפים:** עבור $f(x) \geq g(x)$ ב-$[a, b]$, השטח הכלוא הוא $\int_a^b (f(x) - g(x)) \, dx$."),
    C("def_volume_of_revolution", "definition", HS5, "יישומי אינטגרל",
      r"**גוף סיבוב:** הגוף המתקבל מסיבוב אזור מישורי סביב ציר (לרוב ציר $x$ או $y$)."),
    C("thm_volume_of_revolution_disc", "theorem", HS5, "יישומי אינטגרל",
      r"**נפח גוף סיבוב (שיטת הדיסקים):** עבור סיבוב הגרף $f(x) \geq 0$ ב-$[a, b]$ סביב ציר $x$: $V = \pi \int_a^b f(x)^2 \, dx$."),
    C("def_arc_length", "definition", HS5, "יישומי אינטגרל",
      r"**אורך קשת:** האורך של גרף $f$ בין $a$ ל-$b$."),
    C("thm_arc_length_formula", "theorem", HS5, "יישומי אינטגרל",
      r"**נוסחת אורך קשת:** $L = \int_a^b \sqrt{1 + f'(x)^2} \, dx$."),

    # ═══ Vectors (5 units) ═══
    C("def_vector_2d", "definition", HS5, "וקטורים",
      r"**וקטור דו-מימדי:** איבר ב-$\mathbb{R}^2$, נסמן $\vec{v} = (v_1, v_2)$ או כעמודה $\begin{pmatrix} v_1 \\ v_2 \end{pmatrix}$."),
    C("def_vector_3d", "definition", HS5, "וקטורים",
      r"**וקטור תלת-מימדי:** איבר ב-$\mathbb{R}^3$, $\vec{v} = (v_1, v_2, v_3)$."),
    C("def_vector_addition", "definition", HS5, "וקטורים",
      r"**חיבור וקטורים:** $\vec{u} + \vec{v} = (u_1 + v_1, u_2 + v_2, \ldots)$ — רכיב-רכיב."),
    C("def_scalar_multiplication", "definition", HS5, "וקטורים",
      r"**כפל בסקלר:** $c \cdot \vec{v} = (c v_1, c v_2, \ldots)$ עבור $c \in \mathbb{R}$."),
    C("def_vector_magnitude", "definition", HS5, "וקטורים",
      r"**גודל וקטור (נורמה):** $|\vec{v}| := \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}$ (לפי פיתגורס)."),
    C("def_dot_product", "definition", HS5, "וקטורים",
      r"**מכפלה סקלרית:** $\vec{u} \cdot \vec{v} := u_1 v_1 + u_2 v_2 + \cdots + u_n v_n$."),
    C("thm_dot_product_geometric", "theorem", HS5, "וקטורים",
      r"**מכפלה סקלרית גאומטרית:** $\vec{u} \cdot \vec{v} = |\vec{u}| \cdot |\vec{v}| \cdot \cos\theta$, כאשר $\theta$ הזווית בין הוקטורים."),
    C("def_perpendicular_vectors", "definition", HS5, "וקטורים",
      r"**וקטורים מאונכים:** $\vec{u} \perp \vec{v}$ אם ורק אם $\vec{u} \cdot \vec{v} = 0$ (וקטורים לא אפס)."),
    C("def_parallel_vectors", "definition", HS5, "וקטורים",
      r"**וקטורים מקבילים:** $\vec{u} \parallel \vec{v}$ אם קיים סקלר $t \in \mathbb{R}$ כך ש-$\vec{u} = t \vec{v}$."),
    C("def_unit_vector", "definition", HS5, "וקטורים",
      r"**וקטור יחידה:** וקטור שגודלו $1$. עבור $\vec{v} \neq \vec{0}$, $\hat{v} := \frac{\vec{v}}{|\vec{v}|}$."),

    # ═══ Complex numbers (5 units) ═══
    C("def_imaginary_unit", "definition", HS5, "מספרים מרוכבים",
      r"**יחידה דמיונית:** $i$ הוא מספר המקיים $i^2 = -1$."),
    C("def_complex_number", "definition", HS5, "מספרים מרוכבים",
      r"**מספר מרוכב:** $z = a + b i$ כאשר $a, b \in \mathbb{R}$. $a$ נקרא **חלק ממשי** ($\text{Re}\,z$), $b$ נקרא **חלק דמיוני** ($\text{Im}\,z$)."),
    C("def_complex_conjugate", "definition", HS5, "מספרים מרוכבים",
      r"**צמוד מרוכב:** עבור $z = a + bi$, הצמוד הוא $\bar{z} := a - bi$."),
    C("def_modulus_complex", "definition", HS5, "מספרים מרוכבים",
      r"**ערך מוחלט (מודולוס):** $|z| := \sqrt{a^2 + b^2}$ עבור $z = a + bi$."),
    C("thm_complex_multiplication", "theorem", HS5, "מספרים מרוכבים",
      r"**כפל מרוכבים:** $(a + bi)(c + di) = (ac - bd) + (ad + bc) i$."),
    C("def_polar_form_complex", "definition", HS5, "מספרים מרוכבים",
      r"**צורה פולרית:** $z = r(\cos\theta + i \sin\theta)$ כאשר $r = |z|$ ו-$\theta$ הוא ה**ארגומנט** — הזווית של $z$ במישור המרוכב."),
    C("thm_de_moivre", "theorem", HS5, "מספרים מרוכבים",
      r"**משפט דה-מואבר:** $(\cos\theta + i \sin\theta)^n = \cos(n\theta) + i \sin(n\theta)$ לכל $n \in \mathbb{N}$."),
    C("thm_complex_addition_geometric", "theorem", HS5, "מספרים מרוכבים",
      r"**חיבור מרוכבים (גאומטרי):** חיבור מרוכבים מתאים לחיבור וקטורים במישור (כלל המקבילית)."),
    C("thm_complex_modulus_product", "theorem", HS5, "מספרים מרוכבים",
      r"**מודולוס של מכפלה:** $|z_1 \cdot z_2| = |z_1| \cdot |z_2|$."),
    C("thm_complex_division", "theorem", HS5, "מספרים מרוכבים",
      r"**חילוק מרוכבים:** $\frac{z_1}{z_2} = \frac{z_1 \cdot \bar{z_2}}{|z_2|^2}$ (כש-$z_2 \neq 0$)."),
]


PROOFS = [
    # ── Limits ──
    P("prf_limit_polynomial_continuous", "thm_limit_polynomial_continuous",
      ["thm_limit_constant", "thm_limit_identity", "thm_limit_sum", "thm_limit_product",
       "def_polynomial"],
      "פולינום הוא סכום סופי של איברים מהצורה $a_k x^k$, שכל אחד הוא מכפלה של קבועים ו-$x$.\n\nלכן ניתן לחשב את הגבול שלו לפי כללי גבול של סכום ומכפלה, החל מהגבולות היסודיים $\\lim c = c$ ו-$\\lim x = x_0$. כל אחד מהגבולות החלקיים שווה לערך באותה נקודה, ולכן $\\lim p(x) = p(x_0)$. $\\blacksquare$"),

    # ── Derivatives ──
    P("prf_differentiable_implies_continuous", "thm_differentiable_implies_continuous",
      ["def_derivative_at_point", "def_continuity_at_point",
       "thm_limit_product", "thm_limit_sum"],
      "אם $f$ גזירה ב-$x_0$, אז $\\lim_{h \\to 0} \\frac{f(x_0+h) - f(x_0)}{h} = f'(x_0)$ קיים.\n\n$\\lim_{h \\to 0} (f(x_0+h) - f(x_0)) = \\lim_{h \\to 0} h \\cdot \\frac{f(x_0+h) - f(x_0)}{h} = 0 \\cdot f'(x_0) = 0$.\n\nכלומר $\\lim_{h \\to 0} f(x_0+h) = f(x_0)$, וזו רציפות ב-$x_0$. $\\blacksquare$"),
    P("prf_derivative_constant", "thm_derivative_constant",
      ["def_derivative_at_point"],
      "$(c)' = \\lim_{h \\to 0} \\frac{c - c}{h} = \\lim_{h \\to 0} \\frac{0}{h} = 0$. $\\blacksquare$"),
    P("prf_derivative_x", "thm_derivative_x",
      ["def_derivative_at_point"],
      "$(x)' = \\lim_{h \\to 0} \\frac{(x + h) - x}{h} = \\lim_{h \\to 0} \\frac{h}{h} = 1$. $\\blacksquare$"),
    P("prf_derivative_sum", "thm_derivative_sum",
      ["def_derivative_at_point", "thm_limit_sum"],
      "$(f+g)'(x) = \\lim_{h \\to 0} \\frac{(f+g)(x+h) - (f+g)(x)}{h} = \\lim_{h \\to 0} \\left[\\frac{f(x+h) - f(x)}{h} + \\frac{g(x+h) - g(x)}{h}\\right]$.\n\nלפי גבול של סכום: $= f'(x) + g'(x)$. $\\blacksquare$"),
    P("prf_derivative_constant_multiple", "thm_derivative_constant_multiple",
      ["def_derivative_at_point", "thm_limit_product", "thm_limit_constant"],
      "$(cf)'(x) = \\lim_{h \\to 0} \\frac{c \\cdot f(x+h) - c \\cdot f(x)}{h} = c \\cdot \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h} = c \\cdot f'(x)$. $\\blacksquare$"),
    P("prf_derivative_power", "thm_derivative_power",
      ["def_derivative_at_point", "thm_binomial_theorem", "thm_derivative_constant"],
      "**עבור $n$ טבעי:** $\\frac{(x+h)^n - x^n}{h} = \\frac{\\sum_{k=0}^n \\binom{n}{k} x^{n-k} h^k - x^n}{h} = \\sum_{k=1}^n \\binom{n}{k} x^{n-k} h^{k-1}$ (בינום ניוטון).\n\nכאשר $h \\to 0$, נשארים רק האיברים עם $k = 1$: $\\binom{n}{1} x^{n-1} = n x^{n-1}$. שאר האיברים מכילים $h$ חיובי ושואפים ל-$0$.\n\n**עבור $n$ כללי**: ההכללה נעשית באמצעות לוגריתם ונגזרת לוגריתמית. $\\blacksquare$"),
    P("prf_derivative_product", "thm_derivative_product",
      ["def_derivative_at_point", "thm_differentiable_implies_continuous",
       "thm_limit_sum", "thm_limit_product"],
      "$\\frac{f(x+h)g(x+h) - f(x)g(x)}{h} = \\frac{f(x+h)g(x+h) - f(x)g(x+h) + f(x)g(x+h) - f(x)g(x)}{h}$\n\n$= g(x+h) \\cdot \\frac{f(x+h) - f(x)}{h} + f(x) \\cdot \\frac{g(x+h) - g(x)}{h}$.\n\nבגבול $h \\to 0$: $g(x+h) \\to g(x)$ (רציפות), והאיברים נותנים $g(x) f'(x) + f(x) g'(x)$. $\\blacksquare$"),
    P("prf_derivative_quotient", "thm_derivative_quotient",
      ["thm_derivative_product", "thm_derivative_chain",
       "thm_derivative_power"],
      "$\\frac{f}{g} = f \\cdot g^{-1}$. לפי כלל המכפלה והשרשרת:\n\n$\\left(\\frac{f}{g}\\right)' = f' \\cdot g^{-1} + f \\cdot (g^{-1})' = \\frac{f'}{g} + f \\cdot \\left(-\\frac{g'}{g^2}\\right) = \\frac{f' g - f g'}{g^2}$. $\\blacksquare$"),
    P("prf_derivative_chain", "thm_derivative_chain",
      ["def_derivative_at_point", "thm_differentiable_implies_continuous"],
      "$\\frac{f(g(x+h)) - f(g(x))}{h} = \\frac{f(g(x+h)) - f(g(x))}{g(x+h) - g(x)} \\cdot \\frac{g(x+h) - g(x)}{h}$ (כאשר ההפרש במונה האמצעי שונה מאפס).\n\nכאשר $h \\to 0$: $g(x+h) \\to g(x)$ (רציפות), והגורם הראשון שואף ל-$f'(g(x))$, השני ל-$g'(x)$. לכן הנגזרת היא $f'(g(x)) \\cdot g'(x)$.\n\n(טיפול בנקודות שבהן $g(x+h) = g(x)$ נעשה בנפרד.) $\\blacksquare$"),
    P("prf_derivative_sin", "thm_derivative_sin",
      ["def_derivative_at_point", "thm_sin_addition_formula",
       "thm_limit_sin_over_x", "thm_limit_sum", "thm_limit_product"],
      "$(\\sin x)' = \\lim_{h \\to 0} \\frac{\\sin(x+h) - \\sin x}{h} = \\lim_{h \\to 0} \\frac{\\sin x \\cos h + \\cos x \\sin h - \\sin x}{h}$\n\n$= \\sin x \\cdot \\lim_{h \\to 0} \\frac{\\cos h - 1}{h} + \\cos x \\cdot \\lim_{h \\to 0} \\frac{\\sin h}{h} = \\sin x \\cdot 0 + \\cos x \\cdot 1 = \\cos x$.\n\n(הגבול הראשון $0$ מתקבל מ-$\\cos h - 1 = -2 \\sin^2(h/2)$.) $\\blacksquare$"),
    P("prf_derivative_cos", "thm_derivative_cos",
      ["def_derivative_at_point", "thm_cos_addition_formula",
       "thm_limit_sin_over_x", "thm_derivative_sin"],
      "$(\\cos x)' = \\lim_{h \\to 0} \\frac{\\cos(x+h) - \\cos x}{h} = \\lim_{h \\to 0} \\frac{\\cos x \\cos h - \\sin x \\sin h - \\cos x}{h}$\n\n$= \\cos x \\cdot 0 - \\sin x \\cdot 1 = -\\sin x$. $\\blacksquare$"),
    P("prf_derivative_tan", "thm_derivative_tan",
      ["def_tan", "thm_derivative_quotient", "thm_derivative_sin",
       "thm_derivative_cos", "thm_sin_cos_pythagorean"],
      "$(\\tan x)' = \\left(\\frac{\\sin x}{\\cos x}\\right)' = \\frac{\\cos x \\cdot \\cos x - \\sin x \\cdot (-\\sin x)}{\\cos^2 x} = \\frac{\\cos^2 x + \\sin^2 x}{\\cos^2 x} = \\frac{1}{\\cos^2 x}$. $\\blacksquare$"),
    P("prf_derivative_exp", "thm_derivative_exp",
      ["def_derivative_at_point", "thm_exp_addition",
       "thm_limit_one_plus_inv_n_to_e"],
      "$(e^x)' = \\lim_{h \\to 0} \\frac{e^{x+h} - e^x}{h} = e^x \\cdot \\lim_{h \\to 0} \\frac{e^h - 1}{h}$.\n\nהגבול $\\lim_{h \\to 0} \\frac{e^h - 1}{h} = 1$ הוא תכונה מאפיינת של $e$ (ניתן להוכיח מהגדרת $e$ כגבול).\n\nלכן $(e^x)' = e^x$. $\\blacksquare$"),
    P("prf_derivative_log_natural", "thm_derivative_log_natural",
      ["thm_derivative_inverse_function", "thm_derivative_exp",
       "def_logarithm"],
      "$\\ln x$ היא הפונקציה ההפוכה של $e^y$. נגזרת ההפוכה: אם $y = \\ln x$ אז $x = e^y$, ולכן $\\frac{dy}{dx} = \\frac{1}{dx/dy} = \\frac{1}{e^y} = \\frac{1}{x}$. $\\blacksquare$"),
    P("prf_derivative_a_to_x", "thm_derivative_a_to_x",
      ["thm_derivative_exp", "thm_derivative_chain",
       "thm_log_inverse_of_exp"],
      "$a^x = e^{x \\ln a}$. לפי כלל השרשרת: $(a^x)' = e^{x \\ln a} \\cdot \\ln a = a^x \\cdot \\ln a$. $\\blacksquare$"),
    P("prf_derivative_log_general", "thm_derivative_log_general",
      ["thm_log_change_of_base", "thm_derivative_log_natural",
       "thm_derivative_constant_multiple"],
      "$\\log_a x = \\frac{\\ln x}{\\ln a}$. נגזרת: $(\\log_a x)' = \\frac{1}{\\ln a} \\cdot \\frac{1}{x} = \\frac{1}{x \\ln a}$. $\\blacksquare$"),

    # ── Applications of derivatives ──
    P("prf_fermat_extremum", "thm_fermat_extremum",
      ["def_derivative_at_point", "def_local_extremum"],
      "נניח $f$ מקבלת מקסימום מקומי ב-$x_0$ פנימית. אז קיימת סביבה שבה $f(x_0 + h) \\leq f(x_0)$ לכל $h$ קטן.\n\nגבול מימין: $f'(x_0^+) = \\lim_{h \\to 0^+} \\frac{f(x_0+h) - f(x_0)}{h} \\leq 0$ (מונה אי-חיובי, מכנה חיובי).\n\nגבול משמאל: $f'(x_0^-) = \\lim_{h \\to 0^-} \\frac{f(x_0+h) - f(x_0)}{h} \\geq 0$.\n\nכי $f$ גזירה, שני הגבולות שווים, ולכן $f'(x_0) = 0$. $\\blacksquare$"),
    P("prf_rolle_theorem", "thm_rolle_theorem",
      ["thm_extreme_value_theorem", "thm_fermat_extremum"],
      "$f$ רציפה ב-$[a, b]$, אז לפי משפט ויירשטראס מקבלת בו מקסימום ומינימום מוחלטים.\n\nאם המקסימום או המינימום פנימי — לפי משפט פרמה הנגזרת שם אפסית. סיימנו.\n\nאם שניהם בקצוות — אז $f(a) = f(b)$ הם גם המקסימום וגם המינימום, ולכן $f$ קבועה, וכל הנגזרת אפסית. $\\blacksquare$"),
    P("prf_mean_value_theorem", "thm_mean_value_theorem",
      ["thm_rolle_theorem", "thm_derivative_sum",
       "thm_derivative_constant_multiple"],
      "נגדיר $h(x) := f(x) - \\frac{f(b) - f(a)}{b - a}(x - a)$. אז $h(a) = h(b) = f(a)$, ו-$h$ רציפה וגזירה.\n\nלפי רול קיים $c$ עם $h'(c) = 0$, כלומר $f'(c) - \\frac{f(b) - f(a)}{b - a} = 0$, ולכן $f'(c) = \\frac{f(b) - f(a)}{b - a}$. $\\blacksquare$"),
    P("prf_increasing_test", "thm_increasing_test",
      ["thm_mean_value_theorem"],
      "נניח $f'(x) > 0$ בכל הקטע $I$. לכל $x_1 < x_2$ ב-$I$, לפי משפט הערך הממוצע קיים $c \\in (x_1, x_2)$ עם $\\frac{f(x_2) - f(x_1)}{x_2 - x_1} = f'(c) > 0$.\n\nלכן $f(x_2) - f(x_1) > 0$, כלומר $f(x_1) < f(x_2)$. $\\blacksquare$"),
    P("prf_decreasing_test", "thm_decreasing_test",
      ["thm_mean_value_theorem"],
      "באותה הוכחה כמו במבחן עלייה, רק עם $f'(c) < 0$ → $f(x_1) > f(x_2)$. $\\blacksquare$"),
    P("prf_tangent_line_equation", "thm_tangent_line_equation",
      ["def_derivative_at_point", "def_linear_function"],
      "המשיק בנקודה $(x_0, f(x_0))$ הוא ישר שמשתפעו $f'(x_0)$ (לפי הגדרת הנגזרת — הקו החותך 'מתקרב למשיק' בגבול).\n\nמשוואת ישר דרך נקודה עם שיפוע נתון: $y - y_0 = m(x - x_0)$, ולכן $y - f(x_0) = f'(x_0)(x - x_0)$. $\\blacksquare$"),
    P("prf_second_derivative_test", "thm_second_derivative_test",
      ["def_second_derivative", "thm_concavity_second_derivative",
       "thm_fermat_extremum", "thm_first_derivative_test"],
      "אם $f''(x_0) > 0$, אז $f'$ עולה בסביבת $x_0$. בהנחה $f'(x_0) = 0$, $f'$ עוברת מ-$-$ ל-$+$ ב-$x_0$, ולכן לפי מבחן הנגזרת הראשונה $x_0$ הוא מינימום מקומי.\n\nאם $f''(x_0) < 0$, $f'$ יורדת ועוברת מ-$+$ ל-$-$ → מקסימום מקומי. $\\blacksquare$"),

    # ── Antiderivatives ──
    P("prf_antiderivative_differ_by_constant", "thm_antiderivative_differ_by_constant",
      ["def_antiderivative", "thm_mean_value_theorem", "thm_derivative_sum"],
      "נגדיר $H := F_1 - F_2$. אז $H' = F_1' - F_2' = f - f = 0$ בכל הקטע.\n\nלפי משפט הערך הממוצע, פונקציה עם נגזרת אפס בקטע היא קבועה (לכל $x_1 < x_2$ קיים $c$ עם $H(x_2) - H(x_1) = H'(c)(x_2 - x_1) = 0$). $\\blacksquare$"),
    P("prf_integral_constant_multiple", "thm_integral_constant_multiple",
      ["def_antiderivative", "thm_derivative_constant_multiple"],
      "אם $F' = f$, אז $(cF)' = c \\cdot F' = c \\cdot f$. לכן $cF$ קדומה של $cf$, כלומר $\\int cf \\, dx = c F + C = c \\int f \\, dx$. $\\blacksquare$"),
    P("prf_integral_sum", "thm_integral_sum",
      ["def_antiderivative", "thm_derivative_sum"],
      "אם $F' = f$ ו-$G' = g$, אז $(F + G)' = F' + G' = f + g$, ולכן $F + G$ קדומה של $f + g$. $\\blacksquare$"),
    P("prf_integral_power", "thm_integral_power",
      ["def_antiderivative", "thm_derivative_power"],
      "נבדוק: $\\left(\\frac{x^{n+1}}{n+1}\\right)' = \\frac{(n+1) x^n}{n+1} = x^n$. ✓ עבור $n \\neq -1$ (חלוקה ב-$n+1$). $\\blacksquare$"),
    P("prf_integral_one_over_x", "thm_integral_one_over_x",
      ["def_antiderivative", "thm_derivative_log_natural"],
      "עבור $x > 0$: $(\\ln x)' = \\frac{1}{x}$. עבור $x < 0$: $\\ln|x| = \\ln(-x)$, ו-$(\\ln(-x))' = \\frac{-1}{-x} = \\frac{1}{x}$. בשני המקרים $\\ln|x|$ קדומה. $\\blacksquare$"),
    P("prf_integral_exp", "thm_integral_exp",
      ["def_antiderivative", "thm_derivative_exp"],
      "$(e^x)' = e^x$, ולכן $e^x$ קדומה של עצמה. $\\blacksquare$"),
    P("prf_integral_sin", "thm_integral_sin",
      ["def_antiderivative", "thm_derivative_cos"],
      "$(-\\cos x)' = -(-\\sin x) = \\sin x$, ולכן $-\\cos x$ קדומה של $\\sin x$. $\\blacksquare$"),
    P("prf_integral_cos", "thm_integral_cos",
      ["def_antiderivative", "thm_derivative_sin"],
      "$(\\sin x)' = \\cos x$, ולכן $\\sin x$ קדומה של $\\cos x$. $\\blacksquare$"),
    P("prf_integral_substitution", "thm_integral_substitution",
      ["thm_derivative_chain", "def_antiderivative"],
      "אם $F$ קדומה של $f$, אז $(F(g(x)))' = F'(g(x)) \\cdot g'(x) = f(g(x)) \\cdot g'(x)$ (לפי כלל השרשרת).\n\nלכן $F(g(x))$ קדומה של $f(g(x)) \\cdot g'(x)$, כלומר $\\int f(g(x)) g'(x) \\, dx = F(g(x)) + C = \\int f(u) \\, du$. $\\blacksquare$"),
    P("prf_integral_by_parts", "thm_integral_by_parts",
      ["thm_derivative_product", "def_antiderivative"],
      "מכלל המכפלה: $(fg)' = f' g + f g'$. נסדר: $f g' = (fg)' - f' g$.\n\nאינטגרציה: $\\int f(x) g'(x) \\, dx = f(x) g(x) - \\int f'(x) g(x) \\, dx$. $\\blacksquare$"),

    # ── FTC ──
    P("prf_ftc_part1", "thm_ftc_part1",
      ["def_definite_integral", "def_derivative_at_point",
       "thm_extreme_value_theorem", "thm_definite_integral_additivity"],
      "$F(x + h) - F(x) = \\int_x^{x+h} f(t) \\, dt$.\n\nכי $f$ רציפה ב-$[x, x+h]$, ויירשטראס מבטיח שיש בו ערכי מקסימום $M$ ומינימום $m$. לכן $mh \\leq F(x+h) - F(x) \\leq Mh$, כלומר $m \\leq \\frac{F(x+h) - F(x)}{h} \\leq M$.\n\nכש-$h \\to 0$, $m, M \\to f(x)$ (רציפות), ולפי סנדוויץ׳: $F'(x) = f(x)$. $\\blacksquare$"),
    P("prf_ftc_part2", "thm_ftc_part2",
      ["thm_ftc_part1", "thm_antiderivative_differ_by_constant"],
      "נגדיר $G(x) := \\int_a^x f(t) \\, dt$. לפי החלק הראשון, $G' = f$, ולכן $G$ קדומה של $f$.\n\nכל קדומה $F$ שונה מ-$G$ בקבוע: $F(x) = G(x) + c$.\n\nאז $F(b) - F(a) = G(b) - G(a) = \\int_a^b f \\, dt - 0 = \\int_a^b f \\, dt$. $\\blacksquare$"),
    P("prf_area_under_curve", "thm_area_under_curve",
      ["def_definite_integral", "def_riemann_sum"],
      "סכום רימן עבור $f \\geq 0$ הוא בדיוק סכום שטחים של מלבנים שמכוסים בין הגרף לציר $x$.\n\nככל שהחלוקה נעשית עדינה יותר ($\\Delta x \\to 0$), הסכום מתכנס לשטח המדויק תחת הגרף, שזה $\\int_a^b f(x) \\, dx$. $\\blacksquare$"),
    P("prf_area_between_curves", "thm_area_between_curves",
      ["thm_area_under_curve", "thm_integral_sum"],
      "השטח בין $f$ ו-$g$ (עם $f \\geq g$) שווה לשטח תחת $f$ פחות השטח תחת $g$: $\\int_a^b f \\, dx - \\int_a^b g \\, dx = \\int_a^b (f - g) \\, dx$. $\\blacksquare$"),
    P("prf_volume_of_revolution_disc", "thm_volume_of_revolution_disc",
      ["def_volume_of_revolution", "def_definite_integral"],
      "נחתוך את הגוף בדיסקים אנכיים דקים. בעובי $\\Delta x$ בנקודה $x$, הדיסק הוא עיגול ברדיוס $f(x)$, ונפחו $\\pi f(x)^2 \\Delta x$.\n\nסכום נפחים בגבול: $V = \\int_a^b \\pi f(x)^2 \\, dx$. $\\blacksquare$"),

    # ── Vectors ──
    P("prf_dot_product_geometric", "thm_dot_product_geometric",
      ["def_dot_product", "def_vector_magnitude", "thm_law_of_cosines"],
      "במשולש שנוצר מ-$\\vec{u}, \\vec{v}, \\vec{u} - \\vec{v}$, לפי משפט הקוסינוסים: $|\\vec{u} - \\vec{v}|^2 = |\\vec{u}|^2 + |\\vec{v}|^2 - 2|\\vec{u}||\\vec{v}|\\cos\\theta$.\n\nמצד שני, $|\\vec{u} - \\vec{v}|^2 = (\\vec{u} - \\vec{v}) \\cdot (\\vec{u} - \\vec{v}) = |\\vec{u}|^2 - 2 \\vec{u} \\cdot \\vec{v} + |\\vec{v}|^2$.\n\nהשוואה: $\\vec{u} \\cdot \\vec{v} = |\\vec{u}||\\vec{v}|\\cos\\theta$. $\\blacksquare$"),

    # ── Complex ──
    P("prf_complex_multiplication", "thm_complex_multiplication",
      ["def_imaginary_unit", "def_complex_number", "ax_distributive_law",
       "ax_multiplication_commutativity"],
      "$(a + bi)(c + di) = ac + adi + bci + bdi^2 = ac + (ad + bc)i + bd \\cdot (-1) = (ac - bd) + (ad + bc)i$\n\n(תוך שימוש בפילוג ובכך ש-$i^2 = -1$). $\\blacksquare$"),
    P("prf_de_moivre", "thm_de_moivre",
      ["def_polar_form_complex", "thm_complex_multiplication",
       "thm_cos_addition_formula", "thm_sin_addition_formula"],
      "אינדוקציה על $n$. בסיס $n = 1$: טריוויאלי.\n\nצעד: $(\\cos\\theta + i\\sin\\theta)^{n+1} = (\\cos\\theta + i\\sin\\theta)^n \\cdot (\\cos\\theta + i\\sin\\theta)$\n\n$= (\\cos n\\theta + i\\sin n\\theta)(\\cos\\theta + i\\sin\\theta)$ (לפי הנחת האינדוקציה)\n\n$= (\\cos n\\theta \\cos\\theta - \\sin n\\theta \\sin\\theta) + i(\\sin n\\theta \\cos\\theta + \\cos n\\theta \\sin\\theta)$\n\n$= \\cos((n+1)\\theta) + i \\sin((n+1)\\theta)$ (לפי נוסחאות חיבור). $\\blacksquare$"),
    P("prf_complex_modulus_product", "thm_complex_modulus_product",
      ["def_modulus_complex", "thm_complex_multiplication"],
      "נסמן $z_1 = a + bi, z_2 = c + di$. $z_1 z_2 = (ac - bd) + (ad + bc) i$, אז $|z_1 z_2|^2 = (ac - bd)^2 + (ad + bc)^2$.\n\nפתיחה: $= a^2 c^2 - 2abcd + b^2 d^2 + a^2 d^2 + 2abcd + b^2 c^2 = (a^2 + b^2)(c^2 + d^2) = |z_1|^2 |z_2|^2$.\n\nשורש: $|z_1 z_2| = |z_1| \\cdot |z_2|$. $\\blacksquare$"),
    P("prf_complex_division", "thm_complex_division",
      ["def_complex_conjugate", "def_modulus_complex",
       "thm_complex_multiplication"],
      "$\\frac{z_1}{z_2} = \\frac{z_1 \\cdot \\bar{z_2}}{z_2 \\cdot \\bar{z_2}}$. \n\n$z_2 \\cdot \\bar{z_2} = (c + di)(c - di) = c^2 + d^2 = |z_2|^2$ (ממשי וחיובי).\n\nלכן $\\frac{z_1}{z_2} = \\frac{z_1 \\bar{z_2}}{|z_2|^2}$. $\\blacksquare$"),
]
