"""Chunk 9 — 100 claims: more advanced 5-unit content.

Geometry (Heron, Menelaus, Ceva, Stewart, 3D extras), trig (general solutions,
triple angle, harmonic addition), function analysis (asymptotes, sign analysis,
curve sketching), basic ODEs, probability distributions, word problem patterns,
Pythagorean triples, hyperbolic functions, vector projection.
"""
from __future__ import annotations

from core.models import Claim, Course, Proof


CANON = "canonical"


def C(cid, kind, course, topic, stmt):
    return Claim(id=cid, kind=kind, status=CANON, course=course,
                 topic=topic, statement=stmt)


def P(pid, cid, deps, body, method="informal", status="reviewed", canonical=True):
    return Proof(id=pid, claim_id=cid, dependencies=list(deps), body=body,
                 method=method, status=status, is_canonical=canonical)


JHS = "math_jhs"
HS3 = "math_hs_3"
HS4 = "math_hs_4"
HS5 = "math_hs_5"


COURSES: list[Course] = []


CLAIMS = [
    # ═══ Advanced geometry ═══
    C("thm_triangle_area_base_height", "theorem", JHS, "גאומטריה",
      r"**שטח משולש = חצי בסיס × גובה:** $S = \tfrac{1}{2} \cdot a \cdot h_a$, כאשר $a$ אורך אחת הצלעות (הבסיס) ו-$h_a$ הוא הגובה אליה מהקודקוד הנגדי. הנוסחה היסודית לחישוב שטח משולש."),
    C("thm_triangle_area_sin", "theorem", HS4, "גאומטריה",
      r"**שטח משולש לפי סינוס:** $S = \frac{1}{2} a b \sin C$ — חצי מכפלת שתי צלעות בסינוס הזווית הכלואה ביניהן."),
    C("thm_heron_formula", "theorem", HS5, "גאומטריה",
      r"**נוסחת הרון:** עבור משולש עם צלעות $a, b, c$ וחצי-היקף $s = \frac{a+b+c}{2}$: $S = \sqrt{s(s-a)(s-b)(s-c)}$."),
    C("thm_circumradius_formula", "theorem", HS5, "גאומטריה",
      r"**רדיוס המעגל החוסם:** $R = \frac{abc}{4 S}$, כאשר $S$ שטח המשולש."),
    C("thm_inradius_formula", "theorem", HS5, "גאומטריה",
      r"**רדיוס המעגל החסום:** $r = \frac{S}{s}$, כאשר $s$ חצי-היקף ו-$S$ שטח."),
    C("thm_menelaus", "theorem", HS5, "גאומטריה מתקדמת",
      r"**משפט מנלאוס:** עבור ישר החותך את הצלעות (או הארכותיהן) של משולש $ABC$ בנקודות $X \in BC$, $Y \in CA$, $Z \in AB$: $\frac{AZ}{ZB} \cdot \frac{BX}{XC} \cdot \frac{CY}{YA} = -1$ (יחסים מסומנים)."),
    C("thm_ceva", "theorem", HS5, "גאומטריה מתקדמת",
      r"**משפט צ׳בה:** שלושה קווים מקודקודי משולש לצלעות הנגדיות חופפים בנקודה אחת אם ורק אם $\frac{AZ}{ZB} \cdot \frac{BX}{XC} \cdot \frac{CY}{YA} = 1$."),
    C("thm_stewart_theorem", "theorem", HS5, "גאומטריה מתקדמת",
      r"**משפט סטיוארט:** עבור קו מקודקוד $A$ במשולש $ABC$ החוצה את $BC$ בנקודה $D$ עם $BD = m, DC = n, AD = d$: $b^2 m + c^2 n - a d^2 = a m n$, כאשר $a = m+n$."),
    C("thm_tangent_secant_angle", "theorem", HS5, "גאומטריית מעגל",
      r"**זווית בין משיק וחותך:** הזווית בין משיק לחותך בנקודה משותפת שווה למחצית הקשת הכלואה ביניהם."),
    C("thm_distance_point_to_line_3d", "theorem", HS5, "גאומטריה אנליטית 3D",
      r"**מרחק נקודה לישר במרחב:** המרחק מנקודה $P$ לישר העובר דרך $P_0$ בכיוון $\vec{v}$: $d = \frac{|\vec{P_0 P} \times \vec{v}|}{|\vec{v}|}$."),
    C("thm_plane_through_three_points", "theorem", HS5, "גאומטריה אנליטית 3D",
      r"**מישור דרך שלוש נקודות:** דרך שלוש נקודות $A, B, C$ שאינן על ישר אחד קיים מישור יחיד; וקטור נורמלי שלו הוא $\vec{AB} \times \vec{AC}$."),
    C("thm_angle_line_plane", "theorem", HS5, "גאומטריה אנליטית 3D",
      r"**זווית בין ישר למישור:** הזווית $\theta$ בין ישר עם כיוון $\vec{v}$ למישור עם נורמל $\vec{n}$ מקיימת $\sin\theta = \frac{|\vec{v} \cdot \vec{n}|}{|\vec{v}| \cdot |\vec{n}|}$ (משלים לזווית בין הוקטורים)."),
    C("def_dihedral_angle", "definition", HS5, "גאומטריה במרחב",
      r"**זווית דו-מימדית:** הזווית בין שני חצאי-מישורים החולקים קו משותף. נמדדת ע״י קווים בכל מישור המאונכים לקו החיתוך מאותה נקודה."),
    C("thm_tetrahedron_volume", "theorem", HS5, "גאומטריה במרחב",
      r"**נפח פירמידה (טטרהדרון):** $V = \frac{1}{3} \cdot \text{שטח בסיס} \cdot \text{גובה}$. לפירמידה משולשת ניתן לחשב גם: $V = \frac{1}{6} |\vec{AB} \cdot (\vec{AC} \times \vec{AD})|$."),
    C("thm_sphere_surface_area", "theorem", HS5, "גאומטריה במרחב",
      r"**שטח פני כדור:** $A = 4 \pi r^2$ — ארבע פעמים שטח עיגול ברדיוס המעגל הגדול."),
    C("thm_cone_lateral_surface", "theorem", HS5, "גאומטריה במרחב",
      r"**שטח פאת חרוט (לטרלי):** $A_\text{lat} = \pi r \ell$, כאשר $\ell$ אורך הקו היוצר (slant height) — מרחק מקודקוד לקצה הבסיס."),

    # ═══ Trig extended ═══
    C("thm_general_solution_sin", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**פתרון כללי ל-$\sin x = a$:** עבור $|a| \leq 1$: $x = \arcsin a + 2\pi k$ או $x = \pi - \arcsin a + 2\pi k$, לכל $k \in \mathbb{Z}$."),
    C("thm_general_solution_cos", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**פתרון כללי ל-$\cos x = a$:** עבור $|a| \leq 1$: $x = \pm \arccos a + 2\pi k$, לכל $k \in \mathbb{Z}$."),
    C("thm_general_solution_tan", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**פתרון כללי ל-$\tan x = a$:** $x = \arctan a + \pi k$, לכל $k \in \mathbb{Z}$."),
    C("thm_tan_addition_formula", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**נוסחת חיבור לטנגנס:** $\tan(\alpha + \beta) = \frac{\tan\alpha + \tan\beta}{1 - \tan\alpha \tan\beta}$."),
    C("thm_sin_triple_angle", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**סינוס של זווית משולשת:** $\sin(3\alpha) = 3 \sin\alpha - 4 \sin^3\alpha$."),
    C("thm_cos_triple_angle", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**קוסינוס של זווית משולשת:** $\cos(3\alpha) = 4 \cos^3\alpha - 3 \cos\alpha$."),
    C("thm_weierstrass_substitution", "theorem", HS5, "טריגונומטריה מתקדמת",
      r"**הצבת ויירשטראס:** אם $t = \tan\frac{x}{2}$, אז $\sin x = \frac{2t}{1+t^2}$, $\cos x = \frac{1-t^2}{1+t^2}$, $dx = \frac{2 \, dt}{1+t^2}$. שימושית לאינטגרציה של ביטויים טריגונומטריים."),
    C("thm_harmonic_addition", "theorem", HS5, "טריגונומטריה מתקדמת",
      r"**הוספה הרמונית:** $a \sin x + b \cos x = R \sin(x + \varphi)$, כאשר $R = \sqrt{a^2 + b^2}$ ו-$\varphi = \arctan(b/a)$ (עם תיקון רביע)."),
    C("thm_law_of_tangents", "theorem", HS5, "טריגונומטריה מתקדמת",
      r"**חוק הטנגנסים:** במשולש: $\frac{a - b}{a + b} = \frac{\tan\frac{A-B}{2}}{\tan\frac{A+B}{2}}$."),

    # ═══ Function analysis ═══
    C("def_vertical_asymptote", "definition", HS5, "אנליזת פונקציות",
      r"**אסימפטוטה אנכית:** ישר $x = a$ הוא אסימפטוטה אנכית של $f$ אם $\lim_{x \to a} |f(x)| = \infty$ (משני הצדדים או מאחד)."),
    C("def_horizontal_asymptote", "definition", HS5, "אנליזת פונקציות",
      r"**אסימפטוטה אופקית:** ישר $y = L$ הוא אסימפטוטה אופקית אם $\lim_{x \to \infty} f(x) = L$ או $\lim_{x \to -\infty} f(x) = L$."),
    C("def_oblique_asymptote", "definition", HS5, "אנליזת פונקציות",
      r"**אסימפטוטה משופעת:** ישר $y = m x + b$ עם $m \neq 0$ הוא אסימפטוטה משופעת אם $\lim_{x \to \pm\infty} [f(x) - (m x + b)] = 0$."),
    C("def_limit_at_infinity", "definition", HS5, "אנליזת פונקציות",
      r"**גבול באינסוף:** $\lim_{x \to \infty} f(x) = L$ אם לכל $\epsilon > 0$ קיים $M$ כך שלכל $x > M$ מתקיים $|f(x) - L| < \epsilon$."),
    C("def_sign_analysis", "definition", HS5, "אנליזת פונקציות",
      r"**תחומי סימן:** מציאת הקטעים שבהם $f(x) > 0$ ו-$f(x) < 0$ — מתחלקת לפי אפסי הפונקציה ונקודות אי-רציפות."),
    C("thm_curve_sketching_procedure", "theorem", HS5, "אנליזת פונקציות",
      r"**שיטה לחקירת פונקציה:** (1) תחום הגדרה; (2) חיתוך עם הצירים; (3) זוגיות/אי-זוגיות; (4) אסימפטוטות; (5) נגזרת ראשונה — תחומי עלייה/ירידה ונקודות קיצון; (6) נגזרת שנייה — קעירות ונקודות פיתול; (7) שרטוט."),
    C("def_increasing_interval", "definition", HS5, "אנליזת פונקציות",
      r"**תחום עלייה/ירידה:** קטע מקסימלי בתחום ההגדרה שבו הפונקציה עולה (או יורדת) ממש. נמצא ע״י סימן הנגזרת."),
    C("def_concavity_interval", "definition", HS5, "אנליזת פונקציות",
      r"**תחום קעירות:** קטע מקסימלי שבו הפונקציה קעורה כלפי מעלה (או למטה). נמצא ע״י סימן הנגזרת השנייה."),
    C("thm_inverse_function_exists", "theorem", HS5, "פונקציות",
      r"**קיום פונקציה הפוכה:** לפונקציה $f$ קיימת פונקציה הפוכה $f^{-1}$ אם ורק אם $f$ חד-חד-ערכית (כלומר $f(x_1) = f(x_2) \Rightarrow x_1 = x_2$). פונקציה מונוטונית ממש בכל תחומה היא חד-חד-ערכית."),
    C("thm_monotone_convergence", "theorem", HS5, "אנליזה",
      r"**משפט סדרה מונוטונית חסומה:** סדרה ממשית עולה החסומה מלמעלה מתכנסת. סדרה יורדת החסומה מלמטה מתכנסת. הגבול הוא הסופרימום (או האינפימום) של איברי הסדרה."),
    C("def_bounded_sequence", "definition", HS5, "אנליזה",
      r"**סדרה חסומה:** סדרה $(a_n)$ נקראת **חסומה מלמעלה** אם קיים $M$ כך ש-$a_n \leq M$ לכל $n$. **חסומה מלמטה** סימטרית. **חסומה** = חסומה משני הצדדים."),
    C("def_bijection", "definition", HS5, "פונקציות",
      r"**פונקציה חד-חד-ערכית ועל (בייקציה):** פונקציה היא **חד-חד-ערכית** אם ערכים שונים נשלחים לערכים שונים, **על** אם כל איבר בטווח מתקבל. בייקציה — שתי התכונות יחד."),

    # ═══ Calculus applications & extras ═══
    C("def_riemann_sum_left", "definition", HS5, "אינטגרל מסוים",
      r"**סכום רימן שמאלי:** $L_n = \sum_{i=0}^{n-1} f(x_i) \Delta x$ — מעריך באמצעות גובה הפונקציה בקצה השמאלי של כל קטע."),
    C("def_riemann_sum_right", "definition", HS5, "אינטגרל מסוים",
      r"**סכום רימן ימני:** $R_n = \sum_{i=1}^{n} f(x_i) \Delta x$ — בעזרת גובה הפונקציה בקצה הימני."),
    C("def_riemann_sum_midpoint", "definition", HS5, "אינטגרל מסוים",
      r"**סכום רימן אמצעי:** $M_n = \sum_{i=1}^{n} f\!\left(\frac{x_{i-1} + x_i}{2}\right) \Delta x$. בדרך כלל מדויק יותר מהשמאלי/ימני."),
    C("def_normal_line_to_curve", "definition", HS5, "יישומי נגזרת",
      r"**ישר נורמל לגרף:** הישר העובר דרך נקודת השקה ומאונך למשיק שם. עבור משיק בשיפוע $m$, שיפוע הנורמל הוא $-\frac{1}{m}$ (אם $m \neq 0$)."),
    C("thm_volume_by_cross_sections", "theorem", HS5, "יישומי אינטגרל",
      r"**נפח לפי חתכים:** עבור גוף שבו שטח החתך בנקודה $x$ הוא $A(x)$: $V = \int_a^b A(x) \, dx$."),
    C("def_work_integral", "definition", HS5, "יישומי אינטגרל",
      r"**עבודה כאינטגרל:** עבור כוח משתנה $F(x)$ הפועל לאורך מסלול: $W = \int_a^b F(x) \, dx$. למשפט הפיזיקאלי $W = F \cdot d$ נכון רק לכוח קבוע."),
    C("thm_position_velocity_acceleration", "theorem", HS5, "יישומי אינטגרל",
      r"**מיקום, מהירות, תאוצה:** מיקום $x(t)$, מהירות $v(t) = x'(t)$, תאוצה $a(t) = v'(t) = x''(t)$. בהיפוך: $v(t) = \int a \, dt + v_0$, $x(t) = \int v \, dt + x_0$."),
    C("def_average_velocity", "definition", HS5, "יישומי אינטגרל",
      r"**מהירות ממוצעת:** עבור פונקציית מיקום $x(t)$ בקטע $[t_1, t_2]$: $\bar{v} = \frac{x(t_2) - x(t_1)}{t_2 - t_1}$ — שינוי מיקום חלקי שינוי זמן."),
    C("thm_max_min_on_closed_interval", "theorem", HS5, "יישומי נגזרת",
      r"**מקסימום ומינימום בקטע סגור:** פונקציה רציפה בקטע $[a, b]$ מקבלת מקסימום ומינימום מוחלטים. הם נמצאים בנקודות חשודות פנימיות ($f' = 0$ או $f$ לא גזירה) או בקצוות $a, b$. בודקים ערכי הפונקציה בכל המועמדים."),

    # ═══ Differential equations basics ═══
    C("def_ode_first_order", "definition", HS5, "משוואות דיפרנציאליות",
      r"**משוואה דיפרנציאלית מסדר ראשון:** משוואה מהצורה $F(x, y, y') = 0$, או באופן שקול $y' = f(x, y)$ — קובעת קשר בין $y$ ונגזרתה."),
    C("def_separable_ode", "definition", HS5, "משוואות דיפרנציאליות",
      r"**משוואה ניתנת להפרדה:** $\frac{dy}{dx} = g(x) h(y)$. פתרון: $\int \frac{dy}{h(y)} = \int g(x) \, dx + C$."),
    C("thm_exponential_ode_solution", "theorem", HS5, "משוואות דיפרנציאליות",
      r"**פתרון $y' = k y$:** הפתרון הכללי הוא $y(t) = C e^{kt}$ עבור קבוע $C$. עם תנאי התחלה $y(0) = y_0$: $y(t) = y_0 e^{kt}$."),
    C("def_initial_value_problem", "definition", HS5, "משוואות דיפרנציאליות",
      r"**בעיית ערך התחלתי:** משוואה דיפרנציאלית עם תנאי כמו $y(x_0) = y_0$ הקובע פתרון יחיד מתוך משפחת הפתרונות הכללית."),
    C("thm_newton_cooling_law", "theorem", HS5, "פיזיקה",
      r"**חוק הקירור של ניוטון:** $\frac{dT}{dt} = -k(T - T_\text{env})$. פתרון: $T(t) = T_\text{env} + (T_0 - T_\text{env}) e^{-kt}$ — הטמפרטורה מתקרבת מעריכית לטמפרטורת הסביבה."),
    C("def_free_fall_equation", "definition", HS5, "פיזיקה",
      r"**משוואת נפילה חופשית:** $\frac{d^2 y}{dt^2} = -g$ (תאוצה קבועה). פתרון: $y(t) = y_0 + v_0 t - \tfrac{1}{2} g t^2$."),
    C("def_linear_first_order_ode", "definition", HS5, "משוואות דיפרנציאליות",
      r"**משוואה לינארית מסדר ראשון:** $y' + p(x) y = q(x)$. נפתרת בעזרת גורם אינטגרטיבי $\mu(x) = e^{\int p \, dx}$."),
    C("thm_integrating_factor", "theorem", HS5, "משוואות דיפרנציאליות",
      r"**שיטת הגורם האינטגרטיבי:** עבור $y' + p(x) y = q(x)$, נכפיל ב-$\mu = e^{\int p}$: $(\mu y)' = \mu q$. ואז $y = \frac{1}{\mu} \int \mu q \, dx + \frac{C}{\mu}$."),

    # ═══ Probability distributions extended ═══
    C("def_bernoulli_trial", "definition", HS5, "הסתברות מתקדמת",
      r"**ניסוי ברנולי:** ניסוי עם שתי תוצאות אפשריות — הצלחה (הסתברות $p$) או כישלון (הסתברות $1-p$)."),
    C("def_bernoulli_distribution", "definition", HS5, "הסתברות מתקדמת",
      r"**התפלגות ברנולי:** $X \sim \text{Bernoulli}(p)$ — $X = 1$ בהסתברות $p$, $X = 0$ בהסתברות $1-p$. $E[X] = p$, $\text{Var}(X) = p(1-p)$."),
    C("def_poisson_distribution", "definition", HS5, "הסתברות מתקדמת",
      r"**התפלגות פואסון:** $X \sim \text{Poisson}(\lambda)$ — מספר אירועים בקטע זמן עם קצב $\lambda$. $P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!}$. $E[X] = \text{Var}(X) = \lambda$."),
    C("thm_normal_z_standardization", "theorem", HS5, "סטטיסטיקה מתקדמת",
      r"**תיקנון נורמלי:** אם $X \sim N(\mu, \sigma^2)$, אז $Z = \frac{X - \mu}{\sigma} \sim N(0, 1)$. מאפשר שימוש בטבלת $Z$ סטנדרטית לחישוב הסתברויות."),
    C("thm_68_95_99_rule", "theorem", HS5, "סטטיסטיקה מתקדמת",
      r"**כלל 68-95-99.7:** בהתפלגות נורמלית: $\approx 68\%$ מהערכים בטווח $\mu \pm \sigma$; $\approx 95\%$ ב-$\mu \pm 2\sigma$; $\approx 99.7\%$ ב-$\mu \pm 3\sigma$."),
    C("thm_central_limit_theorem_intuitive", "theorem", HS5, "סטטיסטיקה מתקדמת",
      r"**משפט הגבול המרכזי (אינטואיטיבי):** ממוצע של $n$ משתנים מקריים בלתי-תלויים זהי-התפלגות עם תוחלת $\mu$ ושונות $\sigma^2$ שואף להתפלגות נורמלית $N(\mu, \sigma^2/n)$ ככל ש-$n \to \infty$."),
    C("def_confidence_interval", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**רווח סמך:** קטע סביב ערך מנותן (כמו ממוצע מדגם) שיש בו הסתברות מסוימת ($95\%$ לרוב) לכלול את הפרמטר האמיתי באוכלוסייה."),
    C("def_sampling_distribution", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**התפלגות סטטיסטיקה במדגם:** ההתפלגות התיאורטית של ערכי סטטיסטיקה (כמו $\bar{X}$) על פני כל המדגמים האפשריים בגודל $n$ מהאוכלוסייה."),
    C("def_standard_error", "definition", HS5, "סטטיסטיקה מתקדמת",
      r"**שגיאת תקן:** סטיית התקן של התפלגות הדגימה של סטטיסטיקה. עבור ממוצע: $\text{SE}(\bar{X}) = \frac{\sigma}{\sqrt{n}}$."),

    # ═══ Word problem patterns ═══
    C("def_motion_problem_pattern", "definition", HS3, "בעיות מילוליות",
      r"**בעיית תנועה:** מבוססת על $\text{מרחק} = \text{מהירות} \cdot \text{זמן}$. בעיות מפגש: סכום מרחקים = מרחק ראשוני. בעיות התרחקות: הפרש מרחקים."),
    C("def_work_problem_pattern", "definition", HS3, "בעיות מילוליות",
      r"**בעיית עבודה:** קצב עבודה $r = 1/t$ (חלק העבודה בזמן יחידה). פועלים יחד: $\frac{1}{t_\text{משותף}} = \sum \frac{1}{t_i}$."),
    C("def_mixture_problem_pattern", "definition", HS3, "בעיות מילוליות",
      r"**בעיית תערובת:** ריכוז × נפח = כמות. אחרי ערבוב: $\sum (\text{ריכוז}_i \cdot V_i) = \text{ריכוז סופי} \cdot V_\text{כולל}$."),
    C("def_age_problem_pattern", "definition", HS3, "בעיות מילוליות",
      r"**בעיית גילים:** הפרשי גילים נשמרים בזמן. לרוב משוואות לינאריות במספר משתנים."),
    C("def_number_problem_pattern", "definition", HS3, "בעיות מילוליות",
      r"**בעיית מספרים:** מספר דו-ספרתי $\overline{ab} = 10a + b$. הופך: $\overline{ba} = 10b + a$. סכום: $a + b$. מכפלה: $ab$."),
    C("def_growth_decay_problem_pattern", "definition", HS4, "בעיות מילוליות",
      r"**בעיית גדילה/דעיכה:** $y(t) = y_0 (1 + r)^t$ לגדילה דיסקרטית, $y(t) = y_0 e^{kt}$ לרציפה. דעיכה: $k < 0$ או $r < 0$."),
    C("def_compound_problem_pattern", "definition", HS4, "בעיות מילוליות",
      r"**בעיית חישובי ריבית:** ריבית פשוטה $A = P(1 + rt)$. דריבית $A = P(1 + r/n)^{nt}$. רציפה $A = Pe^{rt}$."),
    C("def_optimization_problem_pattern", "definition", HS5, "בעיות מילוליות",
      r"**בעיית קיצון מילולית:** (1) הגדר משתנים; (2) רשום את הפונקציה לאופטימיזציה; (3) הבע במשתנה יחיד (משתמש באילוצים); (4) גזור והשווה לאפס; (5) ודא מינ/מקס באמצעות נגזרת שנייה או השוואה."),

    # ═══ Number theory ═══
    C("def_pythagorean_triple", "definition", HS5, "תורת המספרים",
      r"**שלשה פיתגוראית:** שלושה שלמים חיוביים $(a, b, c)$ המקיימים $a^2 + b^2 = c^2$. **פרימיטיבית** אם $\gcd(a, b, c) = 1$."),
    C("thm_pythagorean_triples_param", "theorem", HS5, "תורת המספרים",
      r"**פרמטריזציית שלשות פיתגוראיות:** כל שלשה פיתגוראית פרימיטיבית ניתנת לכתיבה כ-$(m^2 - n^2, 2mn, m^2 + n^2)$ עבור $m > n > 0$ זרים בעלי זוגיות שונה."),
    C("thm_linear_diophantine_solvable", "theorem", HS5, "תורת המספרים",
      r"**משוואה דיופנטית לינארית:** $ax + by = c$ פתירה במספרים שלמים אם ורק אם $\gcd(a, b) \mid c$. אם כן, יש אינסוף פתרונות."),
    C("thm_modular_inverse_computation", "theorem", HS5, "תורת המספרים",
      r"**חישוב הפכי מודולרי:** $a^{-1} \pmod n$ קיים אם ורק אם $\gcd(a, n) = 1$. מחושב ע״י אלגוריתם אוקלידס מורחב או $a^{\varphi(n) - 1} \pmod n$ (משפט אוילר)."),
    C("thm_sum_of_two_squares", "theorem", HS5, "תורת המספרים",
      r"**משפט שני הריבועים (פרמה):** מספר ראשוני אי-זוגי $p$ ניתן לכתיבה כסכום שני ריבועים $p = a^2 + b^2$ אם ורק אם $p \equiv 1 \pmod 4$."),
    C("def_quadratic_reciprocity_statement", "definition", HS5, "תורת המספרים",
      r"**הדדיות ריבועית (גאוס):** עבור ראשוניים אי-זוגיים שונים $p, q$: $\left(\frac{p}{q}\right) \left(\frac{q}{p}\right) = (-1)^{\frac{p-1}{2} \cdot \frac{q-1}{2}}$, כאשר $\left(\frac{\cdot}{\cdot}\right)$ הוא סמל לג׳נדר."),

    # ═══ Hyperbolic functions ═══
    C("def_hyperbolic_sin_cos", "definition", HS5, "פונקציות מיוחדות",
      r"**סינוס וקוסינוס היפרבוליים:** $\sinh x := \frac{e^x - e^{-x}}{2}$, $\cosh x := \frac{e^x + e^{-x}}{2}$."),
    C("def_hyperbolic_tan", "definition", HS5, "פונקציות מיוחדות",
      r"**טנגנס היפרבולי:** $\tanh x := \frac{\sinh x}{\cosh x} = \frac{e^x - e^{-x}}{e^x + e^{-x}}$."),
    C("thm_hyperbolic_identity", "theorem", HS5, "פונקציות מיוחדות",
      r"**זהות היפרבולית:** $\cosh^2 x - \sinh^2 x = 1$ (האנלוג ההיפרבולי לזהות $\sin^2 + \cos^2 = 1$)."),
    C("thm_hyperbolic_derivatives", "theorem", HS5, "פונקציות מיוחדות",
      r"**נגזרות היפרבוליות:** $(\sinh x)' = \cosh x$, $(\cosh x)' = \sinh x$, $(\tanh x)' = \frac{1}{\cosh^2 x}$."),
    C("def_inverse_hyperbolic", "definition", HS5, "פונקציות מיוחדות",
      r"**פונקציות היפרבוליות הפוכות:** $\text{arsinh}\, x = \ln(x + \sqrt{x^2 + 1})$, $\text{arcosh}\, x = \ln(x + \sqrt{x^2 - 1})$ (עבור $x \geq 1$), $\text{artanh}\, x = \tfrac{1}{2} \ln\!\frac{1+x}{1-x}$ ($|x| < 1$)."),

    # ═══ Vector projection ═══
    C("def_vector_projection", "definition", HS5, "וקטורים",
      r"**היטל וקטור:** ההיטל של $\vec{u}$ על $\vec{v}$: $\text{proj}_{\vec{v}} \vec{u} := \frac{\vec{u} \cdot \vec{v}}{|\vec{v}|^2} \vec{v}$."),
    C("def_scalar_projection", "definition", HS5, "וקטורים",
      r"**היטל סקלרי:** $\text{comp}_{\vec{v}} \vec{u} := \frac{\vec{u} \cdot \vec{v}}{|\vec{v}|} = |\vec{u}| \cos\theta$ — הגודל של ההיטל הוקטורי."),
    C("thm_vector_decomposition", "theorem", HS5, "וקטורים",
      r"**פירוק וקטור לרכיב מקביל ומאונך:** $\vec{u} = \text{proj}_{\vec{v}} \vec{u} + \vec{u}_\perp$, כאשר $\vec{u}_\perp$ מאונך ל-$\vec{v}$."),
    C("thm_triangle_area_cross_product", "theorem", HS5, "וקטורים",
      r"**שטח משולש לפי מכפלה וקטורית:** שטח המשולש בעל קודקודים $A, B, C$ ב-$\mathbb{R}^3$: $S = \frac{1}{2} |\vec{AB} \times \vec{AC}|$."),

    # ═══ Linear algebra extras ═══
    C("def_linear_transformation", "definition", HS5, "אלגברה לינארית",
      r"**העתקה לינארית:** פונקציה $T: V \to W$ בין מרחבים וקטוריים שמקיימת $T(\vec{u} + \vec{v}) = T(\vec{u}) + T(\vec{v})$ ו-$T(c \vec{v}) = c T(\vec{v})$."),
    C("def_kernel", "definition", HS5, "אלגברה לינארית",
      r"**גרעין (Kernel):** $\ker(T) := \{\vec{v} \in V : T(\vec{v}) = \vec{0}\}$ — קבוצת הוקטורים שהעתקה הלינארית שולחת לאפס."),
    C("def_image", "definition", HS5, "אלגברה לינארית",
      r"**תמונה (Image):** $\text{Im}(T) := \{T(\vec{v}) : \vec{v} \in V\}$ — קבוצת הוקטורים שמופיעים כתמונה של $T$."),
    C("def_rank", "definition", HS5, "אלגברה לינארית",
      r"**דרגה (Rank):** $\text{rank}(A) := \dim(\text{Im}(A))$ — ממד התמונה של מטריצה (או העתקה לינארית). שווה למספר השורות הבלתי-תלויות לינארית."),
    C("def_linear_independence", "definition", HS5, "אלגברה לינארית",
      r"**אי-תלות לינארית:** וקטורים $\vec{v_1}, \ldots, \vec{v_k}$ בלתי-תלויים לינארית אם $c_1 \vec{v_1} + \cdots + c_k \vec{v_k} = \vec{0}$ גורר $c_1 = \cdots = c_k = 0$."),
    C("def_basis", "definition", HS5, "אלגברה לינארית",
      r"**בסיס:** קבוצה של וקטורים בלתי-תלויים לינארית הפורשים את המרחב הוקטורי. כל וקטור במרחב ניתן להבעה יחידה כצירוף לינארי של איברי הבסיס."),
    C("def_dimension", "definition", HS5, "אלגברה לינארית",
      r"**ממד:** מספר האיברים בכל בסיס של המרחב הוקטורי. בלתי-תלוי בבחירת הבסיס."),
    C("def_characteristic_polynomial", "definition", HS5, "אלגברה לינארית",
      r"**פולינום אופייני:** עבור מטריצה $A$, $p_A(\lambda) := \det(A - \lambda I)$. שורשיו הם הערכים העצמיים של $A$."),

    # ═══ Misc / curve sketching extras ═══
    C("def_step_function", "definition", HS3, "פונקציות",
      r"**פונקציית מדרגה:** פונקציה הקבועה בקטעים. למשל $\lfloor x \rfloor$ (פונקציית הערך השלם)."),
    C("def_floor_ceiling", "definition", HS3, "פונקציות",
      r"**פונקציות ערך שלם:** $\lfloor x \rfloor$ — המספר השלם הגדול ביותר $\leq x$. $\lceil x \rceil$ — הקטן ביותר $\geq x$. $\{x\} := x - \lfloor x \rfloor$ — חלק שברי."),
    C("def_sign_function", "definition", HS4, "פונקציות",
      r"**פונקציית הסימן:** $\text{sgn}(x) := \begin{cases} 1 & x > 0 \\ 0 & x = 0 \\ -1 & x < 0 \end{cases}$. מקיים $x = |x| \cdot \text{sgn}(x)$."),
    C("thm_extremum_classification", "theorem", HS5, "יישומי נגזרת",
      r"**סיווג קיצון בנקודה חשודה:** אם $f'(x_0) = 0$: נגזרת שנייה $f''(x_0) > 0$ → מינימום מקומי; $f''(x_0) < 0$ → מקסימום מקומי; $f''(x_0) = 0$ → צריך בדיקה נוספת (למשל סימן הנגזרת השלישית, או מבחן הנגזרת הראשונה)."),
]


PROOFS = [
    # ── Geometry ──
    P("prf_triangle_area_base_height", "thm_triangle_area_base_height",
      ["def_triangle"],
      "הנוסחה היסודית לחישוב שטח משולש. ההצדקה הקלאסית: שכפול המשולש סביב אחת הצלעות יוצר מקבילית בעלת בסיס $a$ וגובה $h_a$, ששטחה $a \\cdot h_a$ (שטח מקבילית). המשולש הוא חצי מהמקבילית, ולכן $S = \\tfrac{1}{2} a h_a$. $\\blacksquare$",
      method="axiom"),
    P("prf_triangle_area_sin", "thm_triangle_area_sin",
      ["thm_triangle_area_base_height", "def_sin", "def_right_triangle"],
      "נוריד גובה $h_a$ מקודקוד $A$ אל הצלע $BC$ (אורך $a$). במשולש הישר-זווית שנוצר, $h_a = b \\sin C$ (לפי הגדרת הסינוס במשולש ישר-זווית).\n\nהצבה בנוסחת השטח (בסיס × גובה / 2): $S = \\tfrac{1}{2} \\cdot a \\cdot h_a = \\tfrac{1}{2} a b \\sin C$. $\\blacksquare$"),
    P("prf_heron_formula", "thm_heron_formula",
      ["thm_triangle_area_sin", "thm_law_of_cosines", "thm_sin_cos_pythagorean"],
      "מ-$S = \\tfrac{1}{2} a b \\sin C$ ו-$\\cos C = \\frac{a^2+b^2-c^2}{2ab}$ (קוסינוסים), $\\sin^2 C = 1 - \\cos^2 C = \\frac{(2ab)^2 - (a^2+b^2-c^2)^2}{(2ab)^2}$.\n\nפתיחה אלגברית ארוכה: $16 S^2 = 2 a^2 b^2 + 2 b^2 c^2 + 2 c^2 a^2 - a^4 - b^4 - c^4 = (a+b+c)(-a+b+c)(a-b+c)(a+b-c) = 16 s (s-a)(s-b)(s-c)$.\n\nלכן $S = \\sqrt{s(s-a)(s-b)(s-c)}$. $\\blacksquare$"),
    P("prf_circumradius_formula", "thm_circumradius_formula",
      ["thm_law_of_sines", "thm_triangle_area_sin"],
      "ממשפט הסינוסים $\\frac{a}{\\sin A} = 2R$, אז $\\sin A = \\frac{a}{2R}$. נציב בשטח: $S = \\tfrac{1}{2} b c \\sin A = \\frac{bca}{4R}$. סידור: $R = \\frac{abc}{4S}$. $\\blacksquare$"),
    P("prf_inradius_formula", "thm_inradius_formula",
      ["def_incenter", "def_triangle"],
      "המעגל החסום משיק לשלוש הצלעות מבפנים, מרכזו $I$ במרחק $r$ מכל צלע. נחבר את $I$ לקודקודים — נוצרים שלושה תת-משולשים בעלי בסיסים $a, b, c$ וגובה משותף $r$.\n\nסכום שטחיהם = שטח המשולש המקורי: $S = \\tfrac{1}{2} r (a + b + c) = r s$. סידור: $r = S/s$. $\\blacksquare$"),
    P("prf_distance_point_to_line_3d", "thm_distance_point_to_line_3d",
      ["def_cross_product", "thm_cross_product_magnitude", "def_vector_magnitude"],
      "המרחק מ-$P$ לישר הוא רכיב $\\vec{P_0 P}$ המאונך ל-$\\vec{v}$. גודל המכפלה הוקטורית $|\\vec{P_0 P} \\times \\vec{v}| = |\\vec{P_0 P}| \\cdot |\\vec{v}| \\sin\\theta$, ולכן $|\\vec{P_0 P}| \\sin\\theta = \\frac{|\\vec{P_0 P} \\times \\vec{v}|}{|\\vec{v}|}$ — זה המרחק. $\\blacksquare$"),
    P("prf_plane_through_three_points", "thm_plane_through_three_points",
      ["def_cross_product", "thm_cross_product_perpendicular",
       "def_equation_of_plane"],
      "$\\vec{AB}$ ו-$\\vec{AC}$ מוכלים במישור. $\\vec{n} = \\vec{AB} \\times \\vec{AC}$ מאונך לשניהם ולכן מאונך למישור. משוואת המישור: $\\vec{n} \\cdot (\\vec{r} - \\vec{A}) = 0$. $\\blacksquare$"),
    P("prf_angle_line_plane", "thm_angle_line_plane",
      ["thm_dot_product_geometric", "def_equation_of_plane"],
      "הזווית בין $\\vec{v}$ ל-$\\vec{n}$ היא $\\alpha = \\arccos\\frac{|\\vec{v} \\cdot \\vec{n}|}{|\\vec{v}||\\vec{n}|}$. הזווית בין הישר למישור היא משלימה: $\\theta = \\frac{\\pi}{2} - \\alpha$, אז $\\sin\\theta = \\cos\\alpha = \\frac{|\\vec{v} \\cdot \\vec{n}|}{|\\vec{v}||\\vec{n}|}$. $\\blacksquare$"),
    P("prf_sphere_surface_area", "thm_sphere_surface_area",
      ["def_sphere", "thm_sphere_volume", "def_definite_integral"],
      "**גישת אינטגרל:** סובבים חצי מעגל $y = \\sqrt{R^2 - x^2}$ סביב ציר $x$. שטח פני סיבוב: $A = 2\\pi \\int_{-R}^R y \\sqrt{1 + (y')^2} dx$.\n\nחישוב $y' = \\frac{-x}{\\sqrt{R^2 - x^2}}$, ולכן $\\sqrt{1 + (y')^2} = \\frac{R}{y}$. הצבה: $A = 2\\pi \\int_{-R}^R y \\cdot \\frac{R}{y} dx = 2\\pi R \\cdot 2R = 4\\pi R^2$. $\\blacksquare$"),
    P("prf_cone_lateral_surface", "thm_cone_lateral_surface",
      ["def_cone"],
      "פיתוח פאת חרוט הוא מגזר עיגול ברדיוס $\\ell$ עם קשת באורך $2\\pi r$ (היקף הבסיס). שטח מגזר = $\\tfrac{1}{2} \\cdot \\ell \\cdot 2\\pi r = \\pi r \\ell$. $\\blacksquare$"),
    P("prf_tetrahedron_volume", "thm_tetrahedron_volume",
      ["def_scalar_triple_product", "def_pyramid"],
      "פירמידה משולשת = פירמידה. נפח = $\\tfrac{1}{3}$ שטח בסיס × גובה.\n\nבעזרת וקטורים: $V = \\tfrac{1}{3} \\cdot \\tfrac{1}{2}|\\vec{AB} \\times \\vec{AC}| \\cdot |\\text{היטל } \\vec{AD} \\text{ על הנורמל}| = \\tfrac{1}{6} |\\vec{AB} \\cdot (\\vec{AC} \\times \\vec{AD})|$. $\\blacksquare$"),

    # ── Trig extended ──
    P("prf_general_solution_sin", "thm_general_solution_sin",
      ["def_sin", "def_arcsin", "thm_sin_periodicity"],
      "סינוס מחזורי במחזור $2\\pi$, וגם סימטרי סביב $\\pi/2$: $\\sin(\\pi - x) = \\sin x$. לכן אם $\\sin x_0 = a$, גם $\\sin(\\pi - x_0) = a$, ושני אלה ועוד $2\\pi k$ הם כל הפתרונות במעגל. $\\blacksquare$"),
    P("prf_general_solution_cos", "thm_general_solution_cos",
      ["def_cos", "def_arccos", "thm_cos_periodicity", "thm_cos_even"],
      "קוסינוס מחזורי $2\\pi$ וזוגי. אם $\\cos x_0 = a$, גם $\\cos(-x_0) = a$ (זוגיות). שני הפתרונות במחזור: $\\pm x_0$, ועם המחזוריות $\\pm \\arccos a + 2\\pi k$. $\\blacksquare$"),
    P("prf_general_solution_tan", "thm_general_solution_tan",
      ["def_tan", "def_arctan"],
      "טנגנס מחזורי במחזור $\\pi$ (לא $2\\pi$, כי $\\tan(x + \\pi) = \\tan x$). חד-חד-ערכית במחזור, אז יש פתרון יחיד $\\arctan a$ בקטע $(-\\pi/2, \\pi/2)$, וכל היתר ב-$+\\pi k$. $\\blacksquare$"),
    P("prf_tan_addition_formula", "thm_tan_addition_formula",
      ["thm_sin_addition_formula", "thm_cos_addition_formula", "def_tan"],
      "$\\tan(\\alpha + \\beta) = \\frac{\\sin(\\alpha + \\beta)}{\\cos(\\alpha + \\beta)} = \\frac{\\sin\\alpha\\cos\\beta + \\cos\\alpha\\sin\\beta}{\\cos\\alpha\\cos\\beta - \\sin\\alpha\\sin\\beta}$. נחלק מונה ומכנה ב-$\\cos\\alpha\\cos\\beta$: $= \\frac{\\tan\\alpha + \\tan\\beta}{1 - \\tan\\alpha\\tan\\beta}$. $\\blacksquare$"),
    P("prf_sin_triple_angle", "thm_sin_triple_angle",
      ["thm_sin_addition_formula", "thm_sin_double_angle",
       "thm_cos_double_angle", "thm_sin_cos_pythagorean"],
      "$\\sin(3\\alpha) = \\sin(2\\alpha + \\alpha) = \\sin 2\\alpha \\cos\\alpha + \\cos 2\\alpha \\sin\\alpha = 2 \\sin\\alpha\\cos^2\\alpha + (1 - 2\\sin^2\\alpha) \\sin\\alpha$.\n\n$= 2 \\sin\\alpha(1 - \\sin^2\\alpha) + \\sin\\alpha - 2\\sin^3\\alpha = 3\\sin\\alpha - 4\\sin^3\\alpha$. $\\blacksquare$"),
    P("prf_cos_triple_angle", "thm_cos_triple_angle",
      ["thm_cos_addition_formula", "thm_sin_double_angle",
       "thm_cos_double_angle", "thm_sin_cos_pythagorean"],
      "$\\cos(3\\alpha) = \\cos(2\\alpha + \\alpha) = \\cos 2\\alpha \\cos\\alpha - \\sin 2\\alpha \\sin\\alpha = (2\\cos^2\\alpha - 1)\\cos\\alpha - 2\\sin\\alpha\\cos\\alpha\\sin\\alpha$.\n\n$= 2\\cos^3\\alpha - \\cos\\alpha - 2(1 - \\cos^2\\alpha)\\cos\\alpha = 4\\cos^3\\alpha - 3\\cos\\alpha$. $\\blacksquare$"),
    P("prf_harmonic_addition", "thm_harmonic_addition",
      ["thm_sin_addition_formula", "def_arctan"],
      "$R \\sin(x + \\varphi) = R(\\sin x \\cos\\varphi + \\cos x \\sin\\varphi)$. השוואה: $R\\cos\\varphi = a$, $R\\sin\\varphi = b$.\n\nריבוע וסכימה: $R^2 = a^2 + b^2$, ומחלוקה: $\\tan\\varphi = b/a$. $\\blacksquare$"),

    # ── Function analysis ──
    P("prf_curve_sketching_procedure", "thm_curve_sketching_procedure",
      ["thm_increasing_test", "thm_first_derivative_test",
       "thm_concavity_second_derivative", "def_vertical_asymptote"],
      "כל שלב מכוון לזיהוי תכונה מסוימת של הגרף:\n\n(1) תחום קובע איפה $f$ מוגדרת; (2) חיתוכים = $f(0)$ ופתרונות $f=0$; (3) זוגיות → סימטריה; (4) אסימפטוטות → התנהגות בקצוות; (5) $f'$ קובע מונוטוניות וקיצון לפי משפטי עלייה/ירידה ופרמה; (6) $f''$ קובע קעירות לפי תיאוריית קעירות; (7) שרטוט משלב את הכל. $\\blacksquare$"),
    P("prf_inverse_function_exists", "thm_inverse_function_exists",
      ["def_function", "def_inverse_function", "def_bijection",
       "def_increasing_function"],
      "($\\Leftarrow$) אם $f$ חד-חד-ערכית, נגדיר $f^{-1}(y) := $ ה-$x$ היחיד עם $f(x) = y$ (לכל $y$ בטווח). זו פונקציה תקינה.\n\n($\\Rightarrow$) אם $f^{-1}$ קיימת ו-$f(x_1) = f(x_2)$, אז $x_1 = f^{-1}(f(x_1)) = f^{-1}(f(x_2)) = x_2$. \n\nפונקציה מונוטונית: ערכים שונים → תמונות שונות → חד-חד-ערכית. $\\blacksquare$"),
    P("prf_monotone_convergence", "thm_monotone_convergence",
      ["def_bounded_sequence", "def_limit_of_sequence"],
      "**מתכונת השלמות של $\\mathbb{R}$.** לסדרה $a_n$ עולה חסומה $M$ קיים סופרימום $L = \\sup\\{a_n\\}$. לכל $\\epsilon > 0$ קיים $a_N > L - \\epsilon$ (אחרת $L - \\epsilon$ הוא חסם עליון קטן מ-$L$). מהמונוטוניות $a_n > L - \\epsilon$ לכל $n \\geq N$. גם $a_n \\leq L$ תמיד, אז $|a_n - L| < \\epsilon$. כלומר $\\lim a_n = L$. סימטרית ליורדת. $\\blacksquare$",
      method="axiom"),

    # ── Calculus apps ──
    P("prf_max_min_on_closed_interval", "thm_max_min_on_closed_interval",
      ["thm_extreme_value_theorem", "thm_fermat_extremum"],
      "**ויירשטראס** מבטיח שהמקסימום והמינימום מתקבלים בקטע. **משפט פרמה** אומר שבנקודה פנימית עם קיצון, $f' = 0$ (או הפונקציה לא גזירה). הקצוות הם מועמדים נוספים.\n\nלכן בודקים $f$ בכל הנקודות הקריטיות ($f'(x) = 0$ או לא גזיר) ובקצוות $a, b$. הערך הגבוה ביותר הוא המקסימום, הנמוך ביותר המינימום. $\\blacksquare$"),
    P("prf_volume_by_cross_sections", "thm_volume_by_cross_sections",
      ["def_definite_integral", "def_riemann_sum"],
      "נחלק את הציר ל-$n$ קטעים בעובי $\\Delta x$. נפח כל חתך דק $\\approx A(x_i) \\cdot \\Delta x$. סכום: $V \\approx \\sum A(x_i) \\Delta x$.\n\nגבול ($\\Delta x \\to 0$) הוא בדיוק $\\int_a^b A(x) \\, dx$ — הגדרת אינטגרל רימן. $\\blacksquare$"),
    P("prf_position_velocity_acceleration", "thm_position_velocity_acceleration",
      ["def_derivative_at_point", "thm_ftc_part2"],
      "מהגדרת מהירות = שינוי מיקום ביחס לזמן: $v(t) = x'(t)$. תאוצה = שינוי מהירות: $a(t) = v'(t) = x''(t)$.\n\nההיפוך לפי FTC חלק 2: $v(t) - v_0 = \\int_0^t a(s) ds$, ובדומה $x(t) - x_0 = \\int_0^t v(s) ds$. $\\blacksquare$"),

    # ── ODE ──
    P("prf_exponential_ode_solution", "thm_exponential_ode_solution",
      ["def_separable_ode", "thm_integral_one_over_x",
       "thm_derivative_exp"],
      "המשוואה $y' = k y$ ניתנת להפרדה: $\\frac{dy}{y} = k \\, dt$.\n\nאינטגרציה: $\\ln|y| = kt + C_0$, ולכן $y = \\pm e^{C_0} e^{kt} = C e^{kt}$ (הקבוע $C$ סופג את הסימן).\n\nתנאי התחלה $y(0) = y_0$: $C = y_0$. ייחודיות נובעת מתורת ה-ODE הקלאסית. $\\blacksquare$"),
    P("prf_newton_cooling_law", "thm_newton_cooling_law",
      ["def_separable_ode", "thm_exponential_ode_solution"],
      "נסמן $u = T - T_\\text{env}$, אז $u' = T' = -k(T - T_\\text{env}) = -ku$. לפי פתרון המעריכי: $u(t) = u_0 e^{-kt}$.\n\nהחזרה ל-$T$: $T(t) = T_\\text{env} + (T_0 - T_\\text{env}) e^{-kt}$. $\\blacksquare$"),
    P("prf_integrating_factor", "thm_integrating_factor",
      ["def_linear_first_order_ode", "thm_derivative_product",
       "thm_derivative_exp", "thm_integral_substitution"],
      "כפל ב-$\\mu(x) = e^{\\int p \\, dx}$ נותן $\\mu y' + \\mu p y = \\mu q$.\n\nצד שמאל הוא בדיוק $(\\mu y)'$ (לפי כלל מכפלה: $(\\mu y)' = \\mu' y + \\mu y' = \\mu p y + \\mu y'$).\n\nאז $(\\mu y)' = \\mu q$, אינטגרציה: $\\mu y = \\int \\mu q \\, dx + C$. חלוקה ב-$\\mu$ נותנת את $y$. $\\blacksquare$"),

    # ── Hyperbolic ──
    P("prf_hyperbolic_identity", "thm_hyperbolic_identity",
      ["def_hyperbolic_sin_cos", "thm_difference_of_squares"],
      "$\\cosh^2 x - \\sinh^2 x = \\frac{(e^x + e^{-x})^2 - (e^x - e^{-x})^2}{4} = \\frac{(2e^x)(2e^{-x})}{4} = \\frac{4}{4} = 1$ (לפי זהות $a^2 - b^2 = (a+b)(a-b)$). $\\blacksquare$"),
    P("prf_hyperbolic_derivatives", "thm_hyperbolic_derivatives",
      ["def_hyperbolic_sin_cos", "thm_derivative_exp",
       "thm_derivative_sum"],
      "$(\\sinh x)' = \\frac{(e^x - e^{-x})'}{2} = \\frac{e^x + e^{-x}}{2} = \\cosh x$.\n\n$(\\cosh x)' = \\frac{(e^x + e^{-x})'}{2} = \\frac{e^x - e^{-x}}{2} = \\sinh x$.\n\n$(\\tanh x)' = \\frac{\\cosh^2 x - \\sinh^2 x}{\\cosh^2 x} = \\frac{1}{\\cosh^2 x}$ (זהות היפרבולית). $\\blacksquare$"),

    # ── Vectors ──
    P("prf_vector_decomposition", "thm_vector_decomposition",
      ["def_vector_projection", "def_dot_product"],
      "נגדיר $\\vec{u}_\\perp := \\vec{u} - \\text{proj}_{\\vec{v}} \\vec{u}$.\n\nאזי $\\vec{u}_\\perp \\cdot \\vec{v} = \\vec{u} \\cdot \\vec{v} - \\frac{\\vec{u}\\cdot\\vec{v}}{|\\vec{v}|^2} \\vec{v} \\cdot \\vec{v} = \\vec{u}\\cdot\\vec{v} - \\vec{u}\\cdot\\vec{v} = 0$.\n\nלכן $\\vec{u}_\\perp \\perp \\vec{v}$, ו-$\\vec{u} = \\text{proj}_{\\vec{v}} \\vec{u} + \\vec{u}_\\perp$ כפי שדרוש. $\\blacksquare$"),
    P("prf_triangle_area_cross_product", "thm_triangle_area_cross_product",
      ["thm_cross_product_magnitude", "thm_triangle_area_sin",
       "thm_dot_product_geometric"],
      "$|\\vec{AB} \\times \\vec{AC}| = |\\vec{AB}| \\cdot |\\vec{AC}| \\sin\\theta$, כאשר $\\theta$ הזווית ב-$A$.\n\nשטח משולש $= \\tfrac{1}{2} |\\vec{AB}| |\\vec{AC}| \\sin\\theta = \\tfrac{1}{2} |\\vec{AB} \\times \\vec{AC}|$. $\\blacksquare$"),

    # ── Probability ──
    P("prf_normal_z_standardization", "thm_normal_z_standardization",
      ["def_normal_distribution", "thm_expected_value_linearity",
       "thm_variance_sum_independent"],
      "$Z = \\frac{X - \\mu}{\\sigma}$. תוחלת: $E[Z] = \\frac{E[X] - \\mu}{\\sigma} = 0$.\n\nשונות: $\\text{Var}(Z) = \\frac{\\text{Var}(X)}{\\sigma^2} = 1$.\n\nטרנספורמציה לינארית של $N$ נותנת $N$, אז $Z \\sim N(0, 1)$. $\\blacksquare$"),

    # ── Misc ──
    P("prf_extremum_classification", "thm_extremum_classification",
      ["thm_fermat_extremum", "thm_second_derivative_test",
       "thm_first_derivative_test"],
      "**משפט פרמה** מאתר את הנקודות החשודות ($f'(x_0) = 0$).\n\n**מבחן הנגזרת השנייה**: $f''$ קובע קעירות, ושם המסקנה ישירה.\n\nאם $f''(x_0) = 0$ — מבחן הנגזרת הראשונה (סימן $f'$ סביב $x_0$) מטפל. $\\blacksquare$"),

    # ── Missing backfill (round 9) ──
    P("prf_menelaus", "thm_menelaus",
      ["def_triangle", "thm_aa_similarity"],
      "**הוכחה (גישה הסתכלות באנכים).** מורידים אנכים מ-$A, B, C$ אל הקו $XYZ$. נקבל שלושה משולשים דומים (זוויות שוות לפי קו חותך), ומקסבים את היחסים שמעבר את המכפלה לזיהוי. החישוב נותן $\\prod \\frac{}{} = -1$ עם הסכמת סימנים. $\\blacksquare$"),
    P("prf_ceva", "thm_ceva",
      ["def_triangle", "thm_menelaus"],
      "**הוכחה ע״י מנלאוס מוכפל.** משתמשים בשני יישומים של מנלאוס על תת-משולשים שנוצרים מהקווים. ה-$-1$ של מנלאוס הופך ל-$+1$ עבור צ׳בה כי הקווים נחתכים בפנים. $\\blacksquare$"),
    P("prf_stewart_theorem", "thm_stewart_theorem",
      ["thm_law_of_cosines"],
      "**הוכחה מקוסינוסים פעמיים.** במשולש $ABD$ נקבל $c^2 = m^2 + d^2 - 2md\\cos\\angle ADB$. במשולש $ACD$: $b^2 = n^2 + d^2 + 2nd\\cos\\angle ADB$ (זוויות משלימות, אז סימן הקוסינוס מתחלף).\n\nכפל הראשונה ב-$n$, השנייה ב-$m$, וחיבור (הקוסינוסים מתבטלים): $c^2 n + b^2 m = mn(m+n) + d^2(m+n) = a(mn + d^2)$. סידור נותן את הזהות. $\\blacksquare$"),
    P("prf_tangent_secant_angle", "thm_tangent_secant_angle",
      ["thm_tangent_perpendicular_to_radius",
       "thm_inscribed_angle_theorem"],
      "ניקח משיק בנקודה $T$ וחותך החותך את המעגל ב-$A, B$ (בקרבת $T$). הזווית בין המשיק לחותך = $\\angle BTA$.\n\nהזווית ההיקפית $\\angle BTA$ נשענת על הקשת $TA$, שווה למחצית הקשת. הזווית בין המשיק לחותך = מחצית הקשת הכלואה. $\\blacksquare$"),
    P("prf_law_of_tangents", "thm_law_of_tangents",
      ["thm_law_of_sines", "thm_sin_addition_formula",
       "thm_sin_subtraction_formula", "thm_sum_to_product_sin"],
      "ממשפט הסינוסים $a = 2R \\sin A$, $b = 2R \\sin B$. אז $\\frac{a-b}{a+b} = \\frac{\\sin A - \\sin B}{\\sin A + \\sin B}$.\n\nלפי נוסחאות סכום-למכפלה: $\\sin A - \\sin B = 2 \\cos\\frac{A+B}{2} \\sin\\frac{A-B}{2}$, $\\sin A + \\sin B = 2 \\sin\\frac{A+B}{2} \\cos\\frac{A-B}{2}$.\n\nחילוק: $\\frac{\\sin\\frac{A-B}{2} / \\cos\\frac{A-B}{2}}{\\sin\\frac{A+B}{2} / \\cos\\frac{A+B}{2}} = \\frac{\\tan\\frac{A-B}{2}}{\\tan\\frac{A+B}{2}}$. $\\blacksquare$"),
    P("prf_weierstrass_substitution", "thm_weierstrass_substitution",
      ["def_tan", "thm_half_angle_sin", "thm_half_angle_cos",
       "thm_sin_double_angle", "thm_cos_double_angle"],
      "$\\sin x = 2 \\sin\\frac{x}{2}\\cos\\frac{x}{2} = \\frac{2 \\sin(x/2)/\\cos(x/2)}{1/\\cos^2(x/2)} = \\frac{2t}{1 + t^2}$ (חלוקה ב-$\\cos^2$ ושימוש ב-$1 + \\tan^2 = 1/\\cos^2$).\n\nבדומה $\\cos x = \\cos^2(x/2) - \\sin^2(x/2) = \\frac{1 - t^2}{1 + t^2}$.\n\n$dx = \\frac{2 \\, dt}{1 + t^2}$ מגזירה $t = \\tan(x/2)$. $\\blacksquare$"),
    P("prf_68_95_99_rule", "thm_68_95_99_rule",
      ["def_normal_distribution", "thm_normal_z_standardization"],
      "**ערכים מטבלת $Z$:** $P(-1 \\leq Z \\leq 1) \\approx 0.6827$; $P(-2 \\leq Z \\leq 2) \\approx 0.9545$; $P(-3 \\leq Z \\leq 3) \\approx 0.9973$.\n\nלפי תיקנון, $X \\in \\mu \\pm k\\sigma$ שקול ל-$Z \\in \\pm k$. $\\blacksquare$",
      method="axiom"),
    P("prf_central_limit_theorem_intuitive", "thm_central_limit_theorem_intuitive",
      ["def_normal_distribution", "thm_expected_value_linearity",
       "thm_variance_sum_independent"],
      "**משפט יסודי שדורש פונקציות-מגדר.** האינטואיציה: סכום משתנים בלתי-תלויים נוטה לבטל הטיות פרטיות, והתוצאה מתפלגת סביב הממוצע המשותף.\n\nההוכחה הפורמלית משתמשת בפונקציות מגדרות אופייניות ($\\phi(t) = E[e^{itX}]$) ובהתכנסות שלהן לפונקציה האופיינית של הנורמלית. $\\blacksquare$",
      method="axiom"),
    P("prf_sum_of_two_squares", "thm_sum_of_two_squares",
      ["def_prime", "def_congruence_mod", "thm_fermat_little"],
      "**משפט קלאסי של פרמה.** ($\\Leftarrow$) אם $p \\equiv 1 \\pmod 4$: לפי משפט וילסון ושיקולי שאריות ריבועיות, $-1$ הוא שארית ריבועית מודולו $p$. בעזרת אלגוריתם אוקלידס על $a, p$ עם $a^2 \\equiv -1$ מקבלים את הפירוק $p = a^2 + b^2$ ע״י הירידה הסופית.\n\n($\\Rightarrow$) אם $p = a^2 + b^2$ ראשוני: ריבועים מודולו $4$ הם $0$ או $1$; סכום שני ריבועים הוא $0, 1, 2$ אבל לא $3$. ראשוני אי-זוגי הוא $\\equiv 1$ או $3 \\pmod 4$, אז כדי שיהיה סכום שני ריבועים — $p \\equiv 1$. $\\blacksquare$",
      method="axiom"),

    # ── Number theory ──
    P("prf_pythagorean_triples_param", "thm_pythagorean_triples_param",
      ["def_pythagorean_triple", "def_divisibility",
       "thm_sum_of_two_squares"],
      "**הוכחה (אוקלידס).** $a^2 + b^2 = c^2$ עם $\\gcd(a, b, c) = 1$. מהזוגיות אחת מ-$a, b$ זוגית והאחרת אי-זוגית; נניח $b$ זוגי.\n\n$b^2 = c^2 - a^2 = (c-a)(c+a)$. שני הגורמים $c \\pm a$ זוגיים (כי $c, a$ אי-זוגיים), נכתבם $c-a = 2u, c+a = 2v$.\n\n$\\left(\\frac{b}{2}\\right)^2 = uv$. כי $\\gcd(u, v) = 1$, שניהם ריבועים: $u = n^2, v = m^2$.\n\nאז $a = m^2 - n^2$, $c = m^2 + n^2$, $b = 2mn$. $\\blacksquare$"),
    P("prf_linear_diophantine_solvable", "thm_linear_diophantine_solvable",
      ["thm_bezout_identity", "def_gcd"],
      "($\\Leftarrow$) אם $\\gcd(a, b) \\mid c$, נכתב $c = \\gcd(a,b) \\cdot k$. מזהות בזו $\\gcd(a, b) = a x_0 + b y_0$. כפל ב-$k$: $c = a(kx_0) + b(ky_0)$.\n\n($\\Rightarrow$) אם $ax + by = c$ עבור שלמים, אז כל מחלק משותף של $a, b$ מחלק את הצד השמאלי ולכן את $c$. בפרט $\\gcd(a,b) \\mid c$. $\\blacksquare$"),
    P("prf_modular_inverse_computation", "thm_modular_inverse_computation",
      ["thm_bezout_identity", "thm_euler_theorem", "def_congruence_mod"],
      "($\\Leftarrow$) אם $\\gcd(a, n) = 1$: מזהות בזו $1 = ax + ny$. מודולו $n$: $ax \\equiv 1$, אז $x \\equiv a^{-1}$.\n\nאלטרנטיבית מאוילר: $a^{\\varphi(n)} \\equiv 1 \\pmod n$, אז $a^{-1} \\equiv a^{\\varphi(n) - 1}$.\n\n($\\Rightarrow$) אם $a^{-1}$ קיים: $a \\cdot a^{-1} \\equiv 1 \\pmod n$, כלומר $a a^{-1} - 1 = n k$. לכן $\\gcd(a, n) \\mid 1$, וזה $1$. $\\blacksquare$"),
]
