"""Chunk 7 — 100 claims: analytic geometry, conics, statistics, 3D vectors+solids,
   inverse trig, series convergence tests, number theory, inequalities, advanced integration.
"""
from __future__ import annotations

from core.models import Claim, Course, Proof


CANON = "canonical"


def C(cid, kind, course, topic, stmt):
    return Claim(id=cid, kind=kind, status=CANON, course=course,
                 topic=topic, statement=stmt)


def P(pid, cid, deps, body, method="informal", status="reviewed", canonical=True):
    return Proof(id=pid, claim_id=cid, dependencies=list(deps), body=body,
                 method=method, status=status, is_canonical=canonical)


HS3 = "math_hs_3"
HS4 = "math_hs_4"
HS5 = "math_hs_5"


COURSES: list[Course] = []  # no new courses this round


CLAIMS = [
    # ═══ Analytic Geometry 2D (math_hs_3) ═══
    C("def_coordinate_plane", "definition", HS3, "גאומטריה אנליטית",
      r"**מערכת צירים (קרטזית):** המישור $\mathbb{R}^2$ עם שני צירים מאונכים ($x$ ו-$y$) הנפגשים בראשית $(0, 0)$. כל נקודה ב$במישור מיוצגת ע״י זוג סדור $(x, y)$."),
    C("thm_distance_formula_2d", "theorem", HS3, "גאומטריה אנליטית",
      r"**נוסחת המרחק במישור:** המרחק בין $(x_1, y_1)$ ל-$(x_2, y_2)$ הוא $d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$."),
    C("thm_midpoint_formula_2d", "theorem", HS3, "גאומטריה אנליטית",
      r"**נוסחת האמצע:** אמצע הקטע בין $(x_1, y_1)$ ל-$(x_2, y_2)$ הוא $\left(\frac{x_1 + x_2}{2}, \frac{y_1 + y_2}{2}\right)$."),
    C("thm_two_point_form_of_line", "theorem", HS3, "גאומטריה אנליטית",
      r"**משוואת ישר דרך שתי נקודות:** הישר דרך $(x_1, y_1)$ ו-$(x_2, y_2)$: $y - y_1 = \frac{y_2 - y_1}{x_2 - x_1}(x - x_1)$."),
    C("thm_slope_intercept_form", "theorem", HS3, "גאומטריה אנליטית",
      r"**צורת שיפוע-חותך:** משוואת ישר $y = m x + b$, כאשר $m$ השיפוע ו-$b$ החותך בציר $y$."),
    C("thm_general_form_of_line", "theorem", HS3, "גאומטריה אנליטית",
      r"**צורה כללית של ישר:** $a x + b y + c = 0$ עם $a, b$ לא שניהם אפס. הצורה הזו תופסת גם ישרים אנכיים (כאשר $b = 0$)."),
    C("thm_parallel_lines_equal_slopes", "theorem", HS3, "גאומטריה אנליטית",
      r"**ישרים מקבילים — שיפוע שווה:** שני ישרים לא אנכיים מקבילים אם ורק אם שיפועיהם שווים."),
    C("thm_perpendicular_lines_slope_product", "theorem", HS3, "גאומטריה אנליטית",
      r"**ישרים מאונכים — מכפלת שיפועים:** שני ישרים (לא ציר $y$) מאונכים אם ורק אם מכפלת שיפועיהם היא $-1$, כלומר $m_1 \cdot m_2 = -1$."),
    C("thm_distance_point_to_line_2d", "theorem", HS3, "גאומטריה אנליטית",
      r"**מרחק מנקודה לישר:** המרחק מהנקודה $(x_0, y_0)$ לישר $a x + b y + c = 0$ הוא $d = \frac{|a x_0 + b y_0 + c|}{\sqrt{a^2 + b^2}}$."),
    C("thm_angle_between_lines_2d", "theorem", HS3, "גאומטריה אנליטית",
      r"**זווית בין ישרים:** הזווית $\theta$ בין שני ישרים עם שיפועים $m_1, m_2$ מקיימת $\tan\theta = \left|\frac{m_1 - m_2}{1 + m_1 m_2}\right|$."),
    C("thm_equation_of_circle", "theorem", HS3, "גאומטריה אנליטית",
      r"**משוואת מעגל:** מעגל עם מרכז $(a, b)$ ורדיוס $r$: $(x - a)^2 + (y - b)^2 = r^2$."),
    C("thm_circle_general_form", "theorem", HS3, "גאומטריה אנליטית",
      r"**צורה כללית של מעגל:** $x^2 + y^2 + D x + E y + F = 0$ — שקול ל-$(x + D/2)^2 + (y + E/2)^2 = (D^2 + E^2)/4 - F$ (השלמת ריבוע)."),

    # ═══ 3D vectors and analytic geometry (math_hs_5) ═══
    C("thm_distance_3d", "theorem", HS5, "גאומטריה אנליטית 3D",
      r"**מרחק במרחב:** $d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2 + (z_2 - z_1)^2}$."),
    C("thm_midpoint_3d", "theorem", HS5, "גאומטריה אנליטית 3D",
      r"**אמצע קטע במרחב:** $\left(\frac{x_1+x_2}{2}, \frac{y_1+y_2}{2}, \frac{z_1+z_2}{2}\right)$."),
    C("def_cross_product", "definition", HS5, "וקטורים",
      r"**מכפלה וקטורית:** $\vec{u} \times \vec{v} := (u_2 v_3 - u_3 v_2, \, u_3 v_1 - u_1 v_3, \, u_1 v_2 - u_2 v_1)$ (וקטור ב-$\mathbb{R}^3$)."),
    C("thm_cross_product_perpendicular", "theorem", HS5, "וקטורים",
      r"**מכפלה וקטורית מאונכת:** $\vec{u} \times \vec{v}$ מאונך הן ל-$\vec{u}$ והן ל-$\vec{v}$."),
    C("thm_cross_product_magnitude", "theorem", HS5, "וקטורים",
      r"**גודל מכפלה וקטורית:** $|\vec{u} \times \vec{v}| = |\vec{u}| \cdot |\vec{v}| \cdot \sin\theta$, כאשר $\theta$ הזווית ביניהם. גודל זה שווה לשטח המקבילית הנמתחת על-ידי הוקטורים."),
    C("def_scalar_triple_product", "definition", HS5, "וקטורים",
      r"**מכפלה משולשת:** $[\vec{u}, \vec{v}, \vec{w}] := \vec{u} \cdot (\vec{v} \times \vec{w})$. גודלה בערך מוחלט שווה לנפח המקבילון."),
    C("def_vector_equation_of_line_3d", "definition", HS5, "גאומטריה אנליטית 3D",
      r"**משוואה וקטורית של ישר במרחב:** $\vec{r}(t) = \vec{r_0} + t \cdot \vec{v}$, כאשר $\vec{r_0}$ נקודה על הישר ו-$\vec{v}$ וקטור כיוון."),
    C("def_parametric_equation_of_line_3d", "definition", HS5, "גאומטריה אנליטית 3D",
      r"**משוואה פרמטרית של ישר במרחב:** $x = x_0 + t v_1$, $y = y_0 + t v_2$, $z = z_0 + t v_3$."),
    C("def_equation_of_plane", "definition", HS5, "גאומטריה אנליטית 3D",
      r"**משוואת מישור:** $a x + b y + c z = d$, כאשר $(a, b, c)$ הוא וקטור נורמלי למישור."),
    C("thm_distance_point_to_plane", "theorem", HS5, "גאומטריה אנליטית 3D",
      r"**מרחק מנקודה למישור:** $d = \frac{|a x_0 + b y_0 + c z_0 - d|}{\sqrt{a^2 + b^2 + c^2}}$."),
    C("thm_angle_between_planes", "theorem", HS5, "גאומטריה אנליטית 3D",
      r"**זווית בין מישורים:** הזווית בין שני מישורים שווה לזווית בין הנורמלים שלהם (או למשלימתה ל-$180°$)."),

    # ═══ Conic sections (math_hs_5) ═══
    C("def_conic_section", "definition", HS5, "חתכי חרוט",
      r"**חתך חרוט:** עקומה המתקבלת מחיתוך חרוט מעגלי כפול במישור. סוגים: מעגל, אליפסה, פרבולה, היפרבולה."),
    C("def_parabola_geometric", "definition", HS5, "חתכי חרוט",
      r"**פרבולה (גאומטרית):** אוסף הנקודות במישור שמרחקן מנקודה קבועה (**מוקד**) שווה למרחקן מישר קבוע (**מדריך**)."),
    C("thm_parabola_canonical_equation", "theorem", HS5, "חתכי חרוט",
      r"**משוואת פרבולה קנונית:** עבור מוקד $(0, p)$ ומדריך $y = -p$: $y = \frac{x^2}{4p}$, או באופן שקול $x^2 = 4 p y$."),
    C("def_ellipse_geometric", "definition", HS5, "חתכי חרוט",
      r"**אליפסה (גאומטרית):** אוסף הנקודות שסכום מרחקיהן משני מוקדים נתונים הוא קבוע ($2a$, גדול מהמרחק בין המוקדים)."),
    C("thm_ellipse_canonical_equation", "theorem", HS5, "חתכי חרוט",
      r"**משוואת אליפסה קנונית:** עם מוקדים בציר $x$ במרחק $c$ מהמרכז, חצי-ציר ראשי $a$ ($a > c$), חצי-ציר משני $b = \sqrt{a^2 - c^2}$: $\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1$."),
    C("def_hyperbola_geometric", "definition", HS5, "חתכי חרוט",
      r"**היפרבולה (גאומטרית):** אוסף הנקודות שהפרש המרחקים שלהן משני מוקדים נתונים הוא קבוע בערך מוחלט."),
    C("thm_hyperbola_canonical_equation", "theorem", HS5, "חתכי חרוט",
      r"**משוואת היפרבולה קנונית:** $\frac{x^2}{a^2} - \frac{y^2}{b^2} = 1$, עם אסימפטוטות $y = \pm \frac{b}{a} x$."),
    C("def_eccentricity", "definition", HS5, "חתכי חרוט",
      r"**אקסצנטריות:** עבור חתך חרוט, $e := \frac{c}{a}$ (יחס מרחק מוקד ממרכז לחצי-ציר ראשי). $e < 1$: אליפסה, $e = 1$: פרבולה, $e > 1$: היפרבולה."),

    # ═══ Statistics (math_hs_4) ═══
    C("def_data_set", "definition", HS4, "סטטיסטיקה",
      r"**מערך נתונים:** סדרה סופית של מספרים $x_1, x_2, \ldots, x_n$ המייצגת תצפיות."),
    C("def_mean", "definition", HS4, "סטטיסטיקה",
      r"**ממוצע (חשבוני):** $\bar{x} := \frac{1}{n} \sum_{i=1}^n x_i$."),
    C("def_median", "definition", HS4, "סטטיסטיקה",
      r"**חציון:** הערך באמצע הסדרה הממוינת. עבור $n$ אי-זוגי, הערך $\frac{n+1}{2}$. עבור $n$ זוגי, ממוצע שני האמצעיים."),
    C("def_mode", "definition", HS4, "סטטיסטיקה",
      r"**שכיח:** הערך המופיע הכי הרבה פעמים בסדרה. ייתכן שכיח יחיד, מספר שכיחים, או אין."),
    C("def_range_stats", "definition", HS4, "סטטיסטיקה",
      r"**טווח (סטטיסטיקה):** $\text{range} := \max(x_i) - \min(x_i)$."),
    C("def_variance", "definition", HS4, "סטטיסטיקה",
      r"**שונות:** $\sigma^2 := \frac{1}{n} \sum_{i=1}^n (x_i - \bar{x})^2$. מודדת פיזור סביב הממוצע."),
    C("def_standard_deviation", "definition", HS4, "סטטיסטיקה",
      r"**סטיית תקן:** $\sigma := \sqrt{\sigma^2}$ — שורש השונות. ביחידות של הנתונים המקוריים."),
    C("thm_variance_alternative_formula", "theorem", HS4, "סטטיסטיקה",
      r"**נוסחה חלופית לשונות:** $\sigma^2 = \frac{1}{n} \sum x_i^2 - \bar{x}^2$ — ממוצע הריבועים פחות ריבוע הממוצע."),
    C("def_frequency_distribution", "definition", HS4, "סטטיסטיקה",
      r"**התפלגות שכיחויות:** טבלה המקצה לכל ערך (או טווח) את מספר הפעמים שהוא הופיע."),
    C("def_quartile", "definition", HS4, "סטטיסטיקה",
      r"**רבעון:** הערך שמחלק את הנתונים לרבעים. $Q_1$ — אחוזון 25, $Q_2 = $ חציון, $Q_3$ — אחוזון 75."),
    C("def_iqr", "definition", HS4, "סטטיסטיקה",
      r"**טווח בין-רבעוני:** $\text{IQR} := Q_3 - Q_1$. מודד פיזור עמיד לחריגים."),
    C("def_correlation_coefficient", "definition", HS4, "סטטיסטיקה",
      r"**מקדם מתאם (פירסון):** $r := \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{n \cdot \sigma_x \cdot \sigma_y}$, $-1 \leq r \leq 1$. $r$ קרוב ל-$1$ או $-1$ מציין יחס לינארי חזק."),

    # ═══ 3D solid geometry (math_hs_5) ═══
    C("def_prism", "definition", HS5, "גאומטריה במרחב",
      r"**מנסרה:** גוף תלת-מימדי עם שני בסיסים זהים מקבילים, ופאות צד מקבילות שמחברות אותם."),
    C("def_cylinder", "definition", HS5, "גאומטריה במרחב",
      r"**גליל:** גוף שנוצר מהזזת עיגול לאורך ציר מאונך לבסיס. אם הציר מאונך — גליל ישר."),
    C("def_cone", "definition", HS5, "גאומטריה במרחב",
      r"**חרוט:** גוף עם בסיס מעגלי וקודקוד שאינו במישור הבסיס. הגובה $h$ הוא המרחק האנכי מהקודקוד לבסיס."),
    C("def_sphere", "definition", HS5, "גאומטריה במרחב",
      r"**כדור:** אוסף הנקודות במרחב שמרחקן מנקודה קבועה (**מרכז**) שווה לרדיוס $r$."),
    C("def_pyramid", "definition", HS5, "גאומטריה במרחב",
      r"**פירמידה:** גוף עם בסיס פוליגונלי וקודקוד אחד מחוץ למישור הבסיס. הצלעות לקודקוד יוצרות פאות צד משולשות."),
    C("thm_cylinder_volume", "theorem", HS5, "גאומטריה במרחב",
      r"**נפח גליל:** $V = \pi r^2 h$ — שטח בסיס כפול גובה."),
    C("thm_cone_volume", "theorem", HS5, "גאומטריה במרחב",
      r"**נפח חרוט:** $V = \frac{1}{3} \pi r^2 h$ — שליש מנפח הגליל המתאים."),
    C("thm_sphere_volume", "theorem", HS5, "גאומטריה במרחב",
      r"**נפח כדור:** $V = \frac{4}{3} \pi r^3$."),

    # ═══ Advanced trig (math_hs_4) ═══
    C("def_secant_cosecant_cotangent", "definition", HS4, "טריגונומטריה מתקדמת",
      r"**סקנט, קוסקנט, קוטנגנס:** $\sec\theta := \frac{1}{\cos\theta}$, $\csc\theta := \frac{1}{\sin\theta}$, $\cot\theta := \frac{1}{\tan\theta} = \frac{\cos\theta}{\sin\theta}$ (כאשר המכנים אינם אפס)."),
    C("def_arcsin", "definition", HS4, "טריגונומטריה מתקדמת",
      r"**ארקסינוס:** $\arcsin: [-1, 1] \to [-\frac{\pi}{2}, \frac{\pi}{2}]$, הפונקציה ההפוכה של $\sin$ מצומצם לתחום זה."),
    C("def_arccos", "definition", HS4, "טריגונומטריה מתקדמת",
      r"**ארקקוסינוס:** $\arccos: [-1, 1] \to [0, \pi]$, ההפוכה של $\cos$ מצומצם."),
    C("def_arctan", "definition", HS4, "טריגונומטריה מתקדמת",
      r"**ארקטנגנס:** $\arctan: \mathbb{R} \to (-\frac{\pi}{2}, \frac{\pi}{2})$, ההפוכה של $\tan$ מצומצם."),
    C("thm_sum_to_product_sin", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**סכום סינוסים למכפלה:** $\sin\alpha + \sin\beta = 2 \sin\frac{\alpha + \beta}{2} \cos\frac{\alpha - \beta}{2}$."),
    C("thm_sum_to_product_cos", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**סכום קוסינוסים למכפלה:** $\cos\alpha + \cos\beta = 2 \cos\frac{\alpha + \beta}{2} \cos\frac{\alpha - \beta}{2}$."),
    C("thm_product_to_sum_sin_cos", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**מכפלה לסכום:** $\sin\alpha \cos\beta = \frac{1}{2}[\sin(\alpha + \beta) + \sin(\alpha - \beta)]$."),
    C("thm_half_angle_sin", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**זווית חצי — סינוס:** $\sin^2\frac{\alpha}{2} = \frac{1 - \cos\alpha}{2}$."),
    C("thm_half_angle_cos", "theorem", HS4, "טריגונומטריה מתקדמת",
      r"**זווית חצי — קוסינוס:** $\cos^2\frac{\alpha}{2} = \frac{1 + \cos\alpha}{2}$."),
    C("thm_inverse_trig_derivatives", "theorem", HS5, "נגזרות פונקציות",
      r"**נגזרות פונקציות טריגו הפוכות:** $(\arcsin x)' = \frac{1}{\sqrt{1 - x^2}}$, $(\arccos x)' = -\frac{1}{\sqrt{1 - x^2}}$, $(\arctan x)' = \frac{1}{1 + x^2}$."),

    # ═══ Series convergence (math_hs_5) ═══
    C("def_partial_sum", "definition", HS5, "טורים",
      r"**סכום חלקי:** עבור סדרה $(a_n)$, הסכום החלקי ה-$n$-י הוא $S_n := a_1 + a_2 + \cdots + a_n$."),
    C("def_series_convergence", "definition", HS5, "טורים",
      r"**התכנסות טור:** הטור $\sum_{n=1}^{\infty} a_n$ **מתכנס** אם סדרת הסכומים החלקיים $(S_n)$ מתכנסת. הגבול נקרא **סכום הטור**."),
    C("thm_p_series_convergence", "theorem", HS5, "טורים",
      r"**מבחן ה-$p$-טור:** $\sum_{n=1}^{\infty} \frac{1}{n^p}$ מתכנס אם ורק אם $p > 1$. בפרט $\sum \frac{1}{n}$ (טור הרמוני) מתבדר."),
    C("thm_comparison_test", "theorem", HS5, "טורים",
      r"**מבחן ההשוואה:** אם $0 \leq a_n \leq b_n$ לכל $n$ גדול מספיק: אם $\sum b_n$ מתכנס אז גם $\sum a_n$; אם $\sum a_n$ מתבדר אז גם $\sum b_n$."),
    C("thm_ratio_test", "theorem", HS5, "טורים",
      r"**מבחן המנה:** עבור $\sum a_n$ עם $a_n > 0$, נסמן $L := \lim_{n \to \infty} \frac{a_{n+1}}{a_n}$. אם $L < 1$ הטור מתכנס; אם $L > 1$ מתבדר; אם $L = 1$ המבחן לא קובע."),
    C("thm_alternating_series_leibniz", "theorem", HS5, "טורים",
      r"**מבחן לייבניץ לטורים מתחלפים:** טור $\sum (-1)^n a_n$ עם $a_n > 0$ מונוטונית יורדת ל-$0$ מתכנס."),
    C("thm_telescoping_series", "theorem", HS5, "טורים",
      r"**טור טלסקופי:** עבור טור מהצורה $\sum (b_n - b_{n+1})$: $S_n = b_1 - b_{n+1}$, ולכן הטור מתכנס אם ורק אם $b_n$ מתכנסת, אז $S = b_1 - \lim b_n$."),
    C("thm_necessary_condition_convergence", "theorem", HS5, "טורים",
      r"**תנאי הכרחי להתכנסות:** אם $\sum a_n$ מתכנס, אז $\lim_{n \to \infty} a_n = 0$. (ההפך לא תמיד נכון — הטור ההרמוני דוגמה.)"),

    # ═══ Number theory advanced (math_hs_5) ═══
    C("def_gcd", "definition", HS5, "תורת המספרים",
      r"**מחלק משותף מקסימלי (GCD):** עבור $a, b$ שלמים לא שניהם אפס, $\gcd(a, b)$ הוא המספר החיובי הגדול ביותר שמחלק את שניהם."),
    C("def_lcm", "definition", HS5, "תורת המספרים",
      r"**כפולה משותפת מינימלית (LCM):** $\text{lcm}(a, b)$ הוא המספר החיובי הקטן ביותר שגם $a$ וגם $b$ מחלקים אותו."),
    C("thm_gcd_lcm_product", "theorem", HS5, "תורת המספרים",
      r"**$\gcd \cdot \text{lcm} = ab$:** עבור $a, b > 0$, $\gcd(a, b) \cdot \text{lcm}(a, b) = a \cdot b$."),
    C("thm_euclidean_algorithm", "theorem", HS5, "תורת המספרים",
      r"**אלגוריתם אוקלידס:** $\gcd(a, b) = \gcd(b, r)$ כאשר $a = b q + r$. חזרה על השלב עד $r = 0$ — אז $\gcd = b$."),
    C("thm_bezout_identity", "theorem", HS5, "תורת המספרים",
      r"**זהות בזו:** עבור $a, b$ לא שניהם אפס, קיימים שלמים $x, y$ כך ש-$a x + b y = \gcd(a, b)$."),
    C("def_congruence_mod", "definition", HS5, "תורת המספרים",
      r"**קונגרואנציה מודולו $n$:** $a \equiv b \pmod n$ אם $n \mid (a - b)$, כלומר $a$ ו-$b$ נותנים את אותה שארית בחילוק ב-$n$."),
    C("thm_modular_arithmetic_properties", "theorem", HS5, "תורת המספרים",
      r"**תכונות אריתמטיקה מודולרית:** אם $a \equiv b \pmod n$ ו-$c \equiv d \pmod n$, אז $a + c \equiv b + d$, $a - c \equiv b - d$, $a c \equiv b d$ (הכל $\pmod n$)."),
    C("thm_fermat_little", "theorem", HS5, "תורת המספרים",
      r"**משפט פרמה הקטן:** עבור ראשוני $p$ ושלם $a$ עם $\gcd(a, p) = 1$: $a^{p-1} \equiv 1 \pmod p$."),

    # ═══ Classical inequalities (math_hs_5) ═══
    C("thm_squared_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**$a^2 + b^2 \geq 2ab$:** לכל $a, b \in \mathbb{R}$. שוויון אם ורק אם $a = b$."),
    C("thm_am_gm_two_variables", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון הממוצעים (חשבוני-הנדסי, שני משתנים):** לכל $a, b \geq 0$: $\frac{a + b}{2} \geq \sqrt{a b}$. שוויון אם ורק אם $a = b$."),
    C("thm_am_gm_n_variables", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון הממוצעים ($n$ משתנים):** לכל $a_1, \ldots, a_n \geq 0$: $\frac{a_1 + \cdots + a_n}{n} \geq \sqrt[n]{a_1 \cdots a_n}$."),
    C("thm_cauchy_schwarz_inequality_vectors", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון קושי-שוורץ:** לכל וקטורים $\vec{u}, \vec{v}$: $|\vec{u} \cdot \vec{v}| \leq |\vec{u}| \cdot |\vec{v}|$. שוויון אם ורק אם הוקטורים מקבילים."),
    C("thm_triangle_inequality_vectors", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון המשולש (וקטורי):** לכל $\vec{u}, \vec{v}$: $|\vec{u} + \vec{v}| \leq |\vec{u}| + |\vec{v}|$."),
    C("thm_reverse_triangle_inequality", "theorem", HS5, "אי-שוויונים קלאסיים",
      r"**אי-שוויון המשולש ההפכי:** לכל $a, b$: $||a| - |b|| \leq |a - b|$ (גרסה נומרית); ולכל וקטורים: $||\vec{u}| - |\vec{v}|| \leq |\vec{u} - \vec{v}|$."),

    # ═══ Advanced integration (math_hs_5) ═══
    C("def_improper_integral", "definition", HS5, "אינטגרל מתקדם",
      r"**אינטגרל לא-אמיתי (גבול אינסופי):** $\int_a^{\infty} f(x) \, dx := \lim_{b \to \infty} \int_a^b f(x) \, dx$, אם הגבול קיים סופי — מתכנס; אחרת — מתבדר."),
    C("def_improper_integral_singular", "definition", HS5, "אינטגרל מתקדם",
      r"**אינטגרל לא-אמיתי (סינגולריות):** אם $f$ אינה חסומה בנקודה $c \in [a, b]$, מגדירים $\int_a^b f$ ע״י גבול שמתקרב ל-$c$ ומתעלם משם."),
    C("def_partial_fraction", "definition", HS5, "אינטגרל מתקדם",
      r"**פיצול לשברים חלקיים:** פירוק שבר רציונלי $\frac{P(x)}{Q(x)}$ לסכום שברים פשוטים יותר (לפי גורמי $Q$). שיטה לאינטגרציה של פונקציות רציונליות."),
    C("thm_volume_by_shells", "theorem", HS5, "יישומי אינטגרל",
      r"**נפח גוף סיבוב — שיטת המעטפות:** עבור סיבוב הגרף $f(x) \geq 0$ ב-$[a, b]$ סביב ציר $y$: $V = 2\pi \int_a^b x \cdot f(x) \, dx$."),
    C("thm_surface_of_revolution", "theorem", HS5, "יישומי אינטגרל",
      r"**שטח פני גוף סיבוב:** עבור סיבוב $f$ סביב ציר $x$: $S = 2\pi \int_a^b f(x) \sqrt{1 + f'(x)^2} \, dx$."),
    C("def_average_value_function", "definition", HS5, "יישומי אינטגרל",
      r"**ערך ממוצע של פונקציה:** $\bar{f} := \frac{1}{b - a} \int_a^b f(x) \, dx$ — האנלוג הרציף של ממוצע חשבוני."),
    C("thm_mean_value_for_integrals", "theorem", HS5, "יישומי אינטגרל",
      r"**משפט ערך ממוצע לאינטגרלים:** אם $f$ רציפה ב-$[a, b]$, קיים $c \in [a, b]$ כך ש-$f(c) = \frac{1}{b - a} \int_a^b f$ (כלומר הערך הממוצע מתקבל באיזושהי נקודה)."),
    C("thm_integration_logarithmic", "theorem", HS5, "אינטגרל מתקדם",
      r"**אינטגרציה לוגריתמית:** $\int \frac{f'(x)}{f(x)} \, dx = \ln|f(x)| + C$ — מקרה פרטי חשוב של שיטת ההצבה."),

    # ═══ Misc additional (mixed levels) ═══
    C("def_implicit_function", "definition", HS5, "נגזרת מתקדמת",
      r"**פונקציה סתומה:** משוואה $F(x, y) = 0$ המגדירה $y$ כפונקציה (אולי מקומית) של $x$ ללא נוסחה מפורשת."),
    C("thm_implicit_differentiation", "theorem", HS5, "נגזרת מתקדמת",
      r"**גזירה סתומה:** אם $F(x, y(x)) = 0$ ו-$y$ גזירה, גוזרים את שני האגפים לפי $x$ (תוך שימוש בכלל השרשרת ל-$y$) ופותרים ל-$y'$."),
    C("def_related_rates", "definition", HS5, "יישומי נגזרת",
      r"**שיעורי שינוי קשורים:** בעיות שבהן שני גדלים תלויים בזמן ($x(t), y(t)$), מקיימים יחס $F(x, y) = 0$, וגוזרים לפי $t$ כדי לקשר את $\frac{dx}{dt}$ ו-$\frac{dy}{dt}$."),
    C("thm_optimization_strategy", "theorem", HS5, "יישומי נגזרת",
      r"**אסטרטגיית אופטימיזציה:** למציאת קיצון: (1) זהה את הפונקציה לאופטימיזציה ואת המשתנים; (2) הבע במשתנה יחיד תוך שימוש באילוצים; (3) גזור והשווה לאפס; (4) בדוק עם הנגזרת השנייה או השוואת ערכי קצה."),
    C("def_exponential_growth_model", "definition", HS4, "מודלים",
      r"**מודל גדילה מעריכית:** $y(t) = y_0 \cdot e^{k t}$ — הקצב הוא פרופורציוני לערך הנוכחי. $k > 0$ גדילה, $k < 0$ דעיכה."),
    C("thm_exponential_growth_derivative", "theorem", HS5, "מודלים",
      r"**מאפיין מעריכי:** $y(t) = y_0 e^{kt}$ הוא הפתרון היחיד ל-$y'(t) = k \cdot y(t)$ עם $y(0) = y_0$."),
    C("def_half_life", "definition", HS4, "מודלים",
      r"**זמן מחצית חיים:** עבור דעיכה מעריכית $y = y_0 e^{-\lambda t}$, $T_{1/2}$ הוא הזמן שבו הכמות יורדת לחצי: $T_{1/2} = \frac{\ln 2}{\lambda}$."),
    C("def_real_valued_function", "definition", HS3, "פונקציות",
      r"**פונקציה ממשית של משתנה ממשי:** פונקציה $f: D \to \mathbb{R}$ עם $D \subseteq \mathbb{R}$."),
    C("def_piecewise_function", "definition", HS3, "פונקציות",
      r"**פונקציה מוגדרת בקטעים:** פונקציה שמוגדרת ע״י נוסחאות שונות בקטעים שונים של תחום ההגדרה."),
    C("thm_chord_in_circle_length", "theorem", HS3, "גאומטריה",
      r"**אורך מיתר במעגל:** מיתר באורך $2\sqrt{r^2 - d^2}$ כאשר $r$ רדיוס המעגל ו-$d$ המרחק מהמרכז למיתר."),
]


PROOFS = [
    # ── Analytic geometry 2D ──
    P("prf_distance_formula_2d", "thm_distance_formula_2d",
      ["thm_pythagoras", "def_coordinate_plane"],
      "ניצור משולש ישר-זווית עם הניצבים מקבילים לצירים: ניצב אופקי $|x_2 - x_1|$, ניצב אנכי $|y_2 - y_1|$, יתר $d$ — המרחק המבוקש.\n\nלפי פיתגורס: $d^2 = (x_2 - x_1)^2 + (y_2 - y_1)^2$, ולכן $d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$. $\\blacksquare$"),
    P("prf_midpoint_formula_2d", "thm_midpoint_formula_2d",
      ["def_coordinate_plane"],
      "האמצע הוא הנקודה שבה כל קואורדינטה היא ממוצע הקואורדינטות המקבילות:\n\n$x_m = \\frac{x_1 + x_2}{2}$, $y_m = \\frac{y_1 + y_2}{2}$. (תכונה אריתמטית של אמצע על הציר.) $\\blacksquare$"),
    P("prf_parallel_lines_equal_slopes", "thm_parallel_lines_equal_slopes",
      ["thm_slope_intercept_form", "def_slope_between_points"],
      "שני ישרים $y = m_1 x + b_1$ ו-$y = m_2 x + b_2$ מקבילים אם ורק אם אין להם נקודת חיתוך משותפת.\n\nחיתוך: $m_1 x + b_1 = m_2 x + b_2 \\Rightarrow (m_1 - m_2) x = b_2 - b_1$. אין פתרון רק כאשר $m_1 = m_2$ ו-$b_1 \\neq b_2$. במקרה $m_1 = m_2$ ו-$b_1 = b_2$ הישרים מתלכדים. $\\blacksquare$"),
    P("prf_perpendicular_lines_slope_product", "thm_perpendicular_lines_slope_product",
      ["thm_slope_intercept_form", "thm_pythagoras"],
      "אם זווית הישר הראשון $\\alpha$ והשני $\\alpha + 90°$, אז $m_1 = \\tan\\alpha$ ו-$m_2 = \\tan(\\alpha + 90°) = -\\cot\\alpha = -\\frac{1}{\\tan\\alpha}$.\n\nלכן $m_1 \\cdot m_2 = \\tan\\alpha \\cdot \\left(-\\frac{1}{\\tan\\alpha}\\right) = -1$. $\\blacksquare$"),
    P("prf_equation_of_circle", "thm_equation_of_circle",
      ["def_circle", "thm_distance_formula_2d"],
      "מהגדרת מעגל, נקודה $(x, y)$ במעגל אם ורק אם המרחק שלה ממרכז $(a, b)$ הוא $r$.\n\nלפי נוסחת המרחק: $\\sqrt{(x - a)^2 + (y - b)^2} = r$, ובהעלאה בריבוע: $(x - a)^2 + (y - b)^2 = r^2$. $\\blacksquare$"),
    P("prf_circle_general_form", "thm_circle_general_form",
      ["thm_equation_of_circle", "thm_difference_of_squares"],
      "$(x - a)^2 + (y - b)^2 = r^2$ נפתח: $x^2 - 2ax + a^2 + y^2 - 2by + b^2 = r^2$, ובסידור: $x^2 + y^2 + D x + E y + F = 0$ עם $D = -2a$, $E = -2b$, $F = a^2 + b^2 - r^2$.\n\nההפך — השלמת ריבועים: $x^2 + Dx = (x + D/2)^2 - D^2/4$, ובדומה ל-$y$. נקבל מעגל עם מרכז $(-D/2, -E/2)$ ורדיוס בריבוע $D^2/4 + E^2/4 - F$. $\\blacksquare$"),

    # ── 3D vectors ──
    P("prf_distance_3d", "thm_distance_3d",
      ["thm_pythagoras", "thm_distance_formula_2d"],
      "פיתגורס במרחב: ההפרשים $\\Delta x, \\Delta y, \\Delta z$ יוצרים תיבה. בה האלכסון הוא $\\sqrt{\\Delta x^2 + \\Delta y^2 + \\Delta z^2}$ (פיתגורס פעמיים: באלכסון של פאת בסיס ואז עליה לקודקוד עליון). $\\blacksquare$"),
    P("prf_cross_product_perpendicular", "thm_cross_product_perpendicular",
      ["def_cross_product", "def_dot_product"],
      "$\\vec{u} \\cdot (\\vec{u} \\times \\vec{v}) = u_1(u_2 v_3 - u_3 v_2) + u_2(u_3 v_1 - u_1 v_3) + u_3(u_1 v_2 - u_2 v_1)$\n\n$= u_1 u_2 v_3 - u_1 u_3 v_2 + u_2 u_3 v_1 - u_2 u_1 v_3 + u_3 u_1 v_2 - u_3 u_2 v_1 = 0$ (זוגות מבטלים זה את זה).\n\nבאופן דומה $\\vec{v} \\cdot (\\vec{u} \\times \\vec{v}) = 0$. $\\blacksquare$"),
    P("prf_cross_product_magnitude", "thm_cross_product_magnitude",
      ["def_cross_product", "def_vector_magnitude", "thm_sin_cos_pythagorean",
       "thm_dot_product_geometric"],
      "$|\\vec{u} \\times \\vec{v}|^2 = |\\vec{u}|^2 |\\vec{v}|^2 - (\\vec{u} \\cdot \\vec{v})^2$ (זהות לגראנז׳, מתקבלת מפתיחה ישירה של הגדרת המכפלה הוקטורית).\n\n$= |\\vec{u}|^2 |\\vec{v}|^2 - |\\vec{u}|^2 |\\vec{v}|^2 \\cos^2\\theta = |\\vec{u}|^2 |\\vec{v}|^2 \\sin^2\\theta$.\n\nשורש: $|\\vec{u} \\times \\vec{v}| = |\\vec{u}| |\\vec{v}| |\\sin\\theta| = |\\vec{u}| |\\vec{v}| \\sin\\theta$ (זווית $\\theta \\in [0, \\pi]$ מבטיחה $\\sin \\geq 0$). $\\blacksquare$"),
    P("prf_distance_point_to_plane", "thm_distance_point_to_plane",
      ["def_equation_of_plane", "def_dot_product", "def_vector_magnitude"],
      "הנורמל למישור הוא $\\vec{n} = (a, b, c)$. ההיטל של וקטור מנקודה במישור $\\vec{P_0}$ לנקודה $\\vec{P}$ על כיוון $\\vec{n}$ נותן את המרחק:\n\n$d = \\frac{|\\vec{n} \\cdot (\\vec{P} - \\vec{P_0})|}{|\\vec{n}|} = \\frac{|a x_0 + b y_0 + c z_0 - d|}{\\sqrt{a^2 + b^2 + c^2}}$. $\\blacksquare$"),

    # ── Statistics ──
    P("prf_variance_alternative_formula", "thm_variance_alternative_formula",
      ["def_variance", "def_mean", "ax_distributive_law"],
      "$\\sigma^2 = \\frac{1}{n}\\sum (x_i - \\bar{x})^2 = \\frac{1}{n}\\sum (x_i^2 - 2 x_i \\bar{x} + \\bar{x}^2)$\n\n$= \\frac{1}{n}\\sum x_i^2 - 2\\bar{x} \\cdot \\frac{1}{n}\\sum x_i + \\frac{1}{n} \\cdot n \\cdot \\bar{x}^2 = \\frac{1}{n}\\sum x_i^2 - 2 \\bar{x}^2 + \\bar{x}^2 = \\frac{1}{n}\\sum x_i^2 - \\bar{x}^2$. $\\blacksquare$"),

    # ── Solid geometry ──
    P("prf_cylinder_volume", "thm_cylinder_volume",
      ["def_cylinder", "thm_volume_of_revolution_disc"],
      "גליל ישר ברדיוס $r$ וגובה $h$ הוא גוף הסיבוב של מלבן $[0, h] \\times \\{r\\}$ סביב ציר $x$ (אם הציר מאוזן).\n\nשטח בסיס: $\\pi r^2$. סכימה לאורך הציר: $V = \\pi r^2 \\cdot h$. $\\blacksquare$"),
    P("prf_cone_volume", "thm_cone_volume",
      ["def_cone", "thm_volume_of_revolution_disc"],
      "חרוט גובה $h$ ורדיוס בסיס $r$ הוא גוף הסיבוב של משולש ישר-זווית. גרף הצלע: $f(x) = \\frac{r x}{h}$ ב-$[0, h]$.\n\n$V = \\pi \\int_0^h \\left(\\frac{r x}{h}\\right)^2 \\, dx = \\frac{\\pi r^2}{h^2} \\cdot \\frac{x^3}{3}\\Big|_0^h = \\frac{\\pi r^2 h}{3}$. $\\blacksquare$"),
    P("prf_sphere_volume", "thm_sphere_volume",
      ["def_sphere", "thm_volume_of_revolution_disc"],
      "כדור ברדיוס $R$ הוא גוף הסיבוב של חצי-מעגל $f(x) = \\sqrt{R^2 - x^2}$ סביב ציר $x$.\n\n$V = \\pi \\int_{-R}^{R} (R^2 - x^2) \\, dx = \\pi \\left[R^2 x - \\frac{x^3}{3}\\right]_{-R}^{R} = \\pi \\cdot \\left(\\frac{4 R^3}{3}\\right) = \\frac{4}{3}\\pi R^3$. $\\blacksquare$"),

    # ── Trig sum-to-product ──
    P("prf_sum_to_product_sin", "thm_sum_to_product_sin",
      ["thm_sin_addition_formula", "thm_sin_subtraction_formula"],
      "נסמן $\\alpha = A + B$, $\\beta = A - B$ (כך ש-$A = \\frac{\\alpha+\\beta}{2}$, $B = \\frac{\\alpha-\\beta}{2}$).\n\n$\\sin(A+B) + \\sin(A-B) = (\\sin A \\cos B + \\cos A \\sin B) + (\\sin A \\cos B - \\cos A \\sin B) = 2 \\sin A \\cos B$.\n\nכלומר $\\sin\\alpha + \\sin\\beta = 2 \\sin\\frac{\\alpha+\\beta}{2} \\cos\\frac{\\alpha-\\beta}{2}$. $\\blacksquare$"),
    P("prf_sum_to_product_cos", "thm_sum_to_product_cos",
      ["thm_cos_addition_formula", "thm_cos_subtraction_formula"],
      "באותה החלפת משתנים: $\\cos(A+B) + \\cos(A-B) = 2 \\cos A \\cos B$.\n\nלכן $\\cos\\alpha + \\cos\\beta = 2 \\cos\\frac{\\alpha+\\beta}{2} \\cos\\frac{\\alpha-\\beta}{2}$. $\\blacksquare$"),
    P("prf_half_angle_cos", "thm_half_angle_cos",
      ["thm_cos_double_angle"],
      "מנוסחת זווית כפולה $\\cos\\alpha = 2\\cos^2\\frac{\\alpha}{2} - 1$.\n\nסידור: $\\cos^2\\frac{\\alpha}{2} = \\frac{1 + \\cos\\alpha}{2}$. $\\blacksquare$"),
    P("prf_half_angle_sin", "thm_half_angle_sin",
      ["thm_cos_double_angle"],
      "$\\cos\\alpha = 1 - 2\\sin^2\\frac{\\alpha}{2}$, ולכן $\\sin^2\\frac{\\alpha}{2} = \\frac{1 - \\cos\\alpha}{2}$. $\\blacksquare$"),

    # ── Series ──
    P("prf_necessary_condition_convergence", "thm_necessary_condition_convergence",
      ["def_series_convergence", "def_partial_sum", "def_limit_of_sequence"],
      "אם $\\sum a_n$ מתכנס לסכום $S$, אז $S_n \\to S$ ו-$S_{n-1} \\to S$.\n\n$a_n = S_n - S_{n-1} \\to S - S = 0$. $\\blacksquare$"),
    P("prf_telescoping_series", "thm_telescoping_series",
      ["def_partial_sum", "def_series_convergence"],
      "$S_n = (b_1 - b_2) + (b_2 - b_3) + \\cdots + (b_n - b_{n+1}) = b_1 - b_{n+1}$ (קנצלציה ביניים).\n\nאם $\\lim b_n = L$ אז $\\lim S_n = b_1 - L$, וזה סכום הטור. אחרת הטור מתבדר. $\\blacksquare$"),

    # ── Number theory ──
    P("prf_euclidean_algorithm", "thm_euclidean_algorithm",
      ["def_gcd", "thm_division_algorithm", "thm_divisibility_linear_combinations"],
      "מאלגוריתם החילוק $a = b q + r$, כל מחלק משותף של $a$ ו-$b$ מחלק גם את $r = a - b q$. ובאותו אופן כל מחלק משותף של $b$ ו-$r$ מחלק את $a$.\n\nלכן קבוצת המחלקים המשותפים של $(a, b)$ זהה לקבוצת המחלקים המשותפים של $(b, r)$, ובפרט ה-GCD שווה. $\\blacksquare$"),
    P("prf_bezout_identity", "thm_bezout_identity",
      ["thm_euclidean_algorithm", "def_gcd", "def_integers"],
      "מבצעים את אלגוריתם אוקלידס. בכל שלב הוא יוצר משוואה $r_i = r_{i-2} - q_i \\cdot r_{i-1}$.\n\nע״י החלפה לאחור, מבטאים את ה-GCD (הוא $r_{k}$ האחרון לפני $r = 0$) כצירוף לינארי שלם של $a$ ו-$b$: $\\gcd(a, b) = a x + b y$. $\\blacksquare$"),
    P("prf_modular_arithmetic_properties", "thm_modular_arithmetic_properties",
      ["def_congruence_mod", "def_divisibility"],
      "$a \\equiv b$ פירושו $n \\mid (a - b)$, ובאופן דומה $n \\mid (c - d)$.\n\n**חיבור:** $(a + c) - (b + d) = (a - b) + (c - d)$, סכום שני מספרים שמתחלקים ב-$n$, ולכן מתחלק ב-$n$ → $a + c \\equiv b + d$.\n\n**כפל:** $ac - bd = ac - bc + bc - bd = (a - b) c + b (c - d)$, צירוף לינארי של מספרים שמתחלקים ב-$n$. $\\blacksquare$"),

    # ── Inequalities ──
    P("prf_squared_inequality", "thm_squared_inequality",
      ["thm_square_nonnegative"],
      "$(a - b)^2 \\geq 0$ לכל $a, b$ (משפט ריבוע אי-שלילי).\n\nפתיחה: $a^2 - 2ab + b^2 \\geq 0$, ולכן $a^2 + b^2 \\geq 2ab$. שוויון ב-$a = b$. $\\blacksquare$"),
    P("prf_am_gm_two_variables", "thm_am_gm_two_variables",
      ["thm_squared_inequality", "def_square_root"],
      "עבור $a, b \\geq 0$: $(\\sqrt{a} - \\sqrt{b})^2 \\geq 0$, פתיחה: $a + b \\geq 2\\sqrt{ab}$.\n\nחלוקה ב-$2$: $\\frac{a + b}{2} \\geq \\sqrt{ab}$. שוויון כאשר $\\sqrt{a} = \\sqrt{b}$, כלומר $a = b$. $\\blacksquare$"),
    P("prf_cauchy_schwarz_inequality_vectors", "thm_cauchy_schwarz_inequality_vectors",
      ["thm_dot_product_geometric", "def_cos"],
      "מנוסחת המכפלה הסקלרית הגאומטרית: $\\vec{u} \\cdot \\vec{v} = |\\vec{u}| |\\vec{v}| \\cos\\theta$.\n\nכי $|\\cos\\theta| \\leq 1$: $|\\vec{u} \\cdot \\vec{v}| \\leq |\\vec{u}| |\\vec{v}|$. שוויון כאשר $\\cos\\theta = \\pm 1$, כלומר וקטורים מקבילים. $\\blacksquare$"),
    P("prf_triangle_inequality_vectors", "thm_triangle_inequality_vectors",
      ["thm_cauchy_schwarz_inequality_vectors", "def_vector_magnitude",
       "def_dot_product"],
      "$|\\vec{u} + \\vec{v}|^2 = (\\vec{u} + \\vec{v}) \\cdot (\\vec{u} + \\vec{v}) = |\\vec{u}|^2 + 2 \\vec{u} \\cdot \\vec{v} + |\\vec{v}|^2$.\n\nלפי קושי-שוורץ: $\\vec{u} \\cdot \\vec{v} \\leq |\\vec{u}||\\vec{v}|$. לכן $|\\vec{u} + \\vec{v}|^2 \\leq (|\\vec{u}| + |\\vec{v}|)^2$, ובשורש: $|\\vec{u} + \\vec{v}| \\leq |\\vec{u}| + |\\vec{v}|$. $\\blacksquare$"),

    # ── Integration advanced ──
    P("prf_integration_logarithmic", "thm_integration_logarithmic",
      ["thm_integral_one_over_x", "thm_integral_substitution",
       "thm_derivative_log_natural"],
      "הצבה $u = f(x)$, $du = f'(x) dx$. אז $\\int \\frac{f'(x)}{f(x)} dx = \\int \\frac{1}{u} du = \\ln|u| + C = \\ln|f(x)| + C$. $\\blacksquare$"),
    P("prf_mean_value_for_integrals", "thm_mean_value_for_integrals",
      ["thm_extreme_value_theorem", "thm_intermediate_value",
       "def_definite_integral"],
      "כי $f$ רציפה ב-$[a, b]$, לפי ויירשטראס יש לה מינימום $m$ ומקסימום $M$.\n\nאז $m(b - a) \\leq \\int_a^b f \\leq M(b - a)$, כלומר $m \\leq \\frac{1}{b-a}\\int_a^b f \\leq M$.\n\nלפי משפט ערך הביניים, יש $c \\in [a, b]$ עם $f(c) = \\frac{1}{b-a}\\int_a^b f$. $\\blacksquare$"),

    # ── Misc ──
    P("prf_exponential_growth_derivative", "thm_exponential_growth_derivative",
      ["thm_derivative_exp", "thm_derivative_chain",
       "def_exponential_growth_model"],
      "אם $y = y_0 e^{kt}$ אז $y' = y_0 e^{kt} \\cdot k = k \\cdot y$, ו-$y(0) = y_0$.\n\nיחידות: אם $z$ פתרון אחר של $z' = kz$ עם $z(0) = y_0$, נגדיר $w = z/y$. אז $w' = (z' y - z y')/y^2 = (kzy - kzy)/y^2 = 0$, ולכן $w$ קבוע. ערך התחלתי $w(0) = 1$, אז $z = y$. $\\blacksquare$"),
    P("prf_chord_in_circle_length", "thm_chord_in_circle_length",
      ["def_circle", "thm_pythagoras",
       "thm_perpendicular_diameter_bisects_chord"],
      "אנך ממרכז המעגל אל המיתר חוצה אותו (משפט אנך לקוטר). נסמן את אורך חצי המיתר $\\ell$, המרחק מהמרכז $d$, והרדיוס $r$.\n\nמשולש ישר-זווית עם ניצבים $\\ell, d$ ויתר $r$: $r^2 = \\ell^2 + d^2 \\Rightarrow \\ell = \\sqrt{r^2 - d^2}$, ולכן המיתר $2\\ell = 2\\sqrt{r^2 - d^2}$. $\\blacksquare$"),
]
